         static int AdoscLookback( int           optInFastPeriod  /* From 2 to 100000 */, int           optInSlowPeriod  /* From 2 to 100000 */ );

#if defined( _MANAGED ) && defined( USE_SUBARRAY )
         static enum class RetCode Adosc( int    startIdx,
                                          int    endIdx,
                                          SubArray<double>^ inHigh,
                                          SubArray<double>^ inLow,
                                          SubArray<double>^ inClose,
                                          SubArray<double>^ inVolume,
                                          int optInFastPeriod,
                                          int optInSlowPeriod,
                                          [Out]int%    outBegIdx,
                                          [Out]int%    outNBElement,
                                          SubArray<double>^  outReal );

         static enum class RetCode Adosc( int    startIdx,
                                          int    endIdx,
                                          SubArray<float>^ inHigh,
                                          SubArray<float>^ inLow,
                                          SubArray<float>^ inClose,
                                          SubArray<float>^ inVolume,
                                          int optInFastPeriod,
                                          int optInSlowPeriod,
                                          [Out]int%    outBegIdx,
                                          [Out]int%    outNBElement,
                                          SubArray<double>^  outReal );

         static enum class RetCode Adosc( int    startIdx,
                                          int    endIdx,
                                          cli::array<double>^ inHigh,
                                          cli::array<double>^ inLow,
                                          cli::array<double>^ inClose,
                                          cli::array<double>^ inVolume,
                                          int optInFastPeriod,
                                          int optInSlowPeriod,
                                          [Out]int%    outBegIdx,
                                          [Out]int%    outNBElement,
                                          cli::array<double>^  outReal )
         { return Adosc( startIdx, endIdx,
                         gcnew SubArrayFrom1D<double>(inHigh,0),
                         gcnew SubArrayFrom1D<double>(inLow,0),
                         gcnew SubArrayFrom1D<double>(inClose,0),
                         gcnew SubArrayFrom1D<double>(inVolume,0),
                         optInFastPeriod,
                         optInSlowPeriod,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
         static enum class RetCode Adosc( int    startIdx,
                                          int    endIdx,
                                          cli::array<float>^ inHigh,
                                          cli::array<float>^ inLow,
                                          cli::array<float>^ inClose,
                                          cli::array<float>^ inVolume,
                                          int optInFastPeriod,
                                          int optInSlowPeriod,
                                          [Out]int%    outBegIdx,
                                          [Out]int%    outNBElement,
                                          cli::array<double>^  outReal )
         { return Adosc( startIdx, endIdx,
                         gcnew SubArrayFrom1D<float>(inHigh,0),
                         gcnew SubArrayFrom1D<float>(inLow,0),
                         gcnew SubArrayFrom1D<float>(inClose,0),
                         gcnew SubArrayFrom1D<float>(inVolume,0),
                         optInFastPeriod,
                         optInSlowPeriod,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
#elif defined( _MANAGED )
         static enum class RetCode Adosc( int    startIdx,
                                          int    endIdx,
                                          cli::array<double>^ inHigh,
                                          cli::array<double>^ inLow,
                                          cli::array<double>^ inClose,
                                          cli::array<double>^ inVolume,
                                          int optInFastPeriod,
                                          int optInSlowPeriod,
                                          [Out]int%    outBegIdx,
                                          [Out]int%    outNBElement,
                                          cli::array<double>^  outReal );
         static enum class RetCode Adosc( int    startIdx,
                                          int    endIdx,
                                          cli::array<float>^ inHigh,
                                          cli::array<float>^ inLow,
                                          cli::array<float>^ inClose,
                                          cli::array<float>^ inVolume,
                                          int optInFastPeriod,
                                          int optInSlowPeriod,
                                          [Out]int%    outBegIdx,
                                          [Out]int%    outNBElement,
                                          cli::array<double>^  outReal );
#endif

#if defined( _MANAGED ) && defined( USE_SUBARRAY )
         static enum class RetCode AdoscLogic( int    startIdx,
                                               int    endIdx,
                                               SubArray<double>^ inHigh,
                                               SubArray<double>^ inLow,
                                               SubArray<double>^ inClose,
                                               SubArray<double>^ inVolume,
                                               int optInFastPeriod,
                                               int optInSlowPeriod,
                                               [Out]int%    outBegIdx,
                                               [Out]int%    outNBElement,
                                               SubArray<double>^  outReal );

         static enum class RetCode AdoscLogic( int    startIdx,
                                               int    endIdx,
                                               SubArray<float>^ inHigh,
                                               SubArray<float>^ inLow,
                                               SubArray<float>^ inClose,
                                               SubArray<float>^ inVolume,
                                               int optInFastPeriod,
                                               int optInSlowPeriod,
                                               [Out]int%    outBegIdx,
                                               [Out]int%    outNBElement,
                                               SubArray<double>^  outReal );

         static enum class RetCode AdoscLogic( int    startIdx,
                                               int    endIdx,
                                               cli::array<double>^ inHigh,
                                               cli::array<double>^ inLow,
                                               cli::array<double>^ inClose,
                                               cli::array<double>^ inVolume,
                                               int optInFastPeriod,
                                               int optInSlowPeriod,
                                               [Out]int%    outBegIdx,
                                               [Out]int%    outNBElement,
                                               cli::array<double>^  outReal )
         { return AdoscLogic( startIdx, endIdx,
                         gcnew SubArrayFrom1D<double>(inHigh,0),
                         gcnew SubArrayFrom1D<double>(inLow,0),
                         gcnew SubArrayFrom1D<double>(inClose,0),
                         gcnew SubArrayFrom1D<double>(inVolume,0),
                         optInFastPeriod,
                         optInSlowPeriod,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
         static enum class RetCode AdoscLogic( int    startIdx,
                                               int    endIdx,
                                               cli::array<float>^ inHigh,
                                               cli::array<float>^ inLow,
                                               cli::array<float>^ inClose,
                                               cli::array<float>^ inVolume,
                                               int optInFastPeriod,
                                               int optInSlowPeriod,
                                               [Out]int%    outBegIdx,
                                               [Out]int%    outNBElement,
                                               cli::array<double>^  outReal )
         { return AdoscLogic( startIdx, endIdx,
                         gcnew SubArrayFrom1D<float>(inHigh,0),
                         gcnew SubArrayFrom1D<float>(inLow,0),
                         gcnew SubArrayFrom1D<float>(inClose,0),
                         gcnew SubArrayFrom1D<float>(inVolume,0),
                         optInFastPeriod,
                         optInSlowPeriod,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
#elif defined( _MANAGED )
         static enum class RetCode AdoscLogic( int    startIdx,
                                               int    endIdx,
                                               cli::array<double>^ inHigh,
                                               cli::array<double>^ inLow,
                                               cli::array<double>^ inClose,
                                               cli::array<double>^ inVolume,
                                               int optInFastPeriod,
                                               int optInSlowPeriod,
                                               [Out]int%    outBegIdx,
                                               [Out]int%    outNBElement,
                                               cli::array<double>^  outReal );
         static enum class RetCode AdoscLogic( int    startIdx,
                                               int    endIdx,
                                               cli::array<float>^ inHigh,
                                               cli::array<float>^ inLow,
                                               cli::array<float>^ inClose,
                                               cli::array<float>^ inVolume,
                                               int optInFastPeriod,
                                               int optInSlowPeriod,
                                               [Out]int%    outBegIdx,
                                               [Out]int%    outNBElement,
                                               cli::array<double>^  outReal );
#endif

         #define TA_ADOSC Core::Adosc
         #define TA_ADOSC_Lookback Core::AdoscLookback
         #define TA_ADOSC_Logic Core::AdoscLogic
