         static int UltoscLookback( int           optInTimePeriod1  /* From 1 to 100000 */, int           optInTimePeriod2  /* From 1 to 100000 */, int           optInTimePeriod3  /* From 1 to 100000 */ );

#if defined( _MANAGED ) && defined( USE_SUBARRAY )
         static enum class RetCode Ultosc( int    startIdx,
                                           int    endIdx,
                                           SubArray<double>^ inHigh,
                                           SubArray<double>^ inLow,
                                           SubArray<double>^ inClose,
                                           int optInTimePeriod1,
                                           int optInTimePeriod2,
                                           int optInTimePeriod3,
                                           [Out]int%    outBegIdx,
                                           [Out]int%    outNBElement,
                                           SubArray<double>^  outReal );

         static enum class RetCode Ultosc( int    startIdx,
                                           int    endIdx,
                                           SubArray<float>^ inHigh,
                                           SubArray<float>^ inLow,
                                           SubArray<float>^ inClose,
                                           int optInTimePeriod1,
                                           int optInTimePeriod2,
                                           int optInTimePeriod3,
                                           [Out]int%    outBegIdx,
                                           [Out]int%    outNBElement,
                                           SubArray<double>^  outReal );

         static enum class RetCode Ultosc( int    startIdx,
                                           int    endIdx,
                                           cli::array<double>^ inHigh,
                                           cli::array<double>^ inLow,
                                           cli::array<double>^ inClose,
                                           int optInTimePeriod1,
                                           int optInTimePeriod2,
                                           int optInTimePeriod3,
                                           [Out]int%    outBegIdx,
                                           [Out]int%    outNBElement,
                                           cli::array<double>^  outReal )
         { return Ultosc( startIdx, endIdx,
                         gcnew SubArrayFrom1D<double>(inHigh,0),
                         gcnew SubArrayFrom1D<double>(inLow,0),
                         gcnew SubArrayFrom1D<double>(inClose,0),
                         optInTimePeriod1,
                         optInTimePeriod2,
                         optInTimePeriod3,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
         static enum class RetCode Ultosc( int    startIdx,
                                           int    endIdx,
                                           cli::array<float>^ inHigh,
                                           cli::array<float>^ inLow,
                                           cli::array<float>^ inClose,
                                           int optInTimePeriod1,
                                           int optInTimePeriod2,
                                           int optInTimePeriod3,
                                           [Out]int%    outBegIdx,
                                           [Out]int%    outNBElement,
                                           cli::array<double>^  outReal )
         { return Ultosc( startIdx, endIdx,
                         gcnew SubArrayFrom1D<float>(inHigh,0),
                         gcnew SubArrayFrom1D<float>(inLow,0),
                         gcnew SubArrayFrom1D<float>(inClose,0),
                         optInTimePeriod1,
                         optInTimePeriod2,
                         optInTimePeriod3,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
#elif defined( _MANAGED )
         static enum class RetCode Ultosc( int    startIdx,
                                           int    endIdx,
                                           cli::array<double>^ inHigh,
                                           cli::array<double>^ inLow,
                                           cli::array<double>^ inClose,
                                           int optInTimePeriod1,
                                           int optInTimePeriod2,
                                           int optInTimePeriod3,
                                           [Out]int%    outBegIdx,
                                           [Out]int%    outNBElement,
                                           cli::array<double>^  outReal );
         static enum class RetCode Ultosc( int    startIdx,
                                           int    endIdx,
                                           cli::array<float>^ inHigh,
                                           cli::array<float>^ inLow,
                                           cli::array<float>^ inClose,
                                           int optInTimePeriod1,
                                           int optInTimePeriod2,
                                           int optInTimePeriod3,
                                           [Out]int%    outBegIdx,
                                           [Out]int%    outNBElement,
                                           cli::array<double>^  outReal );
#endif

#if defined( _MANAGED ) && defined( USE_SUBARRAY )
         static enum class RetCode UltoscLogic( int    startIdx,
                                                int    endIdx,
                                                SubArray<double>^ inHigh,
                                                SubArray<double>^ inLow,
                                                SubArray<double>^ inClose,
                                                int optInTimePeriod1,
                                                int optInTimePeriod2,
                                                int optInTimePeriod3,
                                                [Out]int%    outBegIdx,
                                                [Out]int%    outNBElement,
                                                SubArray<double>^  outReal );

         static enum class RetCode UltoscLogic( int    startIdx,
                                                int    endIdx,
                                                SubArray<float>^ inHigh,
                                                SubArray<float>^ inLow,
                                                SubArray<float>^ inClose,
                                                int optInTimePeriod1,
                                                int optInTimePeriod2,
                                                int optInTimePeriod3,
                                                [Out]int%    outBegIdx,
                                                [Out]int%    outNBElement,
                                                SubArray<double>^  outReal );

         static enum class RetCode UltoscLogic( int    startIdx,
                                                int    endIdx,
                                                cli::array<double>^ inHigh,
                                                cli::array<double>^ inLow,
                                                cli::array<double>^ inClose,
                                                int optInTimePeriod1,
                                                int optInTimePeriod2,
                                                int optInTimePeriod3,
                                                [Out]int%    outBegIdx,
                                                [Out]int%    outNBElement,
                                                cli::array<double>^  outReal )
         { return UltoscLogic( startIdx, endIdx,
                         gcnew SubArrayFrom1D<double>(inHigh,0),
                         gcnew SubArrayFrom1D<double>(inLow,0),
                         gcnew SubArrayFrom1D<double>(inClose,0),
                         optInTimePeriod1,
                         optInTimePeriod2,
                         optInTimePeriod3,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
         static enum class RetCode UltoscLogic( int    startIdx,
                                                int    endIdx,
                                                cli::array<float>^ inHigh,
                                                cli::array<float>^ inLow,
                                                cli::array<float>^ inClose,
                                                int optInTimePeriod1,
                                                int optInTimePeriod2,
                                                int optInTimePeriod3,
                                                [Out]int%    outBegIdx,
                                                [Out]int%    outNBElement,
                                                cli::array<double>^  outReal )
         { return UltoscLogic( startIdx, endIdx,
                         gcnew SubArrayFrom1D<float>(inHigh,0),
                         gcnew SubArrayFrom1D<float>(inLow,0),
                         gcnew SubArrayFrom1D<float>(inClose,0),
                         optInTimePeriod1,
                         optInTimePeriod2,
                         optInTimePeriod3,
             outBegIdx,
             outNBElement,
               gcnew SubArrayFrom1D<double>(outReal,0) );
         }
#elif defined( _MANAGED )
         static enum class RetCode UltoscLogic( int    startIdx,
                                                int    endIdx,
                                                cli::array<double>^ inHigh,
                                                cli::array<double>^ inLow,
                                                cli::array<double>^ inClose,
                                                int optInTimePeriod1,
                                                int optInTimePeriod2,
                                                int optInTimePeriod3,
                                                [Out]int%    outBegIdx,
                                                [Out]int%    outNBElement,
                                                cli::array<double>^  outReal );
         static enum class RetCode UltoscLogic( int    startIdx,
                                                int    endIdx,
                                                cli::array<float>^ inHigh,
                                                cli::array<float>^ inLow,
                                                cli::array<float>^ inClose,
                                                int optInTimePeriod1,
                                                int optInTimePeriod2,
                                                int optInTimePeriod3,
                                                [Out]int%    outBegIdx,
                                                [Out]int%    outNBElement,
                                                cli::array<double>^  outReal );
#endif

         #define TA_ULTOSC Core::Ultosc
         #define TA_ULTOSC_Lookback Core::UltoscLookback
         #define TA_ULTOSC_Logic Core::UltoscLogic
