/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::adosc`].
    ///
    /// # Arguments
    ///
    /// * `optInFastPeriod` - Number of period (default: 3, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 10, range: 2..=100000)
    #[inline]
    pub fn adosc_lookback(&self, mut optInFastPeriod: i32, mut optInSlowPeriod: i32) -> usize {
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 3;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 10;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        let mut slowestPeriod: usize = 0_usize;
        if optInFastPeriod < optInSlowPeriod {
            slowestPeriod = (optInSlowPeriod) as usize;
        } else {
            slowestPeriod = (optInFastPeriod) as usize;
        }
        return self.ema_lookback((slowestPeriod) as i32);
    }
    /// Chaikin A/D Oscillator
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `inVolume` - Input price series
    /// * `optInFastPeriod` - Number of period (default: 3, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 10, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn adosc(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 3;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 10;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut slowestPeriod: usize = 0_usize;
        let mut high: f64 = 0.0_f64;
        let mut low: f64 = 0.0_f64;
        let mut close: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut slowEMA: f64 = 0.0_f64;
        let mut slowk: f64 = 0.0_f64;
        let mut one_minus_slowk: f64 = 0.0_f64;
        let mut fastEMA: f64 = 0.0_f64;
        let mut fastk: f64 = 0.0_f64;
        let mut one_minus_fastk: f64 = 0.0_f64;
        let mut ad: f64 = 0.0_f64;
        if optInFastPeriod < optInSlowPeriod {
            slowestPeriod = (optInSlowPeriod) as usize;
        } else {
            slowestPeriod = (optInFastPeriod) as usize;
        }
        lookbackTotal = self.ema_lookback((slowestPeriod) as i32);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        today = startIdx - lookbackTotal;
        ad = 0.0;
        fastk = 2.0 / (((optInFastPeriod) as f64) + 1.0);
        one_minus_fastk = 1.0 - fastk;
        slowk = 2.0 / (((optInSlowPeriod) as f64) + 1.0);
        one_minus_slowk = 1.0 - slowk;
        high = inHigh[today];
        low = inLow[today];
        tmp = high - low;
        close = inClose[today];
        if tmp > 0.0 {
            ad += (close - low - (high - close)) / tmp * ((inVolume[today]) as f64);
        }
        today += 1;
        fastEMA = ad;
        slowEMA = ad;
        while today < startIdx {
            high = inHigh[today];
            low = inLow[today];
            tmp = high - low;
            close = inClose[today];
            if tmp > 0.0 {
                ad += (close - low - (high - close)) / tmp * ((inVolume[today]) as f64);
            }
            today += 1;
            fastEMA = (fastk as f64).mul_add(ad, one_minus_fastk * fastEMA);
            slowEMA = (slowk as f64).mul_add(ad, one_minus_slowk * slowEMA);
        }
        outIdx = 0;
        while today <= endIdx {
            high = inHigh[today];
            low = inLow[today];
            tmp = high - low;
            close = inClose[today];
            if tmp > 0.0 {
                ad += (close - low - (high - close)) / tmp * ((inVolume[today]) as f64);
            }
            today += 1;
            fastEMA = (fastk as f64).mul_add(ad, one_minus_fastk * fastEMA);
            slowEMA = (slowk as f64).mul_add(ad, one_minus_slowk * slowEMA);
            outReal[outIdx] = fastEMA - slowEMA;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn adosc_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut slowestPeriod: usize = 0_usize;
        let mut high: f64 = 0.0_f64;
        let mut low: f64 = 0.0_f64;
        let mut close: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut slowEMA: f64 = 0.0_f64;
        let mut slowk: f64 = 0.0_f64;
        let mut one_minus_slowk: f64 = 0.0_f64;
        let mut fastEMA: f64 = 0.0_f64;
        let mut fastk: f64 = 0.0_f64;
        let mut one_minus_fastk: f64 = 0.0_f64;
        let mut ad: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx < inVolume.len());
        assert!(endIdx - startIdx < outReal.len());
        if optInFastPeriod < optInSlowPeriod {
            slowestPeriod = (optInSlowPeriod) as usize;
        } else {
            slowestPeriod = (optInFastPeriod) as usize;
        }
        lookbackTotal = self.ema_lookback((slowestPeriod) as i32);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        today = startIdx - lookbackTotal;
        ad = 0.0;
        fastk = 2.0 / (((optInFastPeriod) as f64) + 1.0);
        one_minus_fastk = 1.0 - fastk;
        slowk = 2.0 / (((optInSlowPeriod) as f64) + 1.0);
        one_minus_slowk = 1.0 - slowk;
        high = *inHigh.as_ptr().add(today);
        low = *inLow.as_ptr().add(today);
        tmp = high - low;
        close = *inClose.as_ptr().add(today);
        if tmp > 0.0 {
            ad += (close - low - (high - close)) / tmp * ((*inVolume.as_ptr().add(today)) as f64);
        }
        today += 1;
        fastEMA = ad;
        slowEMA = ad;
        while today < startIdx {
            high = *inHigh.as_ptr().add(today);
            low = *inLow.as_ptr().add(today);
            tmp = high - low;
            close = *inClose.as_ptr().add(today);
            if tmp > 0.0 {
                ad += (close - low - (high - close)) / tmp * ((*inVolume.as_ptr().add(today)) as f64);
            }
            today += 1;
            fastEMA = (fastk as f64).mul_add(ad, one_minus_fastk * fastEMA);
            slowEMA = (slowk as f64).mul_add(ad, one_minus_slowk * slowEMA);
        }
        outIdx = 0;
        while today <= endIdx {
            high = *inHigh.as_ptr().add(today);
            low = *inLow.as_ptr().add(today);
            tmp = high - low;
            close = *inClose.as_ptr().add(today);
            if tmp > 0.0 {
                ad += (close - low - (high - close)) / tmp * ((*inVolume.as_ptr().add(today)) as f64);
            }
            today += 1;
            fastEMA = (fastk as f64).mul_add(ad, one_minus_fastk * fastEMA);
            slowEMA = (slowk as f64).mul_add(ad, one_minus_slowk * slowEMA);
            *outReal.as_mut_ptr().add(outIdx) = fastEMA - slowEMA;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
