/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::apo`].
    ///
    /// # Arguments
    ///
    /// * `optInFastPeriod` - Number of period (default: 12, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 26, range: 2..=100000)
    #[inline]
    pub fn apo_lookback(&self, mut optInFastPeriod: i32, mut optInSlowPeriod: i32, mut optInMAType: i32) -> usize {
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return self.ma_lookback((optInSlowPeriod).max(optInFastPeriod), optInMAType);
    }
    /// Absolute Price Oscillator
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInFastPeriod` - Number of period (default: 12, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 26, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn apo(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut tempInteger: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement2: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        tempBuffer = vec![0.0_f64; ((endIdx - startIdx + 1) * 1) as usize];
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = (optInSlowPeriod) as usize;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = (tempInteger) as i32;
        }
        retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInFastPeriod, optInMAType, &mut outBegIdx2, &mut outNbElement2, &mut tempBuffer[..]);
        if retCode == RetCode::Success {
            retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInSlowPeriod, optInMAType, &mut outBegIdx1, &mut outNbElement1, outReal);
            if retCode == RetCode::Success {
                tempInteger = outBegIdx1 - outBegIdx2;
                // for( i = 0, j = tempInteger; i < outNbElement1; i += 1, j += 1 )
                i = 0;
                j = tempInteger;
                while i < outNbElement1 {
                    outReal[i] = ((tempBuffer[j] - outReal[i]) as f64);
                    i += 1;
                    j += 1;
                }
                (*outBegIdx) = outBegIdx1;
                (*outNBElement) = outNbElement1;
            }
        }
        return retCode;
    }
    #[inline]
    pub fn apo_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInFastPeriod: i32,
        mut optInSlowPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut tempInteger: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement2: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        tempBuffer = vec![0.0_f64; ((endIdx - startIdx + 1) * 1) as usize];
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = (optInSlowPeriod) as usize;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = (tempInteger) as i32;
        }
        retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInFastPeriod, optInMAType, &mut outBegIdx2, &mut outNbElement2, &mut tempBuffer[..]);
        if retCode == RetCode::Success {
            retCode = self.ma_unguarded(startIdx, endIdx, inReal, optInSlowPeriod, optInMAType, &mut outBegIdx1, &mut outNbElement1, outReal);
            if retCode == RetCode::Success {
                tempInteger = outBegIdx1 - outBegIdx2;
                // for( i = 0, j = tempInteger; i < outNbElement1; i += 1, j += 1 )
                i = 0;
                j = tempInteger;
                while i < outNbElement1 {
                    *outReal.as_mut_ptr().add(i) = ((*tempBuffer.as_ptr().add(j) - *outReal.as_ptr().add(i)) as f64);
                    i += 1;
                    j += 1;
                }
                (*outBegIdx) = outBegIdx1;
                (*outNBElement) = outNbElement1;
            }
        }
        return retCode;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
