/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::aroon`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    #[inline]
    pub fn aroon_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod) as usize;
    }
    /// Aroon
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outAroonDown` - Output values
    /// * `outAroonUp` - Output values
    pub fn aroon(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outAroonDown: &mut [f64],
        outAroonUp: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut lowest: f64 = 0.0_f64;
        let mut highest: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut factor: f64 = 0.0_f64;
        let mut outIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut lowestIdx: i32 = 0_i32;
        let mut highestIdx: i32 = 0_i32;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        if startIdx < (optInTimePeriod) as usize {
            startIdx = (optInTimePeriod) as usize;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        trailingIdx = startIdx - (optInTimePeriod) as usize;
        lowestIdx = 0 - 1;
        highestIdx = 0 - 1;
        lowest = 0.0;
        highest = 0.0;
        factor = ((100.0) as f64) / ((optInTimePeriod) as f64);
        while today <= endIdx {
            tmp = inLow[today];
            if lowestIdx < (trailingIdx) as i32 {
                lowestIdx = (trailingIdx) as i32;
                lowest = inLow[(lowestIdx) as usize];
                i = (lowestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = inLow[i];
                    if tmp <= lowest {
                        lowestIdx = (i) as i32;
                        lowest = tmp;
                    }
                }
            } else if tmp <= lowest {
                lowestIdx = (today) as i32;
                lowest = tmp;
            }
            tmp = inHigh[today];
            if highestIdx < (trailingIdx) as i32 {
                highestIdx = (trailingIdx) as i32;
                highest = inHigh[(highestIdx) as usize];
                i = (highestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = inHigh[i];
                    if tmp >= highest {
                        highestIdx = (i) as i32;
                        highest = tmp;
                    }
                }
            } else if tmp >= highest {
                highestIdx = (today) as i32;
                highest = tmp;
            }
            outAroonUp[outIdx] = factor * (((optInTimePeriod - ((today) as i32 - highestIdx))) as f64);
            outAroonDown[outIdx] = factor * (((optInTimePeriod - ((today) as i32 - lowestIdx))) as f64);
            outIdx += 1;
            trailingIdx += 1;
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn aroon_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outAroonDown: &mut [f64],
        outAroonUp: &mut [f64],
    ) -> RetCode {
        let mut lowest: f64 = 0.0_f64;
        let mut highest: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut factor: f64 = 0.0_f64;
        let mut outIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut lowestIdx: i32 = 0_i32;
        let mut highestIdx: i32 = 0_i32;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx - startIdx < outAroonDown.len());
        assert!(endIdx - startIdx < outAroonUp.len());
        if startIdx < (optInTimePeriod) as usize {
            startIdx = (optInTimePeriod) as usize;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        trailingIdx = startIdx - (optInTimePeriod) as usize;
        lowestIdx = 0 - 1;
        highestIdx = 0 - 1;
        lowest = 0.0;
        highest = 0.0;
        factor = ((100.0) as f64) / ((optInTimePeriod) as f64);
        while today <= endIdx {
            tmp = *inLow.as_ptr().add(today);
            if lowestIdx < (trailingIdx) as i32 {
                lowestIdx = (trailingIdx) as i32;
                lowest = *inLow.as_ptr().add((lowestIdx) as usize);
                i = (lowestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = *inLow.as_ptr().add(i);
                    if tmp <= lowest {
                        lowestIdx = (i) as i32;
                        lowest = tmp;
                    }
                }
            } else if tmp <= lowest {
                lowestIdx = (today) as i32;
                lowest = tmp;
            }
            tmp = *inHigh.as_ptr().add(today);
            if highestIdx < (trailingIdx) as i32 {
                highestIdx = (trailingIdx) as i32;
                highest = *inHigh.as_ptr().add((highestIdx) as usize);
                i = (highestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = *inHigh.as_ptr().add(i);
                    if tmp >= highest {
                        highestIdx = (i) as i32;
                        highest = tmp;
                    }
                }
            } else if tmp >= highest {
                highestIdx = (today) as i32;
                highest = tmp;
            }
            *outAroonUp.as_mut_ptr().add(outIdx) = factor * (((optInTimePeriod - ((today) as i32 - highestIdx))) as f64);
            *outAroonDown.as_mut_ptr().add(outIdx) = factor * (((optInTimePeriod - ((today) as i32 - lowestIdx))) as f64);
            outIdx += 1;
            trailingIdx += 1;
            today += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
