/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::atr`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    #[inline]
    pub fn atr_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod + self.unstable_period[FuncUnstId::Atr as usize]) as usize;
    }
    /// Average True Range
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn atr(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut retCode: RetCode = RetCode::Success;
        let mut outIdx: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut nbATR: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut prevATR: f64 = 0.0_f64;
        let mut tempBuffer: Vec<f64> = Vec::new();
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = self.atr_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        if optInTimePeriod <= 1 {
            return self.trange_unguarded(startIdx, endIdx, inHigh, inLow, inClose, outBegIdx, outNBElement, outReal);
        }
        tempBuffer = vec![0.0_f64; ((lookbackTotal + (endIdx - startIdx) + 1) * 1) as usize];
        retCode = self.trange_unguarded(startIdx - lookbackTotal + 1, endIdx, inHigh, inLow, inClose, &mut outBegIdx1, &mut outNbElement1, &mut tempBuffer[..]);
        if retCode != RetCode::Success {
            return retCode;
        }
        retCode = self.sma_unguarded((optInTimePeriod - 1) as usize, (optInTimePeriod - 1) as usize, &tempBuffer, optInTimePeriod, &mut outBegIdx1, &mut outNbElement1, std::slice::from_mut(&mut prevATR));
        if retCode != RetCode::Success {
            return retCode;
        }
        today = (optInTimePeriod) as usize;
        outIdx = (self.unstable_period[FuncUnstId::Atr as usize]) as usize;
        while outIdx != 0 {
            prevATR *= ((optInTimePeriod - 1) as f64);
            prevATR += tempBuffer[{ let _v = today; today += 1; _v }];
            prevATR /= ((optInTimePeriod) as f64);
            outIdx -= 1;
        }
        outIdx = 1;
        outReal[0] = prevATR;
        nbATR = endIdx - startIdx + 1;
        while { nbATR -= 1; nbATR } != 0 {
            prevATR *= ((optInTimePeriod - 1) as f64);
            prevATR += tempBuffer[{ let _v = today; today += 1; _v }];
            prevATR /= ((optInTimePeriod) as f64);
            outReal[outIdx] = prevATR;
            outIdx += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return retCode;
    }
    #[inline]
    pub fn atr_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut outIdx: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut nbATR: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut prevATR: f64 = 0.0_f64;
        let mut tempBuffer: Vec<f64> = Vec::new();
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outReal.len());
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = self.atr_lookback(optInTimePeriod);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        if optInTimePeriod <= 1 {
            return self.trange_unguarded(startIdx, endIdx, inHigh, inLow, inClose, outBegIdx, outNBElement, outReal);
        }
        tempBuffer = vec![0.0_f64; ((lookbackTotal + (endIdx - startIdx) + 1) * 1) as usize];
        retCode = self.trange_unguarded(startIdx - lookbackTotal + 1, endIdx, inHigh, inLow, inClose, &mut outBegIdx1, &mut outNbElement1, &mut tempBuffer[..]);
        if retCode != RetCode::Success {
            return retCode;
        }
        retCode = self.sma_unguarded((optInTimePeriod - 1) as usize, (optInTimePeriod - 1) as usize, &tempBuffer, optInTimePeriod, &mut outBegIdx1, &mut outNbElement1, std::slice::from_mut(&mut prevATR));
        if retCode != RetCode::Success {
            return retCode;
        }
        today = (optInTimePeriod) as usize;
        outIdx = (self.unstable_period[FuncUnstId::Atr as usize]) as usize;
        while outIdx != 0 {
            prevATR *= ((optInTimePeriod - 1) as f64);
            prevATR += *tempBuffer.as_ptr().add({ let _v = today; today += 1; _v });
            prevATR /= ((optInTimePeriod) as f64);
            outIdx -= 1;
        }
        outIdx = 1;
        *outReal.as_mut_ptr().add(0) = prevATR;
        nbATR = endIdx - startIdx + 1;
        while { nbATR -= 1; nbATR } != 0 {
            prevATR *= ((optInTimePeriod - 1) as f64);
            prevATR += *tempBuffer.as_ptr().add({ let _v = today; today += 1; _v });
            prevATR /= ((optInTimePeriod) as f64);
            *outReal.as_mut_ptr().add(outIdx) = prevATR;
            outIdx += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return retCode;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
