/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::avgdev`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    #[inline]
    pub fn avgdev_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Average Deviation
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn avgdev(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookback: usize = 0_usize;
        lookback = (optInTimePeriod - 1) as usize;
        if startIdx < lookback {
            startIdx = lookback;
        }
        today = startIdx;
        if today > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = today;
        outIdx = 0;
        while today <= endIdx {
            let mut todaySum: f64 = 0.0_f64;
            let mut todayDev: f64 = 0.0_f64;
            let mut i: usize = 0_usize;
            todaySum = 0.0;
            // for( i = 0; i < (optInTimePeriod) as usize; i += 1 )
            i = 0;
            while i < (optInTimePeriod) as usize {
                todaySum += inReal[today - i];
                i += 1;
            }
            todayDev = 0.0;
            // for( i = 0; i < (optInTimePeriod) as usize; i += 1 )
            i = 0;
            while i < (optInTimePeriod) as usize {
                todayDev += (inReal[today - i] - todaySum / ((optInTimePeriod) as f64)).abs();
                i += 1;
            }
            outReal[outIdx] = todayDev / ((optInTimePeriod) as f64);
            outIdx += 1;
            today += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn avgdev_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookback: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        lookback = (optInTimePeriod - 1) as usize;
        if startIdx < lookback {
            startIdx = lookback;
        }
        today = startIdx;
        if today > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = today;
        outIdx = 0;
        while today <= endIdx {
            let mut todaySum: f64 = 0.0_f64;
            let mut todayDev: f64 = 0.0_f64;
            let mut i: usize = 0_usize;
            todaySum = 0.0;
            // for( i = 0; i < (optInTimePeriod) as usize; i += 1 )
            i = 0;
            while i < (optInTimePeriod) as usize {
                todaySum += *inReal.as_ptr().add(today - i);
                i += 1;
            }
            todayDev = 0.0;
            // for( i = 0; i < (optInTimePeriod) as usize; i += 1 )
            i = 0;
            while i < (optInTimePeriod) as usize {
                todayDev += (*inReal.as_ptr().add(today - i) - todaySum / ((optInTimePeriod) as f64)).abs();
                i += 1;
            }
            *outReal.as_mut_ptr().add(outIdx) = todayDev / ((optInTimePeriod) as f64);
            outIdx += 1;
            today += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
