/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::beta`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 1..=100000)
    #[inline]
    pub fn beta_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod) as usize;
    }
    /// Beta
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal0` - Input price series
    /// * `inReal1` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn beta(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[f64],
        inReal1: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut S_xx: f64 = 0.0_f64;
        let mut S_xy: f64 = 0.0_f64;
        let mut S_x: f64 = 0.0_f64;
        let mut S_y: f64 = 0.0_f64;
        let mut last_price_x: f64 = 0.0_f64;
        let mut last_price_y: f64 = 0.0_f64;
        let mut trailing_last_price_x: f64 = 0.0_f64;
        let mut trailing_last_price_y: f64 = 0.0_f64;
        let mut tmp_real: f64 = 0.0_f64;
        let mut x: f64 = 0.0_f64;
        let mut y: f64 = 0.0_f64;
        let mut n: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut nbInitialElementNeeded: usize = 0_usize;
        S_xx = 0.0;
        S_xy = 0.0;
        S_x = 0.0;
        S_y = 0.0;
        last_price_x = 0.0;
        last_price_y = 0.0;
        trailing_last_price_x = 0.0;
        trailing_last_price_y = 0.0;
        tmp_real = 0.0;
        nbInitialElementNeeded = (optInTimePeriod) as usize;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        trailingIdx = startIdx - nbInitialElementNeeded;
        trailing_last_price_x = inReal0[trailingIdx];
        last_price_x = trailing_last_price_x;
        trailing_last_price_y = inReal1[trailingIdx];
        last_price_y = trailing_last_price_y;
        i = { trailingIdx += 1; trailingIdx };
        while i < startIdx {
            tmp_real = inReal0[i];
            if !((last_price_x).abs() < 1e-14) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = 0.0;
            }
            last_price_x = tmp_real;
            tmp_real = inReal1[{ let _v = i; i += 1; _v }];
            if !((last_price_y).abs() < 1e-14) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = 0.0;
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
        }
        outIdx = 0;
        n = (optInTimePeriod) as f64;
        loop {
            tmp_real = inReal0[i];
            if !((last_price_x).abs() < 1e-14) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = 0.0;
            }
            last_price_x = tmp_real;
            tmp_real = inReal1[{ let _v = i; i += 1; _v }];
            if !((last_price_y).abs() < 1e-14) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = 0.0;
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
            tmp_real = inReal0[trailingIdx];
            if !((trailing_last_price_x).abs() < 1e-14) {
                x = (tmp_real - trailing_last_price_x) / trailing_last_price_x;
            } else {
                x = 0.0;
            }
            trailing_last_price_x = tmp_real;
            tmp_real = inReal1[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            if !((trailing_last_price_y).abs() < 1e-14) {
                y = (tmp_real - trailing_last_price_y) / trailing_last_price_y;
            } else {
                y = 0.0;
            }
            trailing_last_price_y = tmp_real;
            tmp_real = n * S_xx - S_x * S_x;
            if !((tmp_real).abs() < 1e-14) {
                outReal[outIdx] = (n * S_xy - S_x * S_y) / tmp_real;
                outIdx += 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx += 1;
            }
            S_xx -= x * x;
            S_xy -= x * y;
            S_x -= x;
            S_y -= y;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn beta_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal0: &[f64],
        inReal1: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut S_xx: f64 = 0.0_f64;
        let mut S_xy: f64 = 0.0_f64;
        let mut S_x: f64 = 0.0_f64;
        let mut S_y: f64 = 0.0_f64;
        let mut last_price_x: f64 = 0.0_f64;
        let mut last_price_y: f64 = 0.0_f64;
        let mut trailing_last_price_x: f64 = 0.0_f64;
        let mut trailing_last_price_y: f64 = 0.0_f64;
        let mut tmp_real: f64 = 0.0_f64;
        let mut x: f64 = 0.0_f64;
        let mut y: f64 = 0.0_f64;
        let mut n: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut nbInitialElementNeeded: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal0.len());
        assert!(endIdx < inReal1.len());
        assert!(endIdx - startIdx < outReal.len());
        S_xx = 0.0;
        S_xy = 0.0;
        S_x = 0.0;
        S_y = 0.0;
        last_price_x = 0.0;
        last_price_y = 0.0;
        trailing_last_price_x = 0.0;
        trailing_last_price_y = 0.0;
        tmp_real = 0.0;
        nbInitialElementNeeded = (optInTimePeriod) as usize;
        if startIdx < nbInitialElementNeeded {
            startIdx = nbInitialElementNeeded;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        trailingIdx = startIdx - nbInitialElementNeeded;
        trailing_last_price_x = *inReal0.as_ptr().add(trailingIdx);
        last_price_x = trailing_last_price_x;
        trailing_last_price_y = *inReal1.as_ptr().add(trailingIdx);
        last_price_y = trailing_last_price_y;
        i = { trailingIdx += 1; trailingIdx };
        while i < startIdx {
            tmp_real = *inReal0.as_ptr().add(i);
            if !((last_price_x).abs() < 1e-14) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = 0.0;
            }
            last_price_x = tmp_real;
            tmp_real = *inReal1.as_ptr().add({ let _v = i; i += 1; _v });
            if !((last_price_y).abs() < 1e-14) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = 0.0;
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
        }
        outIdx = 0;
        n = (optInTimePeriod) as f64;
        loop {
            tmp_real = *inReal0.as_ptr().add(i);
            if !((last_price_x).abs() < 1e-14) {
                x = (tmp_real - last_price_x) / last_price_x;
            } else {
                x = 0.0;
            }
            last_price_x = tmp_real;
            tmp_real = *inReal1.as_ptr().add({ let _v = i; i += 1; _v });
            if !((last_price_y).abs() < 1e-14) {
                y = (tmp_real - last_price_y) / last_price_y;
            } else {
                y = 0.0;
            }
            last_price_y = tmp_real;
            S_xx += x * x;
            S_xy += x * y;
            S_x += x;
            S_y += y;
            tmp_real = *inReal0.as_ptr().add(trailingIdx);
            if !((trailing_last_price_x).abs() < 1e-14) {
                x = (tmp_real - trailing_last_price_x) / trailing_last_price_x;
            } else {
                x = 0.0;
            }
            trailing_last_price_x = tmp_real;
            tmp_real = *inReal1.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            if !((trailing_last_price_y).abs() < 1e-14) {
                y = (tmp_real - trailing_last_price_y) / trailing_last_price_y;
            } else {
                y = 0.0;
            }
            trailing_last_price_y = tmp_real;
            tmp_real = n * S_xx - S_x * S_x;
            if !((tmp_real).abs() < 1e-14) {
                *outReal.as_mut_ptr().add(outIdx) = (n * S_xy - S_x * S_y) / tmp_real;
                outIdx += 1;
            } else {
                *outReal.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            }
            S_xx -= x * x;
            S_xy -= x * y;
            S_x -= x;
            S_y -= y;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
