/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cci`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    #[inline]
    pub fn cci_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Commodity Channel Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn cci(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut tempReal: f64 = 0.0_f64;
        let mut tempReal2: f64 = 0.0_f64;
        let mut theAverage: f64 = 0.0_f64;
        let mut lastValue: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut circBuffer: [f64; 30 as usize] = [0.0_f64; 30 as usize];
        let mut circBuffer_Idx: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            circBuffer[_si.._si + _n].fill(0.0_f64);
        };
        circBuffer_Idx = 0;
        i = startIdx - lookbackTotal;
        if optInTimePeriod > 1 {
            while i < startIdx {
                circBuffer[circBuffer_Idx] = (inHigh[i] + inLow[i] + inClose[i]) / 3_f64;
                i += 1;
                circBuffer_Idx += 1;
                if circBuffer_Idx >= (optInTimePeriod) as usize {
                    circBuffer_Idx = 0;
                }
            }
        }
        outIdx = 0;
        loop {
            lastValue = (inHigh[i] + inLow[i] + inClose[i]) / 3_f64;
            circBuffer[circBuffer_Idx] = lastValue;
            theAverage = 0.0;
            // for( j = 0; j < (optInTimePeriod) as usize; j += 1 )
            j = 0;
            while j < (optInTimePeriod) as usize {
                theAverage += circBuffer[j];
                j += 1;
            }
            theAverage /= ((optInTimePeriod) as f64);
            tempReal2 = 0.0;
            // for( j = 0; j < (optInTimePeriod) as usize; j += 1 )
            j = 0;
            while j < (optInTimePeriod) as usize {
                tempReal2 += (circBuffer[j] - theAverage).abs();
                j += 1;
            }
            tempReal = lastValue - theAverage;
            if tempReal != 0.0 && tempReal2 != 0.0 {
                outReal[outIdx] = tempReal / (0.015 * (tempReal2 / ((optInTimePeriod) as f64)));
                outIdx += 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx += 1;
            }
            circBuffer_Idx += 1;
            if circBuffer_Idx >= (optInTimePeriod) as usize {
                circBuffer_Idx = 0;
            }
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cci_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempReal: f64 = 0.0_f64;
        let mut tempReal2: f64 = 0.0_f64;
        let mut theAverage: f64 = 0.0_f64;
        let mut lastValue: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut circBuffer: [f64; 30 as usize] = [0.0_f64; 30 as usize];
        let mut circBuffer_Idx: usize = 0_usize;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outReal.len());
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            circBuffer[_si.._si + _n].fill(0.0_f64);
        };
        circBuffer_Idx = 0;
        i = startIdx - lookbackTotal;
        if optInTimePeriod > 1 {
            while i < startIdx {
                *circBuffer.as_mut_ptr().add(circBuffer_Idx) = (*inHigh.as_ptr().add(i) + *inLow.as_ptr().add(i) + *inClose.as_ptr().add(i)) / 3_f64;
                i += 1;
                circBuffer_Idx += 1;
                if circBuffer_Idx >= (optInTimePeriod) as usize {
                    circBuffer_Idx = 0;
                }
            }
        }
        outIdx = 0;
        loop {
            lastValue = (*inHigh.as_ptr().add(i) + *inLow.as_ptr().add(i) + *inClose.as_ptr().add(i)) / 3_f64;
            *circBuffer.as_mut_ptr().add(circBuffer_Idx) = lastValue;
            theAverage = 0.0;
            // for( j = 0; j < (optInTimePeriod) as usize; j += 1 )
            j = 0;
            while j < (optInTimePeriod) as usize {
                theAverage += *circBuffer.as_ptr().add(j);
                j += 1;
            }
            theAverage /= ((optInTimePeriod) as f64);
            tempReal2 = 0.0;
            // for( j = 0; j < (optInTimePeriod) as usize; j += 1 )
            j = 0;
            while j < (optInTimePeriod) as usize {
                tempReal2 += (*circBuffer.as_ptr().add(j) - theAverage).abs();
                j += 1;
            }
            tempReal = lastValue - theAverage;
            if tempReal != 0.0 && tempReal2 != 0.0 {
                *outReal.as_mut_ptr().add(outIdx) = tempReal / (0.015 * (tempReal2 / ((optInTimePeriod) as f64)));
                outIdx += 1;
            } else {
                *outReal.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            }
            circBuffer_Idx += 1;
            if circBuffer_Idx >= (optInTimePeriod) as usize {
                circBuffer_Idx = 0;
            }
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
