/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdl2crows`].
    ///
    /// # Arguments
    ///
    pub fn cdl2crows_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        return (BodyLong_avgPeriod + 2) as usize;
    }
    /// Two Crows
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdl2crows(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        lookbackTotal = self.cdl2crows_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyLongPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - 2 - (BodyLong_avgPeriod) as usize;
        i = BodyLongTrailingIdx;
        while i < startIdx - 2 {
            let mut _candlerange_0: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 }) == 1 && (inClose[i - 2] - inOpen[i - 2]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && ((if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if (inOpen[i - 1]).min(inClose[i - 1]) > (inOpen[i - 2]).max(inClose[i - 2]) { 1 } else { 0 }) != 0) && ((if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && inOpen[i] < inOpen[i - 1] && inOpen[i] > inClose[i - 1] && inClose[i] > inOpen[i - 2] && inClose[i] < inClose[i - 2] {
                outInteger[outIdx] = (0 - 100) as i32;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            let mut _candlerange_1: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            let mut _candlerange_2: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx];
                }
                2 => {
                    _candlerange_2 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx] - (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_1 - _candlerange_2;
            i += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cdl2crows_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        unsafe {
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outInteger.len());
        lookbackTotal = self.cdl2crows_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyLongPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - 2 - (BodyLong_avgPeriod) as usize;
        i = BodyLongTrailingIdx;
        while i < startIdx - 2 {
            let mut _candlerange_0: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_0 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if *inClose.as_ptr().add(i - 2) >= *inOpen.as_ptr().add(i - 2) { 1 } else { 0 - 1 }) == 1 && (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && ((if *inClose.as_ptr().add(i - 1) >= *inOpen.as_ptr().add(i - 1) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && ((if (*inOpen.as_ptr().add(i - 1)).min(*inClose.as_ptr().add(i - 1)) > (*inOpen.as_ptr().add(i - 2)).max(*inClose.as_ptr().add(i - 2)) { 1 } else { 0 }) != 0) && ((if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && *inOpen.as_ptr().add(i) < *inOpen.as_ptr().add(i - 1) && *inOpen.as_ptr().add(i) > *inClose.as_ptr().add(i - 1) && *inClose.as_ptr().add(i) > *inOpen.as_ptr().add(i - 2) && *inClose.as_ptr().add(i) < *inClose.as_ptr().add(i - 2) {
                *outInteger.as_mut_ptr().add(outIdx) = (0 - 100) as i32;
                outIdx += 1;
            } else {
                *outInteger.as_mut_ptr().add(outIdx) = 0;
                outIdx += 1;
            }
            let mut _candlerange_1: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            let mut _candlerange_2: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_2 = (*inClose.as_ptr().add(BodyLongTrailingIdx) - *inOpen.as_ptr().add(BodyLongTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.as_ptr().add(BodyLongTrailingIdx) - *inLow.as_ptr().add(BodyLongTrailingIdx);
                }
                2 => {
                    _candlerange_2 = *inHigh.as_ptr().add(BodyLongTrailingIdx) - *inLow.as_ptr().add(BodyLongTrailingIdx) - (*inClose.as_ptr().add(BodyLongTrailingIdx) - *inOpen.as_ptr().add(BodyLongTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_1 - _candlerange_2;
            i += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
