/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdladvanceblock`].
    ///
    /// # Arguments
    ///
    pub fn cdladvanceblock_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Far_rangeType: i32 = self.candle_settings.far.range_type;
        #[allow(non_snake_case)]
        let Far_avgPeriod: i32 = self.candle_settings.far.avg_period;
        #[allow(non_snake_case)]
        let Far_factor: f64 = self.candle_settings.far.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        #[allow(non_snake_case)]
        let ShadowShort_rangeType: i32 = self.candle_settings.shadow_short.range_type;
        #[allow(non_snake_case)]
        let ShadowShort_avgPeriod: i32 = self.candle_settings.shadow_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowShort_factor: f64 = self.candle_settings.shadow_short.factor;
        return ((((ShadowLong_avgPeriod).max(ShadowShort_avgPeriod)).max((Far_avgPeriod).max(Near_avgPeriod))).max(BodyLong_avgPeriod) + 2) as usize;
    }
    /// Advance Block
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdladvanceblock(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut ShadowShortPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut ShadowLongPeriodTotal: [f64; 2 as usize] = [0.0_f64; 2 as usize];
        let mut NearPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut FarPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut ShadowShortTrailingIdx: usize = 0_usize;
        let mut ShadowLongTrailingIdx: usize = 0_usize;
        let mut NearTrailingIdx: usize = 0_usize;
        let mut FarTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Far_rangeType: i32 = self.candle_settings.far.range_type;
        #[allow(non_snake_case)]
        let Far_avgPeriod: i32 = self.candle_settings.far.avg_period;
        #[allow(non_snake_case)]
        let Far_factor: f64 = self.candle_settings.far.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        #[allow(non_snake_case)]
        let ShadowShort_rangeType: i32 = self.candle_settings.shadow_short.range_type;
        #[allow(non_snake_case)]
        let ShadowShort_avgPeriod: i32 = self.candle_settings.shadow_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowShort_factor: f64 = self.candle_settings.shadow_short.factor;
        lookbackTotal = self.cdladvanceblock_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        ShadowShortPeriodTotal[2] = 0.0;
        ShadowShortPeriodTotal[1] = 0.0;
        ShadowShortPeriodTotal[0] = 0.0;
        ShadowShortTrailingIdx = startIdx - (ShadowShort_avgPeriod) as usize;
        ShadowLongPeriodTotal[1] = 0.0;
        ShadowLongPeriodTotal[0] = 0.0;
        ShadowLongTrailingIdx = startIdx - (ShadowLong_avgPeriod) as usize;
        NearPeriodTotal[2] = 0.0;
        NearPeriodTotal[1] = 0.0;
        NearPeriodTotal[0] = 0.0;
        NearTrailingIdx = startIdx - (Near_avgPeriod) as usize;
        FarPeriodTotal[2] = 0.0;
        FarPeriodTotal[1] = 0.0;
        FarPeriodTotal[0] = 0.0;
        FarTrailingIdx = startIdx - (Far_avgPeriod) as usize;
        BodyLongPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = ShadowShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            ShadowShortPeriodTotal[2] = ShadowShortPeriodTotal[2] + _candlerange_0;
            let mut _candlerange_1: f64;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowShortPeriodTotal[1] = ShadowShortPeriodTotal[1] + _candlerange_1;
            let mut _candlerange_2: f64;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            ShadowShortPeriodTotal[0] = ShadowShortPeriodTotal[0] + _candlerange_2;
            i += 1;
        }
        i = ShadowLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_3 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_3 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            ShadowLongPeriodTotal[1] = ShadowLongPeriodTotal[1] + _candlerange_3;
            let mut _candlerange_4: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_4 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            ShadowLongPeriodTotal[0] = ShadowLongPeriodTotal[0] + _candlerange_4;
            i += 1;
        }
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_5: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_5 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_5 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            NearPeriodTotal[2] = NearPeriodTotal[2] + _candlerange_5;
            let mut _candlerange_6: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_6 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_6 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_6 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            NearPeriodTotal[1] = NearPeriodTotal[1] + _candlerange_6;
            i += 1;
        }
        i = FarTrailingIdx;
        while i < startIdx {
            let mut _candlerange_7: f64;
            match Far_rangeType {
                0 => {
                    _candlerange_7 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_7 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_7 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            FarPeriodTotal[2] = FarPeriodTotal[2] + _candlerange_7;
            let mut _candlerange_8: f64;
            match Far_rangeType {
                0 => {
                    _candlerange_8 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_8 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_8 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            FarPeriodTotal[1] = FarPeriodTotal[1] + _candlerange_8;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_9: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_9 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_9 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_9 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_9 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_9;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 }) == 1 && (if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 }) == 1 && (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) == 1 && inClose[i] > inClose[i - 1] && inClose[i - 1] > inClose[i - 2] && inOpen[i - 1] > inOpen[i - 2] && inOpen[i - 1] <= inClose[i - 2] + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal[2]) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) && inOpen[i] > inOpen[i - 1] && inOpen[i] <= inClose[i - 1] + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal[1]) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i - 2] - inOpen[i - 2]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (inHigh[i - 2] - (if inClose[i - 2] >= inOpen[i - 2] { inClose[i - 2] } else { inOpen[i - 2] })) < ((ShadowShort_factor) * (if (ShadowShort_avgPeriod) != 0 { (ShadowShortPeriodTotal[2]) / (ShadowShort_avgPeriod as f64) } else { match ShadowShort_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (ShadowShort_rangeType) == 2 { 2.0 } else { 1.0 })) && ((inClose[i - 1] - inOpen[i - 1]).abs() < (inClose[i - 2] - inOpen[i - 2]).abs() - ((Far_factor) * (if (Far_avgPeriod) != 0 { (FarPeriodTotal[2]) / (Far_avgPeriod as f64) } else { match Far_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (Far_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i] - inOpen[i]).abs() < (inClose[i - 1] - inOpen[i - 1]).abs() + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal[1]) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) || (inClose[i] - inOpen[i]).abs() < (inClose[i - 1] - inOpen[i - 1]).abs() - ((Far_factor) * (if (Far_avgPeriod) != 0 { (FarPeriodTotal[1]) / (Far_avgPeriod as f64) } else { match Far_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (Far_rangeType) == 2 { 2.0 } else { 1.0 })) || (inClose[i] - inOpen[i]).abs() < (inClose[i - 1] - inOpen[i - 1]).abs() && (inClose[i - 1] - inOpen[i - 1]).abs() < (inClose[i - 2] - inOpen[i - 2]).abs() && ((inHigh[i] - (if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] })) > ((ShadowShort_factor) * (if (ShadowShort_avgPeriod) != 0 { (ShadowShortPeriodTotal[0]) / (ShadowShort_avgPeriod as f64) } else { match ShadowShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (ShadowShort_rangeType) == 2 { 2.0 } else { 1.0 })) || (inHigh[i - 1] - (if inClose[i - 1] >= inOpen[i - 1] { inClose[i - 1] } else { inOpen[i - 1] })) > ((ShadowShort_factor) * (if (ShadowShort_avgPeriod) != 0 { (ShadowShortPeriodTotal[1]) / (ShadowShort_avgPeriod as f64) } else { match ShadowShort_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (ShadowShort_rangeType) == 2 { 2.0 } else { 1.0 }))) || (inClose[i] - inOpen[i]).abs() < (inClose[i - 1] - inOpen[i - 1]).abs() && (inHigh[i] - (if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] })) > ((ShadowLong_factor) * (if (ShadowLong_avgPeriod) != 0 { (ShadowLongPeriodTotal[0]) / (ShadowLong_avgPeriod as f64) } else { match ShadowLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (ShadowLong_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                outInteger[outIdx] = (0 - 100) as i32;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            // for( totIdx = 2; totIdx >= 0; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_10: f64;
                match ShadowShort_rangeType {
                    0 => {
                        _candlerange_10 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_10 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_10 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_10 = 0.0;
                    }
                }
                let mut _candlerange_11: f64;
                match ShadowShort_rangeType {
                    0 => {
                        _candlerange_11 = (inClose[ShadowShortTrailingIdx - totIdx] - inOpen[ShadowShortTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_11 = inHigh[ShadowShortTrailingIdx - totIdx] - inLow[ShadowShortTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_11 = inHigh[ShadowShortTrailingIdx - totIdx] - inLow[ShadowShortTrailingIdx - totIdx] - (inClose[ShadowShortTrailingIdx - totIdx] - inOpen[ShadowShortTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_11 = 0.0;
                    }
                }
                ShadowShortPeriodTotal[totIdx] = ShadowShortPeriodTotal[totIdx] + (_candlerange_10 - _candlerange_11);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            // for( totIdx = 1; totIdx >= 0; totIdx -= 1 )
            totIdx = 1;
            loop {
                let mut _candlerange_12: f64;
                match ShadowLong_rangeType {
                    0 => {
                        _candlerange_12 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_12 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_12 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_12 = 0.0;
                    }
                }
                let mut _candlerange_13: f64;
                match ShadowLong_rangeType {
                    0 => {
                        _candlerange_13 = (inClose[ShadowLongTrailingIdx - totIdx] - inOpen[ShadowLongTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_13 = inHigh[ShadowLongTrailingIdx - totIdx] - inLow[ShadowLongTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_13 = inHigh[ShadowLongTrailingIdx - totIdx] - inLow[ShadowLongTrailingIdx - totIdx] - (inClose[ShadowLongTrailingIdx - totIdx] - inOpen[ShadowLongTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_13 = 0.0;
                    }
                }
                ShadowLongPeriodTotal[totIdx] = ShadowLongPeriodTotal[totIdx] + (_candlerange_12 - _candlerange_13);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            // for( totIdx = 2; totIdx >= 1; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_14: f64;
                match Far_rangeType {
                    0 => {
                        _candlerange_14 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_14 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_14 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_14 = 0.0;
                    }
                }
                let mut _candlerange_15: f64;
                match Far_rangeType {
                    0 => {
                        _candlerange_15 = (inClose[FarTrailingIdx - totIdx] - inOpen[FarTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_15 = inHigh[FarTrailingIdx - totIdx] - inLow[FarTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_15 = inHigh[FarTrailingIdx - totIdx] - inLow[FarTrailingIdx - totIdx] - (inClose[FarTrailingIdx - totIdx] - inOpen[FarTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_15 = 0.0;
                    }
                }
                FarPeriodTotal[totIdx] = FarPeriodTotal[totIdx] + (_candlerange_14 - _candlerange_15);
                let mut _candlerange_16: f64;
                match Near_rangeType {
                    0 => {
                        _candlerange_16 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_16 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_16 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_16 = 0.0;
                    }
                }
                let mut _candlerange_17: f64;
                match Near_rangeType {
                    0 => {
                        _candlerange_17 = (inClose[NearTrailingIdx - totIdx] - inOpen[NearTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_17 = inHigh[NearTrailingIdx - totIdx] - inLow[NearTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_17 = inHigh[NearTrailingIdx - totIdx] - inLow[NearTrailingIdx - totIdx] - (inClose[NearTrailingIdx - totIdx] - inOpen[NearTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_17 = 0.0;
                    }
                }
                NearPeriodTotal[totIdx] = NearPeriodTotal[totIdx] + (_candlerange_16 - _candlerange_17);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            let mut _candlerange_18: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_18 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_18 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_18 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_18 = 0.0;
                }
            }
            let mut _candlerange_19: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_19 = (inClose[BodyLongTrailingIdx - 2] - inOpen[BodyLongTrailingIdx - 2]).abs();
                }
                1 => {
                    _candlerange_19 = inHigh[BodyLongTrailingIdx - 2] - inLow[BodyLongTrailingIdx - 2];
                }
                2 => {
                    _candlerange_19 = inHigh[BodyLongTrailingIdx - 2] - inLow[BodyLongTrailingIdx - 2] - (inClose[BodyLongTrailingIdx - 2] - inOpen[BodyLongTrailingIdx - 2]).abs();
                }
                _ => {
                    _candlerange_19 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_18 - _candlerange_19;
            i += 1;
            ShadowShortTrailingIdx += 1;
            ShadowLongTrailingIdx += 1;
            NearTrailingIdx += 1;
            FarTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cdladvanceblock_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowShortPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut ShadowLongPeriodTotal: [f64; 2 as usize] = [0.0_f64; 2 as usize];
        let mut NearPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut FarPeriodTotal: [f64; 3 as usize] = [0.0_f64; 3 as usize];
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut ShadowShortTrailingIdx: usize = 0_usize;
        let mut ShadowLongTrailingIdx: usize = 0_usize;
        let mut NearTrailingIdx: usize = 0_usize;
        let mut FarTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Far_rangeType: i32 = self.candle_settings.far.range_type;
        #[allow(non_snake_case)]
        let Far_avgPeriod: i32 = self.candle_settings.far.avg_period;
        #[allow(non_snake_case)]
        let Far_factor: f64 = self.candle_settings.far.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        #[allow(non_snake_case)]
        let ShadowShort_rangeType: i32 = self.candle_settings.shadow_short.range_type;
        #[allow(non_snake_case)]
        let ShadowShort_avgPeriod: i32 = self.candle_settings.shadow_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowShort_factor: f64 = self.candle_settings.shadow_short.factor;
        unsafe {
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outInteger.len());
        lookbackTotal = self.cdladvanceblock_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        *ShadowShortPeriodTotal.as_mut_ptr().add(2) = 0.0;
        *ShadowShortPeriodTotal.as_mut_ptr().add(1) = 0.0;
        *ShadowShortPeriodTotal.as_mut_ptr().add(0) = 0.0;
        ShadowShortTrailingIdx = startIdx - (ShadowShort_avgPeriod) as usize;
        *ShadowLongPeriodTotal.as_mut_ptr().add(1) = 0.0;
        *ShadowLongPeriodTotal.as_mut_ptr().add(0) = 0.0;
        ShadowLongTrailingIdx = startIdx - (ShadowLong_avgPeriod) as usize;
        *NearPeriodTotal.as_mut_ptr().add(2) = 0.0;
        *NearPeriodTotal.as_mut_ptr().add(1) = 0.0;
        *NearPeriodTotal.as_mut_ptr().add(0) = 0.0;
        NearTrailingIdx = startIdx - (Near_avgPeriod) as usize;
        *FarPeriodTotal.as_mut_ptr().add(2) = 0.0;
        *FarPeriodTotal.as_mut_ptr().add(1) = 0.0;
        *FarPeriodTotal.as_mut_ptr().add(0) = 0.0;
        FarTrailingIdx = startIdx - (Far_avgPeriod) as usize;
        BodyLongPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = ShadowShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_0 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            *ShadowShortPeriodTotal.as_mut_ptr().add(2) = *ShadowShortPeriodTotal.as_ptr().add(2) + _candlerange_0;
            let mut _candlerange_1: f64;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_1 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            *ShadowShortPeriodTotal.as_mut_ptr().add(1) = *ShadowShortPeriodTotal.as_ptr().add(1) + _candlerange_1;
            let mut _candlerange_2: f64;
            match ShadowShort_rangeType {
                0 => {
                    _candlerange_2 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            *ShadowShortPeriodTotal.as_mut_ptr().add(0) = *ShadowShortPeriodTotal.as_ptr().add(0) + _candlerange_2;
            i += 1;
        }
        i = ShadowLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_3 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            *ShadowLongPeriodTotal.as_mut_ptr().add(1) = *ShadowLongPeriodTotal.as_ptr().add(1) + _candlerange_3;
            let mut _candlerange_4: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_4 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_4 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            *ShadowLongPeriodTotal.as_mut_ptr().add(0) = *ShadowLongPeriodTotal.as_ptr().add(0) + _candlerange_4;
            i += 1;
        }
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_5: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_5 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            *NearPeriodTotal.as_mut_ptr().add(2) = *NearPeriodTotal.as_ptr().add(2) + _candlerange_5;
            let mut _candlerange_6: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_6 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_6 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_6 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            *NearPeriodTotal.as_mut_ptr().add(1) = *NearPeriodTotal.as_ptr().add(1) + _candlerange_6;
            i += 1;
        }
        i = FarTrailingIdx;
        while i < startIdx {
            let mut _candlerange_7: f64;
            match Far_rangeType {
                0 => {
                    _candlerange_7 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_7 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_7 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            *FarPeriodTotal.as_mut_ptr().add(2) = *FarPeriodTotal.as_ptr().add(2) + _candlerange_7;
            let mut _candlerange_8: f64;
            match Far_rangeType {
                0 => {
                    _candlerange_8 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_8 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_8 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            *FarPeriodTotal.as_mut_ptr().add(1) = *FarPeriodTotal.as_ptr().add(1) + _candlerange_8;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_9: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_9 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_9 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_9 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_9 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_9;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if *inClose.as_ptr().add(i - 2) >= *inOpen.as_ptr().add(i - 2) { 1 } else { 0 - 1 }) == 1 && (if *inClose.as_ptr().add(i - 1) >= *inOpen.as_ptr().add(i - 1) { 1 } else { 0 - 1 }) == 1 && (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 }) == 1 && *inClose.as_ptr().add(i) > *inClose.as_ptr().add(i - 1) && *inClose.as_ptr().add(i - 1) > *inClose.as_ptr().add(i - 2) && *inOpen.as_ptr().add(i - 1) > *inOpen.as_ptr().add(i - 2) && *inOpen.as_ptr().add(i - 1) <= *inClose.as_ptr().add(i - 2) + ((Near_factor) * (if (Near_avgPeriod) != 0 { (*NearPeriodTotal.as_ptr().add(2)) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) && *inOpen.as_ptr().add(i) > *inOpen.as_ptr().add(i - 1) && *inOpen.as_ptr().add(i) <= *inClose.as_ptr().add(i - 1) + ((Near_factor) * (if (Near_avgPeriod) != 0 { (*NearPeriodTotal.as_ptr().add(1)) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inHigh.as_ptr().add(i - 2) - (if *inClose.as_ptr().add(i - 2) >= *inOpen.as_ptr().add(i - 2) { *inClose.as_ptr().add(i - 2) } else { *inOpen.as_ptr().add(i - 2) })) < ((ShadowShort_factor) * (if (ShadowShort_avgPeriod) != 0 { (*ShadowShortPeriodTotal.as_ptr().add(2)) / (ShadowShort_avgPeriod as f64) } else { match ShadowShort_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (ShadowShort_rangeType) == 2 { 2.0 } else { 1.0 })) && ((*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() < (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs() - ((Far_factor) * (if (Far_avgPeriod) != 0 { (*FarPeriodTotal.as_ptr().add(2)) / (Far_avgPeriod as f64) } else { match Far_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (Far_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() < (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() + ((Near_factor) * (if (Near_avgPeriod) != 0 { (*NearPeriodTotal.as_ptr().add(1)) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) || (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() < (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() - ((Far_factor) * (if (Far_avgPeriod) != 0 { (*FarPeriodTotal.as_ptr().add(1)) / (Far_avgPeriod as f64) } else { match Far_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (Far_rangeType) == 2 { 2.0 } else { 1.0 })) || (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() < (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() && (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() < (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs() && ((*inHigh.as_ptr().add(i) - (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { *inClose.as_ptr().add(i) } else { *inOpen.as_ptr().add(i) })) > ((ShadowShort_factor) * (if (ShadowShort_avgPeriod) != 0 { (*ShadowShortPeriodTotal.as_ptr().add(0)) / (ShadowShort_avgPeriod as f64) } else { match ShadowShort_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (ShadowShort_rangeType) == 2 { 2.0 } else { 1.0 })) || (*inHigh.as_ptr().add(i - 1) - (if *inClose.as_ptr().add(i - 1) >= *inOpen.as_ptr().add(i - 1) { *inClose.as_ptr().add(i - 1) } else { *inOpen.as_ptr().add(i - 1) })) > ((ShadowShort_factor) * (if (ShadowShort_avgPeriod) != 0 { (*ShadowShortPeriodTotal.as_ptr().add(1)) / (ShadowShort_avgPeriod as f64) } else { match ShadowShort_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (ShadowShort_rangeType) == 2 { 2.0 } else { 1.0 }))) || (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() < (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() && (*inHigh.as_ptr().add(i) - (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { *inClose.as_ptr().add(i) } else { *inOpen.as_ptr().add(i) })) > ((ShadowLong_factor) * (if (ShadowLong_avgPeriod) != 0 { (*ShadowLongPeriodTotal.as_ptr().add(0)) / (ShadowLong_avgPeriod as f64) } else { match ShadowLong_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (ShadowLong_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                *outInteger.as_mut_ptr().add(outIdx) = (0 - 100) as i32;
                outIdx += 1;
            } else {
                *outInteger.as_mut_ptr().add(outIdx) = 0;
                outIdx += 1;
            }
            // for( totIdx = 2; totIdx >= 0; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_10: f64;
                match ShadowShort_rangeType {
                    0 => {
                        _candlerange_10 = (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_10 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx);
                    }
                    2 => {
                        _candlerange_10 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx) - (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_10 = 0.0;
                    }
                }
                let mut _candlerange_11: f64;
                match ShadowShort_rangeType {
                    0 => {
                        _candlerange_11 = (*inClose.as_ptr().add(ShadowShortTrailingIdx - totIdx) - *inOpen.as_ptr().add(ShadowShortTrailingIdx - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_11 = *inHigh.as_ptr().add(ShadowShortTrailingIdx - totIdx) - *inLow.as_ptr().add(ShadowShortTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_11 = *inHigh.as_ptr().add(ShadowShortTrailingIdx - totIdx) - *inLow.as_ptr().add(ShadowShortTrailingIdx - totIdx) - (*inClose.as_ptr().add(ShadowShortTrailingIdx - totIdx) - *inOpen.as_ptr().add(ShadowShortTrailingIdx - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_11 = 0.0;
                    }
                }
                *ShadowShortPeriodTotal.as_mut_ptr().add(totIdx) = *ShadowShortPeriodTotal.as_ptr().add(totIdx) + (_candlerange_10 - _candlerange_11);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            // for( totIdx = 1; totIdx >= 0; totIdx -= 1 )
            totIdx = 1;
            loop {
                let mut _candlerange_12: f64;
                match ShadowLong_rangeType {
                    0 => {
                        _candlerange_12 = (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_12 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx);
                    }
                    2 => {
                        _candlerange_12 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx) - (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_12 = 0.0;
                    }
                }
                let mut _candlerange_13: f64;
                match ShadowLong_rangeType {
                    0 => {
                        _candlerange_13 = (*inClose.as_ptr().add(ShadowLongTrailingIdx - totIdx) - *inOpen.as_ptr().add(ShadowLongTrailingIdx - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_13 = *inHigh.as_ptr().add(ShadowLongTrailingIdx - totIdx) - *inLow.as_ptr().add(ShadowLongTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_13 = *inHigh.as_ptr().add(ShadowLongTrailingIdx - totIdx) - *inLow.as_ptr().add(ShadowLongTrailingIdx - totIdx) - (*inClose.as_ptr().add(ShadowLongTrailingIdx - totIdx) - *inOpen.as_ptr().add(ShadowLongTrailingIdx - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_13 = 0.0;
                    }
                }
                *ShadowLongPeriodTotal.as_mut_ptr().add(totIdx) = *ShadowLongPeriodTotal.as_ptr().add(totIdx) + (_candlerange_12 - _candlerange_13);
                if totIdx == 0 { break; }
                totIdx -= 1;
            }
            // for( totIdx = 2; totIdx >= 1; totIdx -= 1 )
            totIdx = 2;
            loop {
                let mut _candlerange_14: f64;
                match Far_rangeType {
                    0 => {
                        _candlerange_14 = (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_14 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx);
                    }
                    2 => {
                        _candlerange_14 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx) - (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_14 = 0.0;
                    }
                }
                let mut _candlerange_15: f64;
                match Far_rangeType {
                    0 => {
                        _candlerange_15 = (*inClose.as_ptr().add(FarTrailingIdx - totIdx) - *inOpen.as_ptr().add(FarTrailingIdx - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_15 = *inHigh.as_ptr().add(FarTrailingIdx - totIdx) - *inLow.as_ptr().add(FarTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_15 = *inHigh.as_ptr().add(FarTrailingIdx - totIdx) - *inLow.as_ptr().add(FarTrailingIdx - totIdx) - (*inClose.as_ptr().add(FarTrailingIdx - totIdx) - *inOpen.as_ptr().add(FarTrailingIdx - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_15 = 0.0;
                    }
                }
                *FarPeriodTotal.as_mut_ptr().add(totIdx) = *FarPeriodTotal.as_ptr().add(totIdx) + (_candlerange_14 - _candlerange_15);
                let mut _candlerange_16: f64;
                match Near_rangeType {
                    0 => {
                        _candlerange_16 = (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_16 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx);
                    }
                    2 => {
                        _candlerange_16 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx) - (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_16 = 0.0;
                    }
                }
                let mut _candlerange_17: f64;
                match Near_rangeType {
                    0 => {
                        _candlerange_17 = (*inClose.as_ptr().add(NearTrailingIdx - totIdx) - *inOpen.as_ptr().add(NearTrailingIdx - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_17 = *inHigh.as_ptr().add(NearTrailingIdx - totIdx) - *inLow.as_ptr().add(NearTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_17 = *inHigh.as_ptr().add(NearTrailingIdx - totIdx) - *inLow.as_ptr().add(NearTrailingIdx - totIdx) - (*inClose.as_ptr().add(NearTrailingIdx - totIdx) - *inOpen.as_ptr().add(NearTrailingIdx - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_17 = 0.0;
                    }
                }
                *NearPeriodTotal.as_mut_ptr().add(totIdx) = *NearPeriodTotal.as_ptr().add(totIdx) + (_candlerange_16 - _candlerange_17);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            let mut _candlerange_18: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_18 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_18 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_18 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_18 = 0.0;
                }
            }
            let mut _candlerange_19: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_19 = (*inClose.as_ptr().add(BodyLongTrailingIdx - 2) - *inOpen.as_ptr().add(BodyLongTrailingIdx - 2)).abs();
                }
                1 => {
                    _candlerange_19 = *inHigh.as_ptr().add(BodyLongTrailingIdx - 2) - *inLow.as_ptr().add(BodyLongTrailingIdx - 2);
                }
                2 => {
                    _candlerange_19 = *inHigh.as_ptr().add(BodyLongTrailingIdx - 2) - *inLow.as_ptr().add(BodyLongTrailingIdx - 2) - (*inClose.as_ptr().add(BodyLongTrailingIdx - 2) - *inOpen.as_ptr().add(BodyLongTrailingIdx - 2)).abs();
                }
                _ => {
                    _candlerange_19 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_18 - _candlerange_19;
            i += 1;
            ShadowShortTrailingIdx += 1;
            ShadowLongTrailingIdx += 1;
            NearTrailingIdx += 1;
            FarTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
