/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlhikkakemod`].
    ///
    /// # Arguments
    ///
    pub fn cdlhikkakemod_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        return ((1).max(Near_avgPeriod) + 5) as usize;
    }
    /// Modified Hikkake Pattern
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlhikkakemod(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut NearPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut NearTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut patternIdx: usize = 0_usize;
        let mut patternResult: i32 = 0_i32;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        lookbackTotal = self.cdlhikkakemod_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        NearPeriodTotal = 0.0;
        NearTrailingIdx = startIdx - 3 - (Near_avgPeriod) as usize;
        i = NearTrailingIdx;
        while i < startIdx - 3 {
            let mut _candlerange_0: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_0;
            i += 1;
        }
        patternIdx = 0;
        patternResult = 0;
        i = startIdx - 3;
        while i < startIdx {
            if inHigh[i - 2] < inHigh[i - 3] && inLow[i - 2] > inLow[i - 3] && inHigh[i - 1] < inHigh[i - 2] && inLow[i - 1] > inLow[i - 2] && (inHigh[i] < inHigh[i - 1] && inLow[i] < inLow[i - 1] && inClose[i - 2] <= inLow[i - 2] + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) || inHigh[i] > inHigh[i - 1] && inLow[i] > inLow[i - 1] && inClose[i - 2] >= inHigh[i - 2] - ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                patternResult = 100 * (if inHigh[i] < inHigh[i - 1] { 1 } else { 0 - 1 });
                patternIdx = i;
            } else if i <= patternIdx + 3 && (patternResult > 0 && inClose[i] > inHigh[patternIdx - 1] || patternResult < 0 && inClose[i] < inLow[patternIdx - 1]) {
                patternIdx = 0;
            }
            let mut _candlerange_1: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            let mut _candlerange_2: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_2 = (inClose[NearTrailingIdx - 2] - inOpen[NearTrailingIdx - 2]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[NearTrailingIdx - 2] - inLow[NearTrailingIdx - 2];
                }
                2 => {
                    _candlerange_2 = inHigh[NearTrailingIdx - 2] - inLow[NearTrailingIdx - 2] - (inClose[NearTrailingIdx - 2] - inOpen[NearTrailingIdx - 2]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_1 - _candlerange_2;
            NearTrailingIdx += 1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if inHigh[i - 2] < inHigh[i - 3] && inLow[i - 2] > inLow[i - 3] && inHigh[i - 1] < inHigh[i - 2] && inLow[i - 1] > inLow[i - 2] && (inHigh[i] < inHigh[i - 1] && inLow[i] < inLow[i - 1] && inClose[i - 2] <= inLow[i - 2] + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) || inHigh[i] > inHigh[i - 1] && inLow[i] > inLow[i - 1] && inClose[i - 2] >= inHigh[i - 2] - ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                patternResult = 100 * (if inHigh[i] < inHigh[i - 1] { 1 } else { 0 - 1 });
                patternIdx = i;
                outInteger[outIdx] = (patternResult) as i32;
                outIdx += 1;
            } else if i <= patternIdx + 3 && (patternResult > 0 && inClose[i] > inHigh[patternIdx - 1] || patternResult < 0 && inClose[i] < inLow[patternIdx - 1]) {
                outInteger[outIdx] = (patternResult + (100 * (if patternResult > 0 { 1 } else { 0 - 1 })) as i32) as i32;
                outIdx += 1;
                patternIdx = 0;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            let mut _candlerange_3: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_3 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_3 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_4 = (inClose[NearTrailingIdx - 2] - inOpen[NearTrailingIdx - 2]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[NearTrailingIdx - 2] - inLow[NearTrailingIdx - 2];
                }
                2 => {
                    _candlerange_4 = inHigh[NearTrailingIdx - 2] - inLow[NearTrailingIdx - 2] - (inClose[NearTrailingIdx - 2] - inOpen[NearTrailingIdx - 2]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_3 - _candlerange_4;
            NearTrailingIdx += 1;
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cdlhikkakemod_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut NearPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut NearTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut patternIdx: usize = 0_usize;
        let mut patternResult: i32 = 0_i32;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        unsafe {
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outInteger.len());
        lookbackTotal = self.cdlhikkakemod_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        NearPeriodTotal = 0.0;
        NearTrailingIdx = startIdx - 3 - (Near_avgPeriod) as usize;
        i = NearTrailingIdx;
        while i < startIdx - 3 {
            let mut _candlerange_0: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_0 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_0;
            i += 1;
        }
        patternIdx = 0;
        patternResult = 0;
        i = startIdx - 3;
        while i < startIdx {
            if *inHigh.as_ptr().add(i - 2) < *inHigh.as_ptr().add(i - 3) && *inLow.as_ptr().add(i - 2) > *inLow.as_ptr().add(i - 3) && *inHigh.as_ptr().add(i - 1) < *inHigh.as_ptr().add(i - 2) && *inLow.as_ptr().add(i - 1) > *inLow.as_ptr().add(i - 2) && (*inHigh.as_ptr().add(i) < *inHigh.as_ptr().add(i - 1) && *inLow.as_ptr().add(i) < *inLow.as_ptr().add(i - 1) && *inClose.as_ptr().add(i - 2) <= *inLow.as_ptr().add(i - 2) + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) || *inHigh.as_ptr().add(i) > *inHigh.as_ptr().add(i - 1) && *inLow.as_ptr().add(i) > *inLow.as_ptr().add(i - 1) && *inClose.as_ptr().add(i - 2) >= *inHigh.as_ptr().add(i - 2) - ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                patternResult = 100 * (if *inHigh.as_ptr().add(i) < *inHigh.as_ptr().add(i - 1) { 1 } else { 0 - 1 });
                patternIdx = i;
            } else if i <= patternIdx + 3 && (patternResult > 0 && *inClose.as_ptr().add(i) > *inHigh.as_ptr().add(patternIdx - 1) || patternResult < 0 && *inClose.as_ptr().add(i) < *inLow.as_ptr().add(patternIdx - 1)) {
                patternIdx = 0;
            }
            let mut _candlerange_1: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_1 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            let mut _candlerange_2: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_2 = (*inClose.as_ptr().add(NearTrailingIdx - 2) - *inOpen.as_ptr().add(NearTrailingIdx - 2)).abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.as_ptr().add(NearTrailingIdx - 2) - *inLow.as_ptr().add(NearTrailingIdx - 2);
                }
                2 => {
                    _candlerange_2 = *inHigh.as_ptr().add(NearTrailingIdx - 2) - *inLow.as_ptr().add(NearTrailingIdx - 2) - (*inClose.as_ptr().add(NearTrailingIdx - 2) - *inOpen.as_ptr().add(NearTrailingIdx - 2)).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_1 - _candlerange_2;
            NearTrailingIdx += 1;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if *inHigh.as_ptr().add(i - 2) < *inHigh.as_ptr().add(i - 3) && *inLow.as_ptr().add(i - 2) > *inLow.as_ptr().add(i - 3) && *inHigh.as_ptr().add(i - 1) < *inHigh.as_ptr().add(i - 2) && *inLow.as_ptr().add(i - 1) > *inLow.as_ptr().add(i - 2) && (*inHigh.as_ptr().add(i) < *inHigh.as_ptr().add(i - 1) && *inLow.as_ptr().add(i) < *inLow.as_ptr().add(i - 1) && *inClose.as_ptr().add(i - 2) <= *inLow.as_ptr().add(i - 2) + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) || *inHigh.as_ptr().add(i) > *inHigh.as_ptr().add(i - 1) && *inLow.as_ptr().add(i) > *inLow.as_ptr().add(i - 1) && *inClose.as_ptr().add(i - 2) >= *inHigh.as_ptr().add(i - 2) - ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                patternResult = 100 * (if *inHigh.as_ptr().add(i) < *inHigh.as_ptr().add(i - 1) { 1 } else { 0 - 1 });
                patternIdx = i;
                *outInteger.as_mut_ptr().add(outIdx) = (patternResult) as i32;
                outIdx += 1;
            } else if i <= patternIdx + 3 && (patternResult > 0 && *inClose.as_ptr().add(i) > *inHigh.as_ptr().add(patternIdx - 1) || patternResult < 0 && *inClose.as_ptr().add(i) < *inLow.as_ptr().add(patternIdx - 1)) {
                *outInteger.as_mut_ptr().add(outIdx) = (patternResult + (100 * (if patternResult > 0 { 1 } else { 0 - 1 })) as i32) as i32;
                outIdx += 1;
                patternIdx = 0;
            } else {
                *outInteger.as_mut_ptr().add(outIdx) = 0;
                outIdx += 1;
            }
            let mut _candlerange_3: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_3 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_4 = (*inClose.as_ptr().add(NearTrailingIdx - 2) - *inOpen.as_ptr().add(NearTrailingIdx - 2)).abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.as_ptr().add(NearTrailingIdx - 2) - *inLow.as_ptr().add(NearTrailingIdx - 2);
                }
                2 => {
                    _candlerange_4 = *inHigh.as_ptr().add(NearTrailingIdx - 2) - *inLow.as_ptr().add(NearTrailingIdx - 2) - (*inClose.as_ptr().add(NearTrailingIdx - 2) - *inOpen.as_ptr().add(NearTrailingIdx - 2)).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_3 - _candlerange_4;
            NearTrailingIdx += 1;
            i += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
