/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlrisefall3methods`].
    ///
    /// # Arguments
    ///
    pub fn cdlrisefall3methods_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        return ((BodyShort_avgPeriod).max(BodyLong_avgPeriod) + 4) as usize;
    }
    /// Rising/Falling Three Methods
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlrisefall3methods(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut BodyPeriodTotal: [f64; 5 as usize] = [0.0_f64; 5 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        lookbackTotal = self.cdlrisefall3methods_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyPeriodTotal[4] = 0.0;
        BodyPeriodTotal[3] = 0.0;
        BodyPeriodTotal[2] = 0.0;
        BodyPeriodTotal[1] = 0.0;
        BodyPeriodTotal[0] = 0.0;
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i - 3] - inOpen[i - 3]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i - 3] - inLow[i - 3];
                }
                2 => {
                    _candlerange_0 = inHigh[i - 3] - inLow[i - 3] - (inClose[i - 3] - inOpen[i - 3]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyPeriodTotal[3] = BodyPeriodTotal[3] + _candlerange_0;
            let mut _candlerange_1: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2];
                }
                2 => {
                    _candlerange_1 = inHigh[i - 2] - inLow[i - 2] - (inClose[i - 2] - inOpen[i - 2]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyPeriodTotal[2] = BodyPeriodTotal[2] + _candlerange_1;
            let mut _candlerange_2: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            BodyPeriodTotal[1] = BodyPeriodTotal[1] + _candlerange_2;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = (inClose[i - 4] - inOpen[i - 4]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i - 4] - inLow[i - 4];
                }
                2 => {
                    _candlerange_3 = inHigh[i - 4] - inLow[i - 4] - (inClose[i - 4] - inOpen[i - 4]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            BodyPeriodTotal[4] = BodyPeriodTotal[4] + _candlerange_3;
            let mut _candlerange_4: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_4 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            BodyPeriodTotal[0] = BodyPeriodTotal[0] + _candlerange_4;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 }) == 0 - (if inClose[i - 3] >= inOpen[i - 3] { 1 } else { 0 - 1 }) && (if inClose[i - 3] >= inOpen[i - 3] { 1 } else { 0 - 1 }) == (if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 }) && (if inClose[i - 2] >= inOpen[i - 2] { 1 } else { 0 - 1 }) == (if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 }) && (if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 }) == 0 - (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) && (inOpen[i - 3]).min(inClose[i - 3]) < inHigh[i - 4] && (inOpen[i - 3]).max(inClose[i - 3]) > inLow[i - 4] && (inOpen[i - 2]).min(inClose[i - 2]) < inHigh[i - 4] && (inOpen[i - 2]).max(inClose[i - 2]) > inLow[i - 4] && (inOpen[i - 1]).min(inClose[i - 1]) < inHigh[i - 4] && (inOpen[i - 1]).max(inClose[i - 1]) > inLow[i - 4] && inClose[i - 2] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) < inClose[i - 3] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) && inClose[i - 1] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) < inClose[i - 2] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) && inOpen[i] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) > inClose[i - 1] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) && inClose[i] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) > inClose[i - 4] * (((if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as f64) && (inClose[i - 4] - inOpen[i - 4]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyPeriodTotal[4]) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i - 4] - inOpen[i - 4]).abs(), 1 => (inHigh[i - 4]) - (inLow[i - 4]), _ => (inHigh[i - 4]) - (inLow[i - 4]) - ((inClose[i - 4]) - (inOpen[i - 4])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i - 3] - inOpen[i - 3]).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (BodyPeriodTotal[3]) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (inClose[i - 3] - inOpen[i - 3]).abs(), 1 => (inHigh[i - 3]) - (inLow[i - 3]), _ => (inHigh[i - 3]) - (inLow[i - 3]) - ((inClose[i - 3]) - (inOpen[i - 3])).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i - 2] - inOpen[i - 2]).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (BodyPeriodTotal[2]) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (inClose[i - 2] - inOpen[i - 2]).abs(), 1 => (inHigh[i - 2]) - (inLow[i - 2]), _ => (inHigh[i - 2]) - (inLow[i - 2]) - ((inClose[i - 2]) - (inOpen[i - 2])).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i - 1] - inOpen[i - 1]).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (BodyPeriodTotal[1]) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i] - inOpen[i]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyPeriodTotal[0]) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) {
                outInteger[outIdx] = (100 * (if inClose[i - 4] >= inOpen[i - 4] { 1 } else { 0 - 1 })) as i32;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            let mut _candlerange_5: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = (inClose[i - 4] - inOpen[i - 4]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[i - 4] - inLow[i - 4];
                }
                2 => {
                    _candlerange_5 = inHigh[i - 4] - inLow[i - 4] - (inClose[i - 4] - inOpen[i - 4]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_6 = (inClose[BodyLongTrailingIdx - 4] - inOpen[BodyLongTrailingIdx - 4]).abs();
                }
                1 => {
                    _candlerange_6 = inHigh[BodyLongTrailingIdx - 4] - inLow[BodyLongTrailingIdx - 4];
                }
                2 => {
                    _candlerange_6 = inHigh[BodyLongTrailingIdx - 4] - inLow[BodyLongTrailingIdx - 4] - (inClose[BodyLongTrailingIdx - 4] - inOpen[BodyLongTrailingIdx - 4]).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            BodyPeriodTotal[4] = BodyPeriodTotal[4] + (_candlerange_5 - _candlerange_6);
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            loop {
                let mut _candlerange_7: f64;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_7 = (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_7 = inHigh[i - totIdx] - inLow[i - totIdx];
                    }
                    2 => {
                        _candlerange_7 = inHigh[i - totIdx] - inLow[i - totIdx] - (inClose[i - totIdx] - inOpen[i - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_7 = 0.0;
                    }
                }
                let mut _candlerange_8: f64;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_8 = (inClose[BodyShortTrailingIdx - totIdx] - inOpen[BodyShortTrailingIdx - totIdx]).abs();
                    }
                    1 => {
                        _candlerange_8 = inHigh[BodyShortTrailingIdx - totIdx] - inLow[BodyShortTrailingIdx - totIdx];
                    }
                    2 => {
                        _candlerange_8 = inHigh[BodyShortTrailingIdx - totIdx] - inLow[BodyShortTrailingIdx - totIdx] - (inClose[BodyShortTrailingIdx - totIdx] - inOpen[BodyShortTrailingIdx - totIdx]).abs();
                    }
                    _ => {
                        _candlerange_8 = 0.0;
                    }
                }
                BodyPeriodTotal[totIdx] = BodyPeriodTotal[totIdx] + (_candlerange_7 - _candlerange_8);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            let mut _candlerange_9: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_9 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_9 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_9 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_9 = 0.0;
                }
            }
            let mut _candlerange_10: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_10 = (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_10 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx];
                }
                2 => {
                    _candlerange_10 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx] - (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_10 = 0.0;
                }
            }
            BodyPeriodTotal[0] = BodyPeriodTotal[0] + (_candlerange_9 - _candlerange_10);
            i += 1;
            BodyShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cdlrisefall3methods_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyPeriodTotal: [f64; 5 as usize] = [0.0_f64; 5 as usize];
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut totIdx: usize = 0_usize;
        let mut BodyShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let BodyShort_rangeType: i32 = self.candle_settings.body_short.range_type;
        #[allow(non_snake_case)]
        let BodyShort_avgPeriod: i32 = self.candle_settings.body_short.avg_period;
        #[allow(non_snake_case)]
        let BodyShort_factor: f64 = self.candle_settings.body_short.factor;
        unsafe {
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outInteger.len());
        lookbackTotal = self.cdlrisefall3methods_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        *BodyPeriodTotal.as_mut_ptr().add(4) = 0.0;
        *BodyPeriodTotal.as_mut_ptr().add(3) = 0.0;
        *BodyPeriodTotal.as_mut_ptr().add(2) = 0.0;
        *BodyPeriodTotal.as_mut_ptr().add(1) = 0.0;
        *BodyPeriodTotal.as_mut_ptr().add(0) = 0.0;
        BodyShortTrailingIdx = startIdx - (BodyShort_avgPeriod) as usize;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        i = BodyShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_0 = (*inClose.as_ptr().add(i - 3) - *inOpen.as_ptr().add(i - 3)).abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i - 3) - *inLow.as_ptr().add(i - 3);
                }
                2 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i - 3) - *inLow.as_ptr().add(i - 3) - (*inClose.as_ptr().add(i - 3) - *inOpen.as_ptr().add(i - 3)).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(3) = *BodyPeriodTotal.as_ptr().add(3) + _candlerange_0;
            let mut _candlerange_1: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_1 = (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2);
                }
                2 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i - 2) - *inLow.as_ptr().add(i - 2) - (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(2) = *BodyPeriodTotal.as_ptr().add(2) + _candlerange_1;
            let mut _candlerange_2: f64;
            match BodyShort_rangeType {
                0 => {
                    _candlerange_2 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(1) = *BodyPeriodTotal.as_ptr().add(1) + _candlerange_2;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_3: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_3 = (*inClose.as_ptr().add(i - 4) - *inOpen.as_ptr().add(i - 4)).abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i - 4) - *inLow.as_ptr().add(i - 4);
                }
                2 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i - 4) - *inLow.as_ptr().add(i - 4) - (*inClose.as_ptr().add(i - 4) - *inOpen.as_ptr().add(i - 4)).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(4) = *BodyPeriodTotal.as_ptr().add(4) + _candlerange_3;
            let mut _candlerange_4: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_4 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_4 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(0) = *BodyPeriodTotal.as_ptr().add(0) + _candlerange_4;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 }) == 0 - (if *inClose.as_ptr().add(i - 3) >= *inOpen.as_ptr().add(i - 3) { 1 } else { 0 - 1 }) && (if *inClose.as_ptr().add(i - 3) >= *inOpen.as_ptr().add(i - 3) { 1 } else { 0 - 1 }) == (if *inClose.as_ptr().add(i - 2) >= *inOpen.as_ptr().add(i - 2) { 1 } else { 0 - 1 }) && (if *inClose.as_ptr().add(i - 2) >= *inOpen.as_ptr().add(i - 2) { 1 } else { 0 - 1 }) == (if *inClose.as_ptr().add(i - 1) >= *inOpen.as_ptr().add(i - 1) { 1 } else { 0 - 1 }) && (if *inClose.as_ptr().add(i - 1) >= *inOpen.as_ptr().add(i - 1) { 1 } else { 0 - 1 }) == 0 - (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 }) && (*inOpen.as_ptr().add(i - 3)).min(*inClose.as_ptr().add(i - 3)) < *inHigh.as_ptr().add(i - 4) && (*inOpen.as_ptr().add(i - 3)).max(*inClose.as_ptr().add(i - 3)) > *inLow.as_ptr().add(i - 4) && (*inOpen.as_ptr().add(i - 2)).min(*inClose.as_ptr().add(i - 2)) < *inHigh.as_ptr().add(i - 4) && (*inOpen.as_ptr().add(i - 2)).max(*inClose.as_ptr().add(i - 2)) > *inLow.as_ptr().add(i - 4) && (*inOpen.as_ptr().add(i - 1)).min(*inClose.as_ptr().add(i - 1)) < *inHigh.as_ptr().add(i - 4) && (*inOpen.as_ptr().add(i - 1)).max(*inClose.as_ptr().add(i - 1)) > *inLow.as_ptr().add(i - 4) && *inClose.as_ptr().add(i - 2) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) < *inClose.as_ptr().add(i - 3) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) && *inClose.as_ptr().add(i - 1) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) < *inClose.as_ptr().add(i - 2) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) && *inOpen.as_ptr().add(i) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) > *inClose.as_ptr().add(i - 1) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) && *inClose.as_ptr().add(i) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) > *inClose.as_ptr().add(i - 4) * (((if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as f64) && (*inClose.as_ptr().add(i - 4) - *inOpen.as_ptr().add(i - 4)).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (*BodyPeriodTotal.as_ptr().add(4)) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (*inClose.as_ptr().add(i - 4) - *inOpen.as_ptr().add(i - 4)).abs(), 1 => (*inHigh.as_ptr().add(i - 4)) - (*inLow.as_ptr().add(i - 4)), _ => (*inHigh.as_ptr().add(i - 4)) - (*inLow.as_ptr().add(i - 4)) - ((*inClose.as_ptr().add(i - 4)) - (*inOpen.as_ptr().add(i - 4))).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i - 3) - *inOpen.as_ptr().add(i - 3)).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (*BodyPeriodTotal.as_ptr().add(3)) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (*inClose.as_ptr().add(i - 3) - *inOpen.as_ptr().add(i - 3)).abs(), 1 => (*inHigh.as_ptr().add(i - 3)) - (*inLow.as_ptr().add(i - 3)), _ => (*inHigh.as_ptr().add(i - 3)) - (*inLow.as_ptr().add(i - 3)) - ((*inClose.as_ptr().add(i - 3)) - (*inOpen.as_ptr().add(i - 3))).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (*BodyPeriodTotal.as_ptr().add(2)) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (*inClose.as_ptr().add(i - 2) - *inOpen.as_ptr().add(i - 2)).abs(), 1 => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)), _ => (*inHigh.as_ptr().add(i - 2)) - (*inLow.as_ptr().add(i - 2)) - ((*inClose.as_ptr().add(i - 2)) - (*inOpen.as_ptr().add(i - 2))).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs() < ((BodyShort_factor) * (if (BodyShort_avgPeriod) != 0 { (*BodyPeriodTotal.as_ptr().add(1)) / (BodyShort_avgPeriod as f64) } else { match BodyShort_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (BodyShort_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (*BodyPeriodTotal.as_ptr().add(0)) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) {
                *outInteger.as_mut_ptr().add(outIdx) = (100 * (if *inClose.as_ptr().add(i - 4) >= *inOpen.as_ptr().add(i - 4) { 1 } else { 0 - 1 })) as i32;
                outIdx += 1;
            } else {
                *outInteger.as_mut_ptr().add(outIdx) = 0;
                outIdx += 1;
            }
            let mut _candlerange_5: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = (*inClose.as_ptr().add(i - 4) - *inOpen.as_ptr().add(i - 4)).abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i - 4) - *inLow.as_ptr().add(i - 4);
                }
                2 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i - 4) - *inLow.as_ptr().add(i - 4) - (*inClose.as_ptr().add(i - 4) - *inOpen.as_ptr().add(i - 4)).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_6 = (*inClose.as_ptr().add(BodyLongTrailingIdx - 4) - *inOpen.as_ptr().add(BodyLongTrailingIdx - 4)).abs();
                }
                1 => {
                    _candlerange_6 = *inHigh.as_ptr().add(BodyLongTrailingIdx - 4) - *inLow.as_ptr().add(BodyLongTrailingIdx - 4);
                }
                2 => {
                    _candlerange_6 = *inHigh.as_ptr().add(BodyLongTrailingIdx - 4) - *inLow.as_ptr().add(BodyLongTrailingIdx - 4) - (*inClose.as_ptr().add(BodyLongTrailingIdx - 4) - *inOpen.as_ptr().add(BodyLongTrailingIdx - 4)).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(4) = *BodyPeriodTotal.as_ptr().add(4) + (_candlerange_5 - _candlerange_6);
            // for( totIdx = 3; totIdx >= 1; totIdx -= 1 )
            totIdx = 3;
            loop {
                let mut _candlerange_7: f64;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_7 = (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_7 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx);
                    }
                    2 => {
                        _candlerange_7 = *inHigh.as_ptr().add(i - totIdx) - *inLow.as_ptr().add(i - totIdx) - (*inClose.as_ptr().add(i - totIdx) - *inOpen.as_ptr().add(i - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_7 = 0.0;
                    }
                }
                let mut _candlerange_8: f64;
                match BodyShort_rangeType {
                    0 => {
                        _candlerange_8 = (*inClose.as_ptr().add(BodyShortTrailingIdx - totIdx) - *inOpen.as_ptr().add(BodyShortTrailingIdx - totIdx)).abs();
                    }
                    1 => {
                        _candlerange_8 = *inHigh.as_ptr().add(BodyShortTrailingIdx - totIdx) - *inLow.as_ptr().add(BodyShortTrailingIdx - totIdx);
                    }
                    2 => {
                        _candlerange_8 = *inHigh.as_ptr().add(BodyShortTrailingIdx - totIdx) - *inLow.as_ptr().add(BodyShortTrailingIdx - totIdx) - (*inClose.as_ptr().add(BodyShortTrailingIdx - totIdx) - *inOpen.as_ptr().add(BodyShortTrailingIdx - totIdx)).abs();
                    }
                    _ => {
                        _candlerange_8 = 0.0;
                    }
                }
                *BodyPeriodTotal.as_mut_ptr().add(totIdx) = *BodyPeriodTotal.as_ptr().add(totIdx) + (_candlerange_7 - _candlerange_8);
                if totIdx == 1 { break; }
                totIdx -= 1;
            }
            let mut _candlerange_9: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_9 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_9 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_9 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_9 = 0.0;
                }
            }
            let mut _candlerange_10: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_10 = (*inClose.as_ptr().add(BodyLongTrailingIdx) - *inOpen.as_ptr().add(BodyLongTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_10 = *inHigh.as_ptr().add(BodyLongTrailingIdx) - *inLow.as_ptr().add(BodyLongTrailingIdx);
                }
                2 => {
                    _candlerange_10 = *inHigh.as_ptr().add(BodyLongTrailingIdx) - *inLow.as_ptr().add(BodyLongTrailingIdx) - (*inClose.as_ptr().add(BodyLongTrailingIdx) - *inOpen.as_ptr().add(BodyLongTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_10 = 0.0;
                }
            }
            *BodyPeriodTotal.as_mut_ptr().add(0) = *BodyPeriodTotal.as_ptr().add(0) + (_candlerange_9 - _candlerange_10);
            i += 1;
            BodyShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
