/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlrickshawman`].
    ///
    /// # Arguments
    ///
    pub fn cdlrickshawman_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        return (((BodyDoji_avgPeriod).max(ShadowLong_avgPeriod)).max(Near_avgPeriod)) as usize;
    }
    /// Rickshaw Man
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlrickshawman(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut BodyDojiPeriodTotal: f64 = 0.0_f64;
        let mut ShadowLongPeriodTotal: f64 = 0.0_f64;
        let mut NearPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyDojiTrailingIdx: usize = 0_usize;
        let mut ShadowLongTrailingIdx: usize = 0_usize;
        let mut NearTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        lookbackTotal = self.cdlrickshawman_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyDojiPeriodTotal = 0.0;
        BodyDojiTrailingIdx = startIdx - (BodyDoji_avgPeriod) as usize;
        ShadowLongPeriodTotal = 0.0;
        ShadowLongTrailingIdx = startIdx - (ShadowLong_avgPeriod) as usize;
        NearPeriodTotal = 0.0;
        NearTrailingIdx = startIdx - (Near_avgPeriod) as usize;
        i = BodyDojiTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyDojiPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_2 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_2;
            i += 1;
        }
        outIdx = 0;
        loop {
            if (inClose[i] - inOpen[i]).abs() <= ((BodyDoji_factor) * (if (BodyDoji_avgPeriod) != 0 { (BodyDojiPeriodTotal) / (BodyDoji_avgPeriod as f64) } else { match BodyDoji_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyDoji_rangeType) == 2 { 2.0 } else { 1.0 })) && ((if inClose[i] >= inOpen[i] { inOpen[i] } else { inClose[i] }) - inLow[i]) > ((ShadowLong_factor) * (if (ShadowLong_avgPeriod) != 0 { (ShadowLongPeriodTotal) / (ShadowLong_avgPeriod as f64) } else { match ShadowLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (ShadowLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (inHigh[i] - (if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] })) > ((ShadowLong_factor) * (if (ShadowLong_avgPeriod) != 0 { (ShadowLongPeriodTotal) / (ShadowLong_avgPeriod as f64) } else { match ShadowLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (ShadowLong_rangeType) == 2 { 2.0 } else { 1.0 })) && ((inOpen[i]).min(inClose[i]) <= inLow[i] + (inHigh[i] - inLow[i]) / 2_f64 + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) && (inOpen[i]).max(inClose[i]) >= inLow[i] + (inHigh[i] - inLow[i]) / 2_f64 - ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                outInteger[outIdx] = 100;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            let mut _candlerange_3: f64;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_3 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_3 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_4 = (inClose[BodyDojiTrailingIdx] - inOpen[BodyDojiTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[BodyDojiTrailingIdx] - inLow[BodyDojiTrailingIdx];
                }
                2 => {
                    _candlerange_4 = inHigh[BodyDojiTrailingIdx] - inLow[BodyDojiTrailingIdx] - (inClose[BodyDojiTrailingIdx] - inOpen[BodyDojiTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            BodyDojiPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_5 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_5 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_6 = (inClose[ShadowLongTrailingIdx] - inOpen[ShadowLongTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_6 = inHigh[ShadowLongTrailingIdx] - inLow[ShadowLongTrailingIdx];
                }
                2 => {
                    _candlerange_6 = inHigh[ShadowLongTrailingIdx] - inLow[ShadowLongTrailingIdx] - (inClose[ShadowLongTrailingIdx] - inOpen[ShadowLongTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            ShadowLongPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_7 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_7 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_7 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            let mut _candlerange_8: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_8 = (inClose[NearTrailingIdx] - inOpen[NearTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_8 = inHigh[NearTrailingIdx] - inLow[NearTrailingIdx];
                }
                2 => {
                    _candlerange_8 = inHigh[NearTrailingIdx] - inLow[NearTrailingIdx] - (inClose[NearTrailingIdx] - inOpen[NearTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            BodyDojiTrailingIdx += 1;
            ShadowLongTrailingIdx += 1;
            NearTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cdlrickshawman_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut BodyDojiPeriodTotal: f64 = 0.0_f64;
        let mut ShadowLongPeriodTotal: f64 = 0.0_f64;
        let mut NearPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut BodyDojiTrailingIdx: usize = 0_usize;
        let mut ShadowLongTrailingIdx: usize = 0_usize;
        let mut NearTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyDoji_rangeType: i32 = self.candle_settings.body_doji.range_type;
        #[allow(non_snake_case)]
        let BodyDoji_avgPeriod: i32 = self.candle_settings.body_doji.avg_period;
        #[allow(non_snake_case)]
        let BodyDoji_factor: f64 = self.candle_settings.body_doji.factor;
        #[allow(non_snake_case)]
        let Near_rangeType: i32 = self.candle_settings.near.range_type;
        #[allow(non_snake_case)]
        let Near_avgPeriod: i32 = self.candle_settings.near.avg_period;
        #[allow(non_snake_case)]
        let Near_factor: f64 = self.candle_settings.near.factor;
        #[allow(non_snake_case)]
        let ShadowLong_rangeType: i32 = self.candle_settings.shadow_long.range_type;
        #[allow(non_snake_case)]
        let ShadowLong_avgPeriod: i32 = self.candle_settings.shadow_long.avg_period;
        #[allow(non_snake_case)]
        let ShadowLong_factor: f64 = self.candle_settings.shadow_long.factor;
        unsafe {
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outInteger.len());
        lookbackTotal = self.cdlrickshawman_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        BodyDojiPeriodTotal = 0.0;
        BodyDojiTrailingIdx = startIdx - (BodyDoji_avgPeriod) as usize;
        ShadowLongPeriodTotal = 0.0;
        ShadowLongTrailingIdx = startIdx - (ShadowLong_avgPeriod) as usize;
        NearPeriodTotal = 0.0;
        NearTrailingIdx = startIdx - (Near_avgPeriod) as usize;
        i = BodyDojiTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_0 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            BodyDojiPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = ShadowLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_1 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            ShadowLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = NearTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_2 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_2;
            i += 1;
        }
        outIdx = 0;
        loop {
            if (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() <= ((BodyDoji_factor) * (if (BodyDoji_avgPeriod) != 0 { (BodyDojiPeriodTotal) / (BodyDoji_avgPeriod as f64) } else { match BodyDoji_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (BodyDoji_rangeType) == 2 { 2.0 } else { 1.0 })) && ((if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { *inOpen.as_ptr().add(i) } else { *inClose.as_ptr().add(i) }) - *inLow.as_ptr().add(i)) > ((ShadowLong_factor) * (if (ShadowLong_avgPeriod) != 0 { (ShadowLongPeriodTotal) / (ShadowLong_avgPeriod as f64) } else { match ShadowLong_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (ShadowLong_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inHigh.as_ptr().add(i) - (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { *inClose.as_ptr().add(i) } else { *inOpen.as_ptr().add(i) })) > ((ShadowLong_factor) * (if (ShadowLong_avgPeriod) != 0 { (ShadowLongPeriodTotal) / (ShadowLong_avgPeriod as f64) } else { match ShadowLong_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (ShadowLong_rangeType) == 2 { 2.0 } else { 1.0 })) && ((*inOpen.as_ptr().add(i)).min(*inClose.as_ptr().add(i)) <= *inLow.as_ptr().add(i) + (*inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i)) / 2_f64 + ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inOpen.as_ptr().add(i)).max(*inClose.as_ptr().add(i)) >= *inLow.as_ptr().add(i) + (*inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i)) / 2_f64 - ((Near_factor) * (if (Near_avgPeriod) != 0 { (NearPeriodTotal) / (Near_avgPeriod as f64) } else { match Near_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (Near_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                *outInteger.as_mut_ptr().add(outIdx) = 100;
                outIdx += 1;
            } else {
                *outInteger.as_mut_ptr().add(outIdx) = 0;
                outIdx += 1;
            }
            let mut _candlerange_3: f64;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_3 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match BodyDoji_rangeType {
                0 => {
                    _candlerange_4 = (*inClose.as_ptr().add(BodyDojiTrailingIdx) - *inOpen.as_ptr().add(BodyDojiTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.as_ptr().add(BodyDojiTrailingIdx) - *inLow.as_ptr().add(BodyDojiTrailingIdx);
                }
                2 => {
                    _candlerange_4 = *inHigh.as_ptr().add(BodyDojiTrailingIdx) - *inLow.as_ptr().add(BodyDojiTrailingIdx) - (*inClose.as_ptr().add(BodyDojiTrailingIdx) - *inOpen.as_ptr().add(BodyDojiTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            BodyDojiPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_5 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match ShadowLong_rangeType {
                0 => {
                    _candlerange_6 = (*inClose.as_ptr().add(ShadowLongTrailingIdx) - *inOpen.as_ptr().add(ShadowLongTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_6 = *inHigh.as_ptr().add(ShadowLongTrailingIdx) - *inLow.as_ptr().add(ShadowLongTrailingIdx);
                }
                2 => {
                    _candlerange_6 = *inHigh.as_ptr().add(ShadowLongTrailingIdx) - *inLow.as_ptr().add(ShadowLongTrailingIdx) - (*inClose.as_ptr().add(ShadowLongTrailingIdx) - *inOpen.as_ptr().add(ShadowLongTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            ShadowLongPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_7 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_7 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_7 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            let mut _candlerange_8: f64;
            match Near_rangeType {
                0 => {
                    _candlerange_8 = (*inClose.as_ptr().add(NearTrailingIdx) - *inOpen.as_ptr().add(NearTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_8 = *inHigh.as_ptr().add(NearTrailingIdx) - *inLow.as_ptr().add(NearTrailingIdx);
                }
                2 => {
                    _candlerange_8 = *inHigh.as_ptr().add(NearTrailingIdx) - *inLow.as_ptr().add(NearTrailingIdx) - (*inClose.as_ptr().add(NearTrailingIdx) - *inOpen.as_ptr().add(NearTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            NearPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            BodyDojiTrailingIdx += 1;
            ShadowLongTrailingIdx += 1;
            NearTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
