/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::cdlseparatinglines`].
    ///
    /// # Arguments
    ///
    pub fn cdlseparatinglines_lookback(&self) -> usize {
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        return (((ShadowVeryShort_avgPeriod).max(BodyLong_avgPeriod)).max(Equal_avgPeriod) + 1) as usize;
    }
    /// Separating Lines
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inOpen` - Input price series
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outInteger` - Output values
    pub fn cdlseparatinglines(
        &self,
        startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut ShadowVeryShortPeriodTotal: f64 = 0.0_f64;
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut EqualPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut ShadowVeryShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut EqualTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        lookbackTotal = self.cdlseparatinglines_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        ShadowVeryShortPeriodTotal = 0.0;
        ShadowVeryShortTrailingIdx = startIdx - (ShadowVeryShort_avgPeriod) as usize;
        BodyLongPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        EqualPeriodTotal = 0.0;
        EqualTrailingIdx = startIdx - (Equal_avgPeriod) as usize;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_0 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_0 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_1 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_1 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = EqualTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_2 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_2 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            EqualPeriodTotal += _candlerange_2;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if inClose[i - 1] >= inOpen[i - 1] { 1 } else { 0 - 1 }) == 0 - (if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) && inOpen[i] <= inOpen[i - 1] + ((Equal_factor) * (if (Equal_avgPeriod) != 0 { (EqualPeriodTotal) / (Equal_avgPeriod as f64) } else { match Equal_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (Equal_rangeType) == 2 { 2.0 } else { 1.0 })) && inOpen[i] >= inOpen[i - 1] - ((Equal_factor) * (if (Equal_avgPeriod) != 0 { (EqualPeriodTotal) / (Equal_avgPeriod as f64) } else { match Equal_rangeType { 0 => (inClose[i - 1] - inOpen[i - 1]).abs(), 1 => (inHigh[i - 1]) - (inLow[i - 1]), _ => (inHigh[i - 1]) - (inLow[i - 1]) - ((inClose[i - 1]) - (inOpen[i - 1])).abs() } }) / (if (Equal_rangeType) == 2 { 2.0 } else { 1.0 })) && (inClose[i] - inOpen[i]).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && ((if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) == 1 && ((if inClose[i] >= inOpen[i] { inOpen[i] } else { inClose[i] }) - inLow[i]) < ((ShadowVeryShort_factor) * (if (ShadowVeryShort_avgPeriod) != 0 { (ShadowVeryShortPeriodTotal) / (ShadowVeryShort_avgPeriod as f64) } else { match ShadowVeryShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (ShadowVeryShort_rangeType) == 2 { 2.0 } else { 1.0 })) || ((if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 })) as i32 == 0 - 1 && (inHigh[i] - (if inClose[i] >= inOpen[i] { inClose[i] } else { inOpen[i] })) < ((ShadowVeryShort_factor) * (if (ShadowVeryShort_avgPeriod) != 0 { (ShadowVeryShortPeriodTotal) / (ShadowVeryShort_avgPeriod as f64) } else { match ShadowVeryShort_rangeType { 0 => (inClose[i] - inOpen[i]).abs(), 1 => (inHigh[i]) - (inLow[i]), _ => (inHigh[i]) - (inLow[i]) - ((inClose[i]) - (inOpen[i])).abs() } }) / (if (ShadowVeryShort_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                outInteger[outIdx] = ((if inClose[i] >= inOpen[i] { 1 } else { 0 - 1 }) * 100) as i32;
                outIdx += 1;
            } else {
                outInteger[outIdx] = 0;
                outIdx += 1;
            }
            let mut _candlerange_3: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_3 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_3 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_3 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_4 = (inClose[ShadowVeryShortTrailingIdx] - inOpen[ShadowVeryShortTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_4 = inHigh[ShadowVeryShortTrailingIdx] - inLow[ShadowVeryShortTrailingIdx];
                }
                2 => {
                    _candlerange_4 = inHigh[ShadowVeryShortTrailingIdx] - inLow[ShadowVeryShortTrailingIdx] - (inClose[ShadowVeryShortTrailingIdx] - inOpen[ShadowVeryShortTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = (inClose[i] - inOpen[i]).abs();
                }
                1 => {
                    _candlerange_5 = inHigh[i] - inLow[i];
                }
                2 => {
                    _candlerange_5 = inHigh[i] - inLow[i] - (inClose[i] - inOpen[i]).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_6 = (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                1 => {
                    _candlerange_6 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx];
                }
                2 => {
                    _candlerange_6 = inHigh[BodyLongTrailingIdx] - inLow[BodyLongTrailingIdx] - (inClose[BodyLongTrailingIdx] - inOpen[BodyLongTrailingIdx]).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_7 = (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                1 => {
                    _candlerange_7 = inHigh[i - 1] - inLow[i - 1];
                }
                2 => {
                    _candlerange_7 = inHigh[i - 1] - inLow[i - 1] - (inClose[i - 1] - inOpen[i - 1]).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            let mut _candlerange_8: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_8 = (inClose[EqualTrailingIdx - 1] - inOpen[EqualTrailingIdx - 1]).abs();
                }
                1 => {
                    _candlerange_8 = inHigh[EqualTrailingIdx - 1] - inLow[EqualTrailingIdx - 1];
                }
                2 => {
                    _candlerange_8 = inHigh[EqualTrailingIdx - 1] - inLow[EqualTrailingIdx - 1] - (inClose[EqualTrailingIdx - 1] - inOpen[EqualTrailingIdx - 1]).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            EqualPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            EqualTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn cdlseparatinglines_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inOpen: &[f64],
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outInteger: &mut [i32],
    ) -> RetCode {
        let mut ShadowVeryShortPeriodTotal: f64 = 0.0_f64;
        let mut BodyLongPeriodTotal: f64 = 0.0_f64;
        let mut EqualPeriodTotal: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut ShadowVeryShortTrailingIdx: usize = 0_usize;
        let mut BodyLongTrailingIdx: usize = 0_usize;
        let mut EqualTrailingIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        #[allow(non_snake_case)]
        let BodyLong_rangeType: i32 = self.candle_settings.body_long.range_type;
        #[allow(non_snake_case)]
        let BodyLong_avgPeriod: i32 = self.candle_settings.body_long.avg_period;
        #[allow(non_snake_case)]
        let BodyLong_factor: f64 = self.candle_settings.body_long.factor;
        #[allow(non_snake_case)]
        let Equal_rangeType: i32 = self.candle_settings.equal.range_type;
        #[allow(non_snake_case)]
        let Equal_avgPeriod: i32 = self.candle_settings.equal.avg_period;
        #[allow(non_snake_case)]
        let Equal_factor: f64 = self.candle_settings.equal.factor;
        #[allow(non_snake_case)]
        let ShadowVeryShort_rangeType: i32 = self.candle_settings.shadow_very_short.range_type;
        #[allow(non_snake_case)]
        let ShadowVeryShort_avgPeriod: i32 = self.candle_settings.shadow_very_short.avg_period;
        #[allow(non_snake_case)]
        let ShadowVeryShort_factor: f64 = self.candle_settings.shadow_very_short.factor;
        unsafe {
        assert!(endIdx < inOpen.len());
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outInteger.len());
        lookbackTotal = self.cdlseparatinglines_lookback();
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        ShadowVeryShortPeriodTotal = 0.0;
        ShadowVeryShortTrailingIdx = startIdx - (ShadowVeryShort_avgPeriod) as usize;
        BodyLongPeriodTotal = 0.0;
        BodyLongTrailingIdx = startIdx - (BodyLong_avgPeriod) as usize;
        EqualPeriodTotal = 0.0;
        EqualTrailingIdx = startIdx - (Equal_avgPeriod) as usize;
        i = ShadowVeryShortTrailingIdx;
        while i < startIdx {
            let mut _candlerange_0: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_0 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_0 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_0 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_0;
            i += 1;
        }
        i = BodyLongTrailingIdx;
        while i < startIdx {
            let mut _candlerange_1: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_1 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_1 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_1 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_1;
            i += 1;
        }
        i = EqualTrailingIdx;
        while i < startIdx {
            let mut _candlerange_2: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_2 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_2 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_2 = 0.0;
                }
            }
            EqualPeriodTotal += _candlerange_2;
            i += 1;
        }
        i = startIdx;
        outIdx = 0;
        loop {
            if (if *inClose.as_ptr().add(i - 1) >= *inOpen.as_ptr().add(i - 1) { 1 } else { 0 - 1 }) == 0 - (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 }) && *inOpen.as_ptr().add(i) <= *inOpen.as_ptr().add(i - 1) + ((Equal_factor) * (if (Equal_avgPeriod) != 0 { (EqualPeriodTotal) / (Equal_avgPeriod as f64) } else { match Equal_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (Equal_rangeType) == 2 { 2.0 } else { 1.0 })) && *inOpen.as_ptr().add(i) >= *inOpen.as_ptr().add(i - 1) - ((Equal_factor) * (if (Equal_avgPeriod) != 0 { (EqualPeriodTotal) / (Equal_avgPeriod as f64) } else { match Equal_rangeType { 0 => (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs(), 1 => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)), _ => (*inHigh.as_ptr().add(i - 1)) - (*inLow.as_ptr().add(i - 1)) - ((*inClose.as_ptr().add(i - 1)) - (*inOpen.as_ptr().add(i - 1))).abs() } }) / (if (Equal_rangeType) == 2 { 2.0 } else { 1.0 })) && (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs() > ((BodyLong_factor) * (if (BodyLong_avgPeriod) != 0 { (BodyLongPeriodTotal) / (BodyLong_avgPeriod as f64) } else { match BodyLong_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (BodyLong_rangeType) == 2 { 2.0 } else { 1.0 })) && ((if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 }) == 1 && ((if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { *inOpen.as_ptr().add(i) } else { *inClose.as_ptr().add(i) }) - *inLow.as_ptr().add(i)) < ((ShadowVeryShort_factor) * (if (ShadowVeryShort_avgPeriod) != 0 { (ShadowVeryShortPeriodTotal) / (ShadowVeryShort_avgPeriod as f64) } else { match ShadowVeryShort_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (ShadowVeryShort_rangeType) == 2 { 2.0 } else { 1.0 })) || ((if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 })) as i32 == 0 - 1 && (*inHigh.as_ptr().add(i) - (if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { *inClose.as_ptr().add(i) } else { *inOpen.as_ptr().add(i) })) < ((ShadowVeryShort_factor) * (if (ShadowVeryShort_avgPeriod) != 0 { (ShadowVeryShortPeriodTotal) / (ShadowVeryShort_avgPeriod as f64) } else { match ShadowVeryShort_rangeType { 0 => (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs(), 1 => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)), _ => (*inHigh.as_ptr().add(i)) - (*inLow.as_ptr().add(i)) - ((*inClose.as_ptr().add(i)) - (*inOpen.as_ptr().add(i))).abs() } }) / (if (ShadowVeryShort_rangeType) == 2 { 2.0 } else { 1.0 }))) {
                *outInteger.as_mut_ptr().add(outIdx) = ((if *inClose.as_ptr().add(i) >= *inOpen.as_ptr().add(i) { 1 } else { 0 - 1 }) * 100) as i32;
                outIdx += 1;
            } else {
                *outInteger.as_mut_ptr().add(outIdx) = 0;
                outIdx += 1;
            }
            let mut _candlerange_3: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_3 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_3 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_3 = 0.0;
                }
            }
            let mut _candlerange_4: f64;
            match ShadowVeryShort_rangeType {
                0 => {
                    _candlerange_4 = (*inClose.as_ptr().add(ShadowVeryShortTrailingIdx) - *inOpen.as_ptr().add(ShadowVeryShortTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_4 = *inHigh.as_ptr().add(ShadowVeryShortTrailingIdx) - *inLow.as_ptr().add(ShadowVeryShortTrailingIdx);
                }
                2 => {
                    _candlerange_4 = *inHigh.as_ptr().add(ShadowVeryShortTrailingIdx) - *inLow.as_ptr().add(ShadowVeryShortTrailingIdx) - (*inClose.as_ptr().add(ShadowVeryShortTrailingIdx) - *inOpen.as_ptr().add(ShadowVeryShortTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_4 = 0.0;
                }
            }
            ShadowVeryShortPeriodTotal += _candlerange_3 - _candlerange_4;
            let mut _candlerange_5: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_5 = (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                1 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i);
                }
                2 => {
                    _candlerange_5 = *inHigh.as_ptr().add(i) - *inLow.as_ptr().add(i) - (*inClose.as_ptr().add(i) - *inOpen.as_ptr().add(i)).abs();
                }
                _ => {
                    _candlerange_5 = 0.0;
                }
            }
            let mut _candlerange_6: f64;
            match BodyLong_rangeType {
                0 => {
                    _candlerange_6 = (*inClose.as_ptr().add(BodyLongTrailingIdx) - *inOpen.as_ptr().add(BodyLongTrailingIdx)).abs();
                }
                1 => {
                    _candlerange_6 = *inHigh.as_ptr().add(BodyLongTrailingIdx) - *inLow.as_ptr().add(BodyLongTrailingIdx);
                }
                2 => {
                    _candlerange_6 = *inHigh.as_ptr().add(BodyLongTrailingIdx) - *inLow.as_ptr().add(BodyLongTrailingIdx) - (*inClose.as_ptr().add(BodyLongTrailingIdx) - *inOpen.as_ptr().add(BodyLongTrailingIdx)).abs();
                }
                _ => {
                    _candlerange_6 = 0.0;
                }
            }
            BodyLongPeriodTotal += _candlerange_5 - _candlerange_6;
            let mut _candlerange_7: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_7 = (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                1 => {
                    _candlerange_7 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1);
                }
                2 => {
                    _candlerange_7 = *inHigh.as_ptr().add(i - 1) - *inLow.as_ptr().add(i - 1) - (*inClose.as_ptr().add(i - 1) - *inOpen.as_ptr().add(i - 1)).abs();
                }
                _ => {
                    _candlerange_7 = 0.0;
                }
            }
            let mut _candlerange_8: f64;
            match Equal_rangeType {
                0 => {
                    _candlerange_8 = (*inClose.as_ptr().add(EqualTrailingIdx - 1) - *inOpen.as_ptr().add(EqualTrailingIdx - 1)).abs();
                }
                1 => {
                    _candlerange_8 = *inHigh.as_ptr().add(EqualTrailingIdx - 1) - *inLow.as_ptr().add(EqualTrailingIdx - 1);
                }
                2 => {
                    _candlerange_8 = *inHigh.as_ptr().add(EqualTrailingIdx - 1) - *inLow.as_ptr().add(EqualTrailingIdx - 1) - (*inClose.as_ptr().add(EqualTrailingIdx - 1) - *inOpen.as_ptr().add(EqualTrailingIdx - 1)).abs();
                }
                _ => {
                    _candlerange_8 = 0.0;
                }
            }
            EqualPeriodTotal += _candlerange_7 - _candlerange_8;
            i += 1;
            ShadowVeryShortTrailingIdx += 1;
            BodyLongTrailingIdx += 1;
            EqualTrailingIdx += 1;
            if !(i <= endIdx) { break; }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
