/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::correl`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    #[inline]
    pub fn correl_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Pearson's Correlation Coefficient (r)
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal0` - Input price series
    /// * `inReal1` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn correl(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal0: &[f64],
        inReal1: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut sumXY: f64 = 0.0_f64;
        let mut sumX: f64 = 0.0_f64;
        let mut sumY: f64 = 0.0_f64;
        let mut sumX2: f64 = 0.0_f64;
        let mut sumY2: f64 = 0.0_f64;
        let mut x: f64 = 0.0_f64;
        let mut y: f64 = 0.0_f64;
        let mut trailingX: f64 = 0.0_f64;
        let mut trailingY: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        trailingIdx = startIdx - lookbackTotal;
        sumY2 = 0.0;
        sumX2 = sumY2;
        sumY = sumX2;
        sumX = sumY;
        sumXY = sumX;
        for today in (trailingIdx as usize)..(startIdx as usize) + 1 {
            x = inReal0[today];
            sumX += x;
            sumX2 += x * x;
            y = inReal1[today];
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
        }
        today = (startIdx as usize) + 1;
        trailingX = inReal0[trailingIdx];
        trailingY = inReal1[{ let _v = trailingIdx; trailingIdx += 1; _v }];
        tempReal = (sumX2 - sumX * sumX / ((optInTimePeriod) as f64)) * (sumY2 - sumY * sumY / ((optInTimePeriod) as f64));
        if !((tempReal) < 1e-14) {
            outReal[0] = (sumXY - sumX * sumY / ((optInTimePeriod) as f64)) / (tempReal).sqrt();
        } else {
            outReal[0] = 0.0;
        }
        outIdx = 1;
        while today <= endIdx {
            sumX -= trailingX;
            sumX2 -= trailingX * trailingX;
            sumXY -= trailingX * trailingY;
            sumY -= trailingY;
            sumY2 -= trailingY * trailingY;
            x = inReal0[today];
            sumX += x;
            sumX2 += x * x;
            y = inReal1[{ let _v = today; today += 1; _v }];
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
            trailingX = inReal0[trailingIdx];
            trailingY = inReal1[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            tempReal = (sumX2 - sumX * sumX / ((optInTimePeriod) as f64)) * (sumY2 - sumY * sumY / ((optInTimePeriod) as f64));
            if !((tempReal) < 1e-14) {
                outReal[outIdx] = (sumXY - sumX * sumY / ((optInTimePeriod) as f64)) / (tempReal).sqrt();
                outIdx += 1;
            } else {
                outReal[outIdx] = 0.0;
                outIdx += 1;
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn correl_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal0: &[f64],
        inReal1: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut sumXY: f64 = 0.0_f64;
        let mut sumX: f64 = 0.0_f64;
        let mut sumY: f64 = 0.0_f64;
        let mut sumX2: f64 = 0.0_f64;
        let mut sumY2: f64 = 0.0_f64;
        let mut x: f64 = 0.0_f64;
        let mut y: f64 = 0.0_f64;
        let mut trailingX: f64 = 0.0_f64;
        let mut trailingY: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal0.len());
        assert!(endIdx < inReal1.len());
        assert!(endIdx - startIdx < outReal.len());
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        trailingIdx = startIdx - lookbackTotal;
        sumY2 = 0.0;
        sumX2 = sumY2;
        sumY = sumX2;
        sumX = sumY;
        sumXY = sumX;
        for today in (trailingIdx as usize)..(startIdx as usize) + 1 {
            x = *inReal0.as_ptr().add(today);
            sumX += x;
            sumX2 += x * x;
            y = *inReal1.as_ptr().add(today);
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
        }
        today = (startIdx as usize) + 1;
        trailingX = *inReal0.as_ptr().add(trailingIdx);
        trailingY = *inReal1.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
        tempReal = (sumX2 - sumX * sumX / ((optInTimePeriod) as f64)) * (sumY2 - sumY * sumY / ((optInTimePeriod) as f64));
        if !((tempReal) < 1e-14) {
            *outReal.as_mut_ptr().add(0) = (sumXY - sumX * sumY / ((optInTimePeriod) as f64)) / (tempReal).sqrt();
        } else {
            *outReal.as_mut_ptr().add(0) = 0.0;
        }
        outIdx = 1;
        while today <= endIdx {
            sumX -= trailingX;
            sumX2 -= trailingX * trailingX;
            sumXY -= trailingX * trailingY;
            sumY -= trailingY;
            sumY2 -= trailingY * trailingY;
            x = *inReal0.as_ptr().add(today);
            sumX += x;
            sumX2 += x * x;
            y = *inReal1.as_ptr().add({ let _v = today; today += 1; _v });
            sumXY += x * y;
            sumY += y;
            sumY2 += y * y;
            trailingX = *inReal0.as_ptr().add(trailingIdx);
            trailingY = *inReal1.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            tempReal = (sumX2 - sumX * sumX / ((optInTimePeriod) as f64)) * (sumY2 - sumY * sumY / ((optInTimePeriod) as f64));
            if !((tempReal) < 1e-14) {
                *outReal.as_mut_ptr().add(outIdx) = (sumXY - sumX * sumY / ((optInTimePeriod) as f64)) / (tempReal).sqrt();
                outIdx += 1;
            } else {
                *outReal.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
