/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::dema`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    #[inline]
    pub fn dema_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (self.ema_lookback(optInTimePeriod) * 2) as usize;
    }
    /// Double Exponential Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn dema(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut firstEMA: Vec<f64> = Vec::new();
        let mut secondEMA: Vec<f64> = Vec::new();
        let mut firstEMABegIdx: usize = 0_usize;
        let mut firstEMANbElement: usize = 0_usize;
        let mut secondEMABegIdx: usize = 0_usize;
        let mut secondEMANbElement: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut firstEMAIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackEMA: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        (*outNBElement) = 0;
        (*outBegIdx) = 0;
        lookbackEMA = self.ema_lookback(optInTimePeriod);
        lookbackTotal = lookbackEMA * 2;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        if inReal == outReal {
            firstEMA = outReal.to_vec();
        } else {
            tempInt = lookbackTotal + (endIdx - startIdx) + 1;
            firstEMA = vec![0.0_f64; (tempInt * 1) as usize];
        }
        retCode = self.ema_unguarded(startIdx - lookbackEMA, endIdx, inReal, optInTimePeriod, &mut firstEMABegIdx, &mut firstEMANbElement, &mut firstEMA[..]);
        if retCode != RetCode::Success || firstEMANbElement == 0 {
            if firstEMA != outReal {
            }
            return retCode;
        }
        secondEMA = vec![0.0_f64; (firstEMANbElement * 1) as usize];
        retCode = self.ema_unguarded(0, firstEMANbElement - 1, &firstEMA, optInTimePeriod, &mut secondEMABegIdx, &mut secondEMANbElement, &mut secondEMA[..]);
        if retCode != RetCode::Success || secondEMANbElement == 0 {
            if firstEMA != outReal {
            }
            return retCode;
        }
        firstEMAIdx = secondEMABegIdx;
        outIdx = 0;
        while outIdx < secondEMANbElement {
            outReal[outIdx] = ((2.0 * firstEMA[{ let _v = firstEMAIdx; firstEMAIdx += 1; _v }] - secondEMA[outIdx]) as f64);
            outIdx += 1;
        }
        if firstEMA != outReal {
        }
        (*outBegIdx) = firstEMABegIdx + secondEMABegIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn dema_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut firstEMA: Vec<f64> = Vec::new();
        let mut secondEMA: Vec<f64> = Vec::new();
        let mut firstEMABegIdx: usize = 0_usize;
        let mut firstEMANbElement: usize = 0_usize;
        let mut secondEMABegIdx: usize = 0_usize;
        let mut secondEMANbElement: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut firstEMAIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackEMA: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        (*outNBElement) = 0;
        (*outBegIdx) = 0;
        lookbackEMA = self.ema_lookback(optInTimePeriod);
        lookbackTotal = lookbackEMA * 2;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        if inReal == outReal {
            firstEMA = outReal.to_vec();
        } else {
            tempInt = lookbackTotal + (endIdx - startIdx) + 1;
            firstEMA = vec![0.0_f64; (tempInt * 1) as usize];
        }
        retCode = self.ema_unguarded(startIdx - lookbackEMA, endIdx, inReal, optInTimePeriod, &mut firstEMABegIdx, &mut firstEMANbElement, &mut firstEMA[..]);
        if retCode != RetCode::Success || firstEMANbElement == 0 {
            if firstEMA != outReal {
            }
            return retCode;
        }
        secondEMA = vec![0.0_f64; (firstEMANbElement * 1) as usize];
        retCode = self.ema_unguarded(0, firstEMANbElement - 1, &firstEMA, optInTimePeriod, &mut secondEMABegIdx, &mut secondEMANbElement, &mut secondEMA[..]);
        if retCode != RetCode::Success || secondEMANbElement == 0 {
            if firstEMA != outReal {
            }
            return retCode;
        }
        firstEMAIdx = secondEMABegIdx;
        outIdx = 0;
        while outIdx < secondEMANbElement {
            *outReal.as_mut_ptr().add(outIdx) = ((2.0 * *firstEMA.as_ptr().add({ let _v = firstEMAIdx; firstEMAIdx += 1; _v }) - *secondEMA.as_ptr().add(outIdx)) as f64);
            outIdx += 1;
        }
        if firstEMA != outReal {
        }
        (*outBegIdx) = firstEMABegIdx + secondEMABegIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
