/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::kama`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    #[inline]
    pub fn kama_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod + self.unstable_period[FuncUnstId::Kama as usize]) as usize;
    }
    /// Kaufman Adaptive Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn kama(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut constMax: f64 = 0.0_f64;
        let mut constDiff: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut tempReal2: f64 = 0.0_f64;
        let mut sumROC1: f64 = 0.0_f64;
        let mut periodROC: f64 = 0.0_f64;
        let mut prevKAMA: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut trailingValue: f64 = 0.0_f64;
        constMax = 2.0 / (30.0 + 1.0);
        constDiff = 2.0 / (2.0 + 1.0) - constMax;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Kama as usize]) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        sumROC1 = 0.0;
        today = startIdx - lookbackTotal;
        trailingIdx = today;
        i = (optInTimePeriod) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            tempReal = inReal[{ let _v = today; today += 1; _v }];
            tempReal -= inReal[today];
            sumROC1 += (tempReal).abs();
        }
        prevKAMA = inReal[today - 1];
        tempReal = inReal[today];
        tempReal2 = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
        periodROC = tempReal - tempReal2;
        trailingValue = tempReal2;
        if sumROC1 <= periodROC || (sumROC1).abs() < 1e-14 {
            tempReal = 1.0;
        } else {
            tempReal = (periodROC / sumROC1).abs();
        }
        tempReal = (tempReal as f64).mul_add(constDiff, constMax);
        tempReal *= tempReal;
        prevKAMA = (inReal[{ let _v = today; today += 1; _v }] - prevKAMA as f64).mul_add(tempReal, prevKAMA);
        while today <= startIdx {
            tempReal = inReal[today];
            tempReal2 = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            periodROC = tempReal - tempReal2;
            sumROC1 -= (trailingValue - tempReal2).abs();
            sumROC1 += (tempReal - inReal[today - 1]).abs();
            trailingValue = tempReal2;
            if sumROC1 <= periodROC || (sumROC1).abs() < 1e-14 {
                tempReal = 1.0;
            } else {
                tempReal = (periodROC / sumROC1).abs();
            }
            tempReal = (tempReal as f64).mul_add(constDiff, constMax);
            tempReal *= tempReal;
            prevKAMA = (inReal[{ let _v = today; today += 1; _v }] - prevKAMA as f64).mul_add(tempReal, prevKAMA);
        }
        outReal[0] = prevKAMA;
        outIdx = 1;
        (*outBegIdx) = today - 1;
        while today <= endIdx {
            tempReal = inReal[today];
            tempReal2 = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            periodROC = tempReal - tempReal2;
            sumROC1 -= (trailingValue - tempReal2).abs();
            sumROC1 += (tempReal - inReal[today - 1]).abs();
            trailingValue = tempReal2;
            if sumROC1 <= periodROC || (sumROC1).abs() < 1e-14 {
                tempReal = 1.0;
            } else {
                tempReal = (periodROC / sumROC1).abs();
            }
            tempReal = (tempReal as f64).mul_add(constDiff, constMax);
            tempReal *= tempReal;
            prevKAMA = (inReal[{ let _v = today; today += 1; _v }] - prevKAMA as f64).mul_add(tempReal, prevKAMA);
            outReal[outIdx] = prevKAMA;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn kama_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut constMax: f64 = 0.0_f64;
        let mut constDiff: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut tempReal2: f64 = 0.0_f64;
        let mut sumROC1: f64 = 0.0_f64;
        let mut periodROC: f64 = 0.0_f64;
        let mut prevKAMA: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut trailingValue: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        constMax = 2.0 / (30.0 + 1.0);
        constDiff = 2.0 / (2.0 + 1.0) - constMax;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Kama as usize]) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        sumROC1 = 0.0;
        today = startIdx - lookbackTotal;
        trailingIdx = today;
        i = (optInTimePeriod) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            tempReal = *inReal.as_ptr().add({ let _v = today; today += 1; _v });
            tempReal -= *inReal.as_ptr().add(today);
            sumROC1 += (tempReal).abs();
        }
        prevKAMA = *inReal.as_ptr().add(today - 1);
        tempReal = *inReal.as_ptr().add(today);
        tempReal2 = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
        periodROC = tempReal - tempReal2;
        trailingValue = tempReal2;
        if sumROC1 <= periodROC || (sumROC1).abs() < 1e-14 {
            tempReal = 1.0;
        } else {
            tempReal = (periodROC / sumROC1).abs();
        }
        tempReal = (tempReal as f64).mul_add(constDiff, constMax);
        tempReal *= tempReal;
        prevKAMA = (*inReal.as_ptr().add({ let _v = today; today += 1; _v }) - prevKAMA as f64).mul_add(tempReal, prevKAMA);
        while today <= startIdx {
            tempReal = *inReal.as_ptr().add(today);
            tempReal2 = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            periodROC = tempReal - tempReal2;
            sumROC1 -= (trailingValue - tempReal2).abs();
            sumROC1 += (tempReal - *inReal.as_ptr().add(today - 1)).abs();
            trailingValue = tempReal2;
            if sumROC1 <= periodROC || (sumROC1).abs() < 1e-14 {
                tempReal = 1.0;
            } else {
                tempReal = (periodROC / sumROC1).abs();
            }
            tempReal = (tempReal as f64).mul_add(constDiff, constMax);
            tempReal *= tempReal;
            prevKAMA = (*inReal.as_ptr().add({ let _v = today; today += 1; _v }) - prevKAMA as f64).mul_add(tempReal, prevKAMA);
        }
        *outReal.as_mut_ptr().add(0) = prevKAMA;
        outIdx = 1;
        (*outBegIdx) = today - 1;
        while today <= endIdx {
            tempReal = *inReal.as_ptr().add(today);
            tempReal2 = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            periodROC = tempReal - tempReal2;
            sumROC1 -= (trailingValue - tempReal2).abs();
            sumROC1 += (tempReal - *inReal.as_ptr().add(today - 1)).abs();
            trailingValue = tempReal2;
            if sumROC1 <= periodROC || (sumROC1).abs() < 1e-14 {
                tempReal = 1.0;
            } else {
                tempReal = (periodROC / sumROC1).abs();
            }
            tempReal = (tempReal as f64).mul_add(constDiff, constMax);
            tempReal *= tempReal;
            prevKAMA = (*inReal.as_ptr().add({ let _v = today; today += 1; _v }) - prevKAMA as f64).mul_add(tempReal, prevKAMA);
            *outReal.as_mut_ptr().add(outIdx) = prevKAMA;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
