/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::ma`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    #[inline]
    pub fn ma_lookback(&self, mut optInTimePeriod: i32, mut optInMAType: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        let mut retValue: usize = 0_usize;
        if optInTimePeriod <= 1 {
            return (0) as usize;
        }
        match optInMAType {
            0 => {
                retValue = self.sma_lookback(optInTimePeriod);
            }
            1 => {
                retValue = self.ema_lookback(optInTimePeriod);
            }
            2 => {
                retValue = self.wma_lookback(optInTimePeriod);
            }
            3 => {
                retValue = self.dema_lookback(optInTimePeriod);
            }
            4 => {
                retValue = self.tema_lookback(optInTimePeriod);
            }
            5 => {
                retValue = self.trima_lookback(optInTimePeriod);
            }
            6 => {
                retValue = self.kama_lookback(optInTimePeriod);
            }
            7 => {
                retValue = self.mama_lookback(0.5, 0.05);
            }
            8 => {
                retValue = self.t3_lookback(optInTimePeriod, 0.7);
            }
            _ => {
                retValue = 0;
            }
        }
        return retValue;
    }
    /// Moving average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn ma(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut dummyBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut nbElement: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        if optInTimePeriod == 1 {
            nbElement = endIdx - startIdx + 1;
            (*outNBElement) = nbElement;
            // for( todayIdx = startIdx, outIdx = 0; outIdx < nbElement; outIdx += 1, todayIdx += 1 )
            todayIdx = startIdx;
            outIdx = 0;
            while outIdx < nbElement {
                outReal[outIdx] = ((inReal[todayIdx]) as f64);
                outIdx += 1;
                todayIdx += 1;
            }
            (*outBegIdx) = startIdx;
            return RetCode::Success;
        }
        match optInMAType {
            0 => {
                retCode = self.sma_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            1 => {
                retCode = self.ema_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            2 => {
                retCode = self.wma_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            3 => {
                retCode = self.dema_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            4 => {
                retCode = self.tema_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            5 => {
                retCode = self.trima_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            6 => {
                retCode = self.kama_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            7 => {
                dummyBuffer = vec![0.0_f64; ((endIdx - startIdx + 1) * 1) as usize];
                retCode = self.mama_unguarded(startIdx, endIdx, inReal, 0.5, 0.05, outBegIdx, outNBElement, outReal, &mut dummyBuffer[..]);
            }
            8 => {
                retCode = self.t3_unguarded(startIdx, endIdx, inReal, optInTimePeriod, 0.7, outBegIdx, outNBElement, outReal);
            }
            _ => {
                retCode = RetCode::BadParam;
            }
        }
        return retCode;
    }
    #[inline]
    pub fn ma_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut dummyBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut nbElement: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        if optInTimePeriod == 1 {
            nbElement = endIdx - startIdx + 1;
            (*outNBElement) = nbElement;
            // for( todayIdx = startIdx, outIdx = 0; outIdx < nbElement; outIdx += 1, todayIdx += 1 )
            todayIdx = startIdx;
            outIdx = 0;
            while outIdx < nbElement {
                *outReal.as_mut_ptr().add(outIdx) = ((*inReal.as_ptr().add(todayIdx)) as f64);
                outIdx += 1;
                todayIdx += 1;
            }
            (*outBegIdx) = startIdx;
            return RetCode::Success;
        }
        match optInMAType {
            0 => {
                retCode = self.sma_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            1 => {
                retCode = self.ema_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            2 => {
                retCode = self.wma_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            3 => {
                retCode = self.dema_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            4 => {
                retCode = self.tema_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            5 => {
                retCode = self.trima_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            6 => {
                retCode = self.kama_unguarded(startIdx, endIdx, inReal, optInTimePeriod, outBegIdx, outNBElement, outReal);
            }
            7 => {
                dummyBuffer = vec![0.0_f64; ((endIdx - startIdx + 1) * 1) as usize];
                retCode = self.mama_unguarded(startIdx, endIdx, inReal, 0.5, 0.05, outBegIdx, outNBElement, outReal, &mut dummyBuffer[..]);
            }
            8 => {
                retCode = self.t3_unguarded(startIdx, endIdx, inReal, optInTimePeriod, 0.7, outBegIdx, outNBElement, outReal);
            }
            _ => {
                retCode = RetCode::BadParam;
            }
        }
        return retCode;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
