/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::macdext`].
    ///
    /// # Arguments
    ///
    /// * `optInFastPeriod` - Number of period (default: 12, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 26, range: 2..=100000)
    /// * `optInSignalPeriod` - Number of period (default: 9, range: 1..=100000)
    #[inline]
    pub fn macdext_lookback(&self, mut optInFastPeriod: i32, mut optInFastMAType: i32, mut optInSlowPeriod: i32, mut optInSlowMAType: i32, mut optInSignalPeriod: i32, mut optInSignalMAType: i32) -> usize {
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSignalPeriod) as i32) == (i32::MIN) {
            optInSignalPeriod = 9;
        } else if (((optInSignalPeriod) as i32) < 1) || (((optInSignalPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        let mut tempInteger: usize = 0_usize;
        let mut lookbackLargest: usize = 0_usize;
        lookbackLargest = self.ma_lookback(optInFastPeriod, optInFastMAType);
        tempInteger = self.ma_lookback(optInSlowPeriod, optInSlowMAType);
        if tempInteger > lookbackLargest {
            lookbackLargest = tempInteger;
        }
        return (lookbackLargest + self.ma_lookback(optInSignalPeriod, optInSignalMAType)) as usize;
    }
    /// MACD with controllable MA type
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInFastPeriod` - Number of period (default: 12, range: 2..=100000)
    /// * `optInSlowPeriod` - Number of period (default: 26, range: 2..=100000)
    /// * `optInSignalPeriod` - Number of period (default: 9, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outMACD` - Output values
    /// * `outMACDSignal` - Output values
    /// * `outMACDHist` - Output values
    pub fn macdext(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInFastPeriod: i32,
        mut optInFastMAType: i32,
        mut optInSlowPeriod: i32,
        mut optInSlowMAType: i32,
        mut optInSignalPeriod: i32,
        mut optInSignalMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outMACD: &mut [f64],
        outMACDSignal: &mut [f64],
        outMACDHist: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastPeriod) as i32) == (i32::MIN) {
            optInFastPeriod = 12;
        } else if (((optInFastPeriod) as i32) < 2) || (((optInFastPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowPeriod) as i32) == (i32::MIN) {
            optInSlowPeriod = 26;
        } else if (((optInSlowPeriod) as i32) < 2) || (((optInSlowPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSignalPeriod) as i32) == (i32::MIN) {
            optInSignalPeriod = 9;
        } else if (((optInSignalPeriod) as i32) < 1) || (((optInSignalPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut slowMABuffer: Vec<f64> = Vec::new();
        let mut fastMABuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut tempInteger: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement2: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackSignal: usize = 0_usize;
        let mut lookbackLargest: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut tempMAType: usize = 0_usize;
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = (optInSlowPeriod) as usize;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = (tempInteger) as i32;
            tempMAType = (optInSlowMAType) as usize;
            optInSlowMAType = optInFastMAType;
            optInFastMAType = (tempMAType) as i32;
        }
        lookbackLargest = self.ma_lookback(optInFastPeriod, optInFastMAType);
        tempInteger = self.ma_lookback(optInSlowPeriod, optInSlowMAType);
        if tempInteger > lookbackLargest {
            lookbackLargest = tempInteger;
        }
        lookbackSignal = self.ma_lookback(optInSignalPeriod, optInSignalMAType);
        lookbackTotal = lookbackSignal + lookbackLargest;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        tempInteger = endIdx - startIdx + 1 + lookbackSignal;
        fastMABuffer = vec![0.0_f64; (tempInteger * 1) as usize];
        slowMABuffer = vec![0.0_f64; (tempInteger * 1) as usize];
        tempInteger = startIdx - lookbackSignal;
        retCode = self.ma_unguarded(tempInteger, endIdx, inReal, optInSlowPeriod, optInSlowMAType, &mut outBegIdx1, &mut outNbElement1, &mut slowMABuffer[..]);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ma_unguarded(tempInteger, endIdx, inReal, optInFastPeriod, optInFastMAType, &mut outBegIdx2, &mut outNbElement2, &mut fastMABuffer[..]);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        if outBegIdx1 != tempInteger || outBegIdx2 != tempInteger || outNbElement1 != outNbElement2 || outNbElement1 != endIdx - startIdx + 1 + lookbackSignal {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::BadParam;
        }
        // for( i = 0; i < outNbElement1; i += 1 )
        i = 0;
        while i < outNbElement1 {
            fastMABuffer[i] = fastMABuffer[i] - slowMABuffer[i];
            i += 1;
        }
        {
            let _n = ((endIdx - startIdx + 1) * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackSignal) as usize;
            outMACD[_di.._di + _n].copy_from_slice(&fastMABuffer[_si.._si + _n]);
        };
        retCode = self.ma_unguarded(0, outNbElement1 - 1, &fastMABuffer, optInSignalPeriod, optInSignalMAType, &mut outBegIdx2, &mut outNbElement2, outMACDSignal);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        // for( i = 0; i < outNbElement2; i += 1 )
        i = 0;
        while i < outNbElement2 {
            outMACDHist[i] = ((outMACD[i] - outMACDSignal[i]) as f64);
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outNbElement2;
        return RetCode::Success;
    }
    #[inline]
    pub fn macdext_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInFastPeriod: i32,
        mut optInFastMAType: i32,
        mut optInSlowPeriod: i32,
        mut optInSlowMAType: i32,
        mut optInSignalPeriod: i32,
        mut optInSignalMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outMACD: &mut [f64],
        outMACDSignal: &mut [f64],
        outMACDHist: &mut [f64],
    ) -> RetCode {
        let mut slowMABuffer: Vec<f64> = Vec::new();
        let mut fastMABuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut tempInteger: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement2: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackSignal: usize = 0_usize;
        let mut lookbackLargest: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut tempMAType: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outMACD.len());
        assert!(endIdx - startIdx < outMACDSignal.len());
        assert!(endIdx - startIdx < outMACDHist.len());
        if optInSlowPeriod < optInFastPeriod {
            tempInteger = (optInSlowPeriod) as usize;
            optInSlowPeriod = optInFastPeriod;
            optInFastPeriod = (tempInteger) as i32;
            tempMAType = (optInSlowMAType) as usize;
            optInSlowMAType = optInFastMAType;
            optInFastMAType = (tempMAType) as i32;
        }
        lookbackLargest = self.ma_lookback(optInFastPeriod, optInFastMAType);
        tempInteger = self.ma_lookback(optInSlowPeriod, optInSlowMAType);
        if tempInteger > lookbackLargest {
            lookbackLargest = tempInteger;
        }
        lookbackSignal = self.ma_lookback(optInSignalPeriod, optInSignalMAType);
        lookbackTotal = lookbackSignal + lookbackLargest;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        tempInteger = endIdx - startIdx + 1 + lookbackSignal;
        fastMABuffer = vec![0.0_f64; (tempInteger * 1) as usize];
        slowMABuffer = vec![0.0_f64; (tempInteger * 1) as usize];
        tempInteger = startIdx - lookbackSignal;
        retCode = self.ma_unguarded(tempInteger, endIdx, inReal, optInSlowPeriod, optInSlowMAType, &mut outBegIdx1, &mut outNbElement1, &mut slowMABuffer[..]);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ma_unguarded(tempInteger, endIdx, inReal, optInFastPeriod, optInFastMAType, &mut outBegIdx2, &mut outNbElement2, &mut fastMABuffer[..]);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        if outBegIdx1 != tempInteger || outBegIdx2 != tempInteger || outNbElement1 != outNbElement2 || outNbElement1 != endIdx - startIdx + 1 + lookbackSignal {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::BadParam;
        }
        // for( i = 0; i < outNbElement1; i += 1 )
        i = 0;
        while i < outNbElement1 {
            *fastMABuffer.as_mut_ptr().add(i) = *fastMABuffer.as_ptr().add(i) - *slowMABuffer.as_ptr().add(i);
            i += 1;
        }
        {
            let _n = ((endIdx - startIdx + 1) * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackSignal) as usize;
            outMACD[_di.._di + _n].copy_from_slice(&fastMABuffer[_si.._si + _n]);
        };
        retCode = self.ma_unguarded(0, outNbElement1 - 1, &fastMABuffer, optInSignalPeriod, optInSignalMAType, &mut outBegIdx2, &mut outNbElement2, outMACDSignal);
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        // for( i = 0; i < outNbElement2; i += 1 )
        i = 0;
        while i < outNbElement2 {
            *outMACDHist.as_mut_ptr().add(i) = ((*outMACD.as_ptr().add(i) - *outMACDSignal.as_ptr().add(i)) as f64);
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outNbElement2;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
