/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::mavp`].
    ///
    /// # Arguments
    ///
    /// * `optInMinPeriod` - Number of period (default: 2, range: 2..=100000)
    /// * `optInMaxPeriod` - Number of period (default: 30, range: 2..=100000)
    #[inline]
    pub fn mavp_lookback(&self, mut optInMinPeriod: i32, mut optInMaxPeriod: i32, mut optInMAType: i32) -> usize {
        if ((optInMinPeriod) as i32) == (i32::MIN) {
            optInMinPeriod = 2;
        } else if (((optInMinPeriod) as i32) < 2) || (((optInMinPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInMaxPeriod) as i32) == (i32::MIN) {
            optInMaxPeriod = 30;
        } else if (((optInMaxPeriod) as i32) < 2) || (((optInMaxPeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return self.ma_lookback(optInMaxPeriod, optInMAType);
    }
    /// Moving average with variable period
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `inPeriods` - Input price series
    /// * `optInMinPeriod` - Number of period (default: 2, range: 2..=100000)
    /// * `optInMaxPeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn mavp(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        inPeriods: &[f64],
        mut optInMinPeriod: i32,
        mut optInMaxPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInMinPeriod) as i32) == (i32::MIN) {
            optInMinPeriod = 2;
        } else if (((optInMinPeriod) as i32) < 2) || (((optInMinPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInMaxPeriod) as i32) == (i32::MIN) {
            optInMaxPeriod = 30;
        } else if (((optInMaxPeriod) as i32) < 2) || (((optInMaxPeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outputSize: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut curPeriod: usize = 0_usize;
        let mut localPeriodArray: Vec<i32> = Vec::new();
        let mut localOutputArray: Vec<f64> = Vec::new();
        let mut localBegIdx: usize = 0_usize;
        let mut localNbElement: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        lookbackTotal = self.ma_lookback(optInMaxPeriod, optInMAType);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if lookbackTotal > startIdx {
            tempInt = lookbackTotal;
        } else {
            tempInt = startIdx;
        }
        if tempInt > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - tempInt + 1;
        localOutputArray = vec![0.0_f64; (outputSize * 1) as usize];
        localPeriodArray = vec![0_i32; (outputSize * 1) as usize];
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            tempInt = ((inPeriods[startIdx + i]) as usize) as usize;
            if tempInt < (optInMinPeriod) as usize {
                tempInt = (optInMinPeriod) as usize;
            } else if tempInt > (optInMaxPeriod) as usize {
                tempInt = (optInMaxPeriod) as usize;
            }
            localPeriodArray[i] = (tempInt) as i32;
            i += 1;
        }
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            curPeriod = (localPeriodArray[i]) as usize;
            if curPeriod != 0 {
                retCode = self.ma_unguarded(startIdx, endIdx, inReal, (curPeriod) as i32, optInMAType, &mut localBegIdx, &mut localNbElement, &mut localOutputArray[..]);
                if retCode != RetCode::Success {
                    (*outBegIdx) = 0;
                    (*outNBElement) = 0;
                    return retCode;
                }
                outReal[i] = ((localOutputArray[i]) as f64);
                // for( j = i + 1; j < outputSize; j += 1 )
                j = i + 1;
                while j < outputSize {
                    if (localPeriodArray[j]) as usize == curPeriod {
                        localPeriodArray[j] = 0;
                        outReal[j] = ((localOutputArray[j]) as f64);
                    }
                    j += 1;
                }
            }
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
    }
    #[inline]
    pub fn mavp_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        inPeriods: &[f64],
        mut optInMinPeriod: i32,
        mut optInMaxPeriod: i32,
        mut optInMAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut i: usize = 0_usize;
        let mut j: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outputSize: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut curPeriod: usize = 0_usize;
        let mut localPeriodArray: Vec<i32> = Vec::new();
        let mut localOutputArray: Vec<f64> = Vec::new();
        let mut localBegIdx: usize = 0_usize;
        let mut localNbElement: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx < inPeriods.len());
        assert!(endIdx - startIdx < outReal.len());
        lookbackTotal = self.ma_lookback(optInMaxPeriod, optInMAType);
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        if lookbackTotal > startIdx {
            tempInt = lookbackTotal;
        } else {
            tempInt = startIdx;
        }
        if tempInt > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outputSize = endIdx - tempInt + 1;
        localOutputArray = vec![0.0_f64; (outputSize * 1) as usize];
        localPeriodArray = vec![0_i32; (outputSize * 1) as usize];
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            tempInt = ((*inPeriods.as_ptr().add(startIdx + i)) as usize) as usize;
            if tempInt < (optInMinPeriod) as usize {
                tempInt = (optInMinPeriod) as usize;
            } else if tempInt > (optInMaxPeriod) as usize {
                tempInt = (optInMaxPeriod) as usize;
            }
            *localPeriodArray.as_mut_ptr().add(i) = (tempInt) as i32;
            i += 1;
        }
        // for( i = 0; i < outputSize; i += 1 )
        i = 0;
        while i < outputSize {
            curPeriod = (*localPeriodArray.as_ptr().add(i)) as usize;
            if curPeriod != 0 {
                retCode = self.ma_unguarded(startIdx, endIdx, inReal, (curPeriod) as i32, optInMAType, &mut localBegIdx, &mut localNbElement, &mut localOutputArray[..]);
                if retCode != RetCode::Success {
                    (*outBegIdx) = 0;
                    (*outNBElement) = 0;
                    return retCode;
                }
                *outReal.as_mut_ptr().add(i) = ((*localOutputArray.as_ptr().add(i)) as f64);
                // for( j = i + 1; j < outputSize; j += 1 )
                j = i + 1;
                while j < outputSize {
                    if (*localPeriodArray.as_ptr().add(j)) as usize == curPeriod {
                        *localPeriodArray.as_mut_ptr().add(j) = 0;
                        *outReal.as_mut_ptr().add(j) = ((*localOutputArray.as_ptr().add(j)) as f64);
                    }
                    j += 1;
                }
            }
            i += 1;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outputSize;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
