/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::mfi`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    #[inline]
    pub fn mfi_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod + self.unstable_period[FuncUnstId::Mfi as usize]) as usize;
    }
    /// Money Flow Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `inVolume` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn mfi(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut posSumMF: f64 = 0.0_f64;
        let mut negSumMF: f64 = 0.0_f64;
        let mut prevValue: f64 = 0.0_f64;
        let mut tempValue1: f64 = 0.0_f64;
        let mut tempValue2: f64 = 0.0_f64;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut mflow_positive: [f64; 50 as usize] = [0.0_f64; 50 as usize];
        let mut mflow_negative: [f64; 50 as usize] = [0.0_f64; 50 as usize];
        let mut mflow_Idx: usize = 0_usize;
        mflow_Idx = 0;
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_positive[_si.._si + _n].fill(0.0_f64);
        };
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_negative[_si.._si + _n].fill(0.0_f64);
        };
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Mfi as usize]) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx - lookbackTotal;
        prevValue = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
        posSumMF = 0.0;
        negSumMF = 0.0;
        today += 1;
        // for( i = (optInTimePeriod) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod) as usize;
        while i > 0 {
            tempValue1 = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= inVolume[{ let _v = today; today += 1; _v }];
            if tempValue2 < 0_f64 {
                mflow_negative[mflow_Idx] = tempValue1;
                negSumMF += tempValue1;
                mflow_positive[mflow_Idx] = 0.0;
            } else if tempValue2 > 0_f64 {
                mflow_positive[mflow_Idx] = tempValue1;
                posSumMF += tempValue1;
                mflow_negative[mflow_Idx] = 0.0;
            } else {
                mflow_positive[mflow_Idx] = 0.0;
                mflow_negative[mflow_Idx] = 0.0;
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            i -= 1;
        }
        if today > startIdx {
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < 1.0 {
                outReal[outIdx] = 0.0;
                outIdx += 1;
            } else {
                outReal[outIdx] = 100.0 * (posSumMF / tempValue1);
                outIdx += 1;
            }
        } else {
            while today < startIdx {
                posSumMF -= mflow_positive[mflow_Idx];
                negSumMF -= mflow_negative[mflow_Idx];
                tempValue1 = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                tempValue1 *= inVolume[{ let _v = today; today += 1; _v }];
                if tempValue2 < 0_f64 {
                    mflow_negative[mflow_Idx] = tempValue1;
                    negSumMF += tempValue1;
                    mflow_positive[mflow_Idx] = 0.0;
                } else if tempValue2 > 0_f64 {
                    mflow_positive[mflow_Idx] = tempValue1;
                    posSumMF += tempValue1;
                    mflow_negative[mflow_Idx] = 0.0;
                } else {
                    mflow_positive[mflow_Idx] = 0.0;
                    mflow_negative[mflow_Idx] = 0.0;
                }
                mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            }
        }
        while today <= endIdx {
            posSumMF -= mflow_positive[mflow_Idx];
            negSumMF -= mflow_negative[mflow_Idx];
            tempValue1 = (inHigh[today] + inLow[today] + inClose[today]) / 3.0;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= inVolume[{ let _v = today; today += 1; _v }];
            if tempValue2 < 0_f64 {
                mflow_negative[mflow_Idx] = tempValue1;
                negSumMF += tempValue1;
                mflow_positive[mflow_Idx] = 0.0;
            } else if tempValue2 > 0_f64 {
                mflow_positive[mflow_Idx] = tempValue1;
                posSumMF += tempValue1;
                mflow_negative[mflow_Idx] = 0.0;
            } else {
                mflow_positive[mflow_Idx] = 0.0;
                mflow_negative[mflow_Idx] = 0.0;
            }
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < 1.0 {
                outReal[outIdx] = 0.0;
                outIdx += 1;
            } else {
                outReal[outIdx] = 100.0 * (posSumMF / tempValue1);
                outIdx += 1;
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn mfi_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        inVolume: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut posSumMF: f64 = 0.0_f64;
        let mut negSumMF: f64 = 0.0_f64;
        let mut prevValue: f64 = 0.0_f64;
        let mut tempValue1: f64 = 0.0_f64;
        let mut tempValue2: f64 = 0.0_f64;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut mflow_positive: [f64; 50 as usize] = [0.0_f64; 50 as usize];
        let mut mflow_negative: [f64; 50 as usize] = [0.0_f64; 50 as usize];
        let mut mflow_Idx: usize = 0_usize;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx < inVolume.len());
        assert!(endIdx - startIdx < outReal.len());
        mflow_Idx = 0;
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_positive[_si.._si + _n].fill(0.0_f64);
        };
        {
            let _n = ((optInTimePeriod) as usize * 1) as usize;
            let _si = (0) as usize;
            mflow_negative[_si.._si + _n].fill(0.0_f64);
        };
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::Mfi as usize]) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx - lookbackTotal;
        prevValue = (*inHigh.as_ptr().add(today) + *inLow.as_ptr().add(today) + *inClose.as_ptr().add(today)) / 3.0;
        posSumMF = 0.0;
        negSumMF = 0.0;
        today += 1;
        // for( i = (optInTimePeriod) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod) as usize;
        while i > 0 {
            tempValue1 = (*inHigh.as_ptr().add(today) + *inLow.as_ptr().add(today) + *inClose.as_ptr().add(today)) / 3.0;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= *inVolume.as_ptr().add({ let _v = today; today += 1; _v });
            if tempValue2 < 0_f64 {
                *mflow_negative.as_mut_ptr().add(mflow_Idx) = tempValue1;
                negSumMF += tempValue1;
                *mflow_positive.as_mut_ptr().add(mflow_Idx) = 0.0;
            } else if tempValue2 > 0_f64 {
                *mflow_positive.as_mut_ptr().add(mflow_Idx) = tempValue1;
                posSumMF += tempValue1;
                *mflow_negative.as_mut_ptr().add(mflow_Idx) = 0.0;
            } else {
                *mflow_positive.as_mut_ptr().add(mflow_Idx) = 0.0;
                *mflow_negative.as_mut_ptr().add(mflow_Idx) = 0.0;
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            i -= 1;
        }
        if today > startIdx {
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < 1.0 {
                *outReal.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            } else {
                *outReal.as_mut_ptr().add(outIdx) = 100.0 * (posSumMF / tempValue1);
                outIdx += 1;
            }
        } else {
            while today < startIdx {
                posSumMF -= *mflow_positive.as_ptr().add(mflow_Idx);
                negSumMF -= *mflow_negative.as_ptr().add(mflow_Idx);
                tempValue1 = (*inHigh.as_ptr().add(today) + *inLow.as_ptr().add(today) + *inClose.as_ptr().add(today)) / 3.0;
                tempValue2 = tempValue1 - prevValue;
                prevValue = tempValue1;
                tempValue1 *= *inVolume.as_ptr().add({ let _v = today; today += 1; _v });
                if tempValue2 < 0_f64 {
                    *mflow_negative.as_mut_ptr().add(mflow_Idx) = tempValue1;
                    negSumMF += tempValue1;
                    *mflow_positive.as_mut_ptr().add(mflow_Idx) = 0.0;
                } else if tempValue2 > 0_f64 {
                    *mflow_positive.as_mut_ptr().add(mflow_Idx) = tempValue1;
                    posSumMF += tempValue1;
                    *mflow_negative.as_mut_ptr().add(mflow_Idx) = 0.0;
                } else {
                    *mflow_positive.as_mut_ptr().add(mflow_Idx) = 0.0;
                    *mflow_negative.as_mut_ptr().add(mflow_Idx) = 0.0;
                }
                mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
            }
        }
        while today <= endIdx {
            posSumMF -= *mflow_positive.as_ptr().add(mflow_Idx);
            negSumMF -= *mflow_negative.as_ptr().add(mflow_Idx);
            tempValue1 = (*inHigh.as_ptr().add(today) + *inLow.as_ptr().add(today) + *inClose.as_ptr().add(today)) / 3.0;
            tempValue2 = tempValue1 - prevValue;
            prevValue = tempValue1;
            tempValue1 *= *inVolume.as_ptr().add({ let _v = today; today += 1; _v });
            if tempValue2 < 0_f64 {
                *mflow_negative.as_mut_ptr().add(mflow_Idx) = tempValue1;
                negSumMF += tempValue1;
                *mflow_positive.as_mut_ptr().add(mflow_Idx) = 0.0;
            } else if tempValue2 > 0_f64 {
                *mflow_positive.as_mut_ptr().add(mflow_Idx) = tempValue1;
                posSumMF += tempValue1;
                *mflow_negative.as_mut_ptr().add(mflow_Idx) = 0.0;
            } else {
                *mflow_positive.as_mut_ptr().add(mflow_Idx) = 0.0;
                *mflow_negative.as_mut_ptr().add(mflow_Idx) = 0.0;
            }
            tempValue1 = posSumMF + negSumMF;
            if tempValue1 < 1.0 {
                *outReal.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            } else {
                *outReal.as_mut_ptr().add(outIdx) = 100.0 * (posSumMF / tempValue1);
                outIdx += 1;
            }
            mflow_Idx = (mflow_Idx + 1) % (optInTimePeriod) as usize;
        }
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
