/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::minus_dm`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    #[inline]
    pub fn minus_dm_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if optInTimePeriod > 1 {
            return (optInTimePeriod + self.unstable_period[FuncUnstId::MinusDM as usize] - 1) as usize;
        } else {
            return (1) as usize;
        }
    }
    /// Minus Directional Movement
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn minus_dm(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevHigh: f64 = 0.0_f64;
        let mut prevLow: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut prevMinusDM: f64 = 0.0_f64;
        let mut diffP: f64 = 0.0_f64;
        let mut diffM: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        if optInTimePeriod > 1 {
            lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::MinusDM as usize] - 1) as usize;
        } else {
            lookbackTotal = 1;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod <= 1 {
            (*outBegIdx) = startIdx;
            today = startIdx - 1;
            prevHigh = inHigh[today];
            prevLow = inLow[today];
            while today < endIdx {
                today += 1;
                tempReal = inHigh[today];
                diffP = tempReal - prevHigh;
                prevHigh = tempReal;
                tempReal = inLow[today];
                diffM = prevLow - tempReal;
                prevLow = tempReal;
                if diffM > 0_f64 && diffP < diffM {
                    outReal[outIdx] = diffM;
                    outIdx += 1;
                } else {
                    outReal[outIdx] = 0.0;
                    outIdx += 1;
                }
            }
            (*outNBElement) = outIdx;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        prevMinusDM = 0.0;
        today = startIdx - lookbackTotal;
        prevHigh = inHigh[today];
        prevLow = inLow[today];
        i = (optInTimePeriod - 1) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = inHigh[today];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[today];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0_f64 && diffP < diffM {
                prevMinusDM += diffM;
            }
        }
        i = (self.unstable_period[FuncUnstId::MinusDM as usize]) as usize;
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = inHigh[today];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[today];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0_f64 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64) + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64);
            }
        }
        outReal[0] = prevMinusDM;
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = inHigh[today];
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = inLow[today];
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0_f64 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64) + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64);
            }
            outReal[outIdx] = prevMinusDM;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn minus_dm_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevHigh: f64 = 0.0_f64;
        let mut prevLow: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut prevMinusDM: f64 = 0.0_f64;
        let mut diffP: f64 = 0.0_f64;
        let mut diffM: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx - startIdx < outReal.len());
        if optInTimePeriod > 1 {
            lookbackTotal = (optInTimePeriod + self.unstable_period[FuncUnstId::MinusDM as usize] - 1) as usize;
        } else {
            lookbackTotal = 1;
        }
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod <= 1 {
            (*outBegIdx) = startIdx;
            today = startIdx - 1;
            prevHigh = *inHigh.as_ptr().add(today);
            prevLow = *inLow.as_ptr().add(today);
            while today < endIdx {
                today += 1;
                tempReal = *inHigh.as_ptr().add(today);
                diffP = tempReal - prevHigh;
                prevHigh = tempReal;
                tempReal = *inLow.as_ptr().add(today);
                diffM = prevLow - tempReal;
                prevLow = tempReal;
                if diffM > 0_f64 && diffP < diffM {
                    *outReal.as_mut_ptr().add(outIdx) = diffM;
                    outIdx += 1;
                } else {
                    *outReal.as_mut_ptr().add(outIdx) = 0.0;
                    outIdx += 1;
                }
            }
            (*outNBElement) = outIdx;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        prevMinusDM = 0.0;
        today = startIdx - lookbackTotal;
        prevHigh = *inHigh.as_ptr().add(today);
        prevLow = *inLow.as_ptr().add(today);
        i = (optInTimePeriod - 1) as usize;
        while { let _v = i; i -= 1; _v } > 0 {
            today += 1;
            tempReal = *inHigh.as_ptr().add(today);
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = *inLow.as_ptr().add(today);
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0_f64 && diffP < diffM {
                prevMinusDM += diffM;
            }
        }
        i = (self.unstable_period[FuncUnstId::MinusDM as usize]) as usize;
        while { let _v = i; i -= 1; _v } != 0 {
            today += 1;
            tempReal = *inHigh.as_ptr().add(today);
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = *inLow.as_ptr().add(today);
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0_f64 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64) + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64);
            }
        }
        *outReal.as_mut_ptr().add(0) = prevMinusDM;
        outIdx = 1;
        while today < endIdx {
            today += 1;
            tempReal = *inHigh.as_ptr().add(today);
            diffP = tempReal - prevHigh;
            prevHigh = tempReal;
            tempReal = *inLow.as_ptr().add(today);
            diffM = prevLow - tempReal;
            prevLow = tempReal;
            if diffM > 0_f64 && diffP < diffM {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64) + diffM;
            } else {
                prevMinusDM = prevMinusDM - prevMinusDM / ((optInTimePeriod) as f64);
            }
            *outReal.as_mut_ptr().add(outIdx) = prevMinusDM;
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
