/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::obv`].
    ///
    /// # Arguments
    ///
    pub fn obv_lookback(&self) -> usize {
        return (0) as usize;
    }
    /// On Balance Volume
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `inVolume` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn obv(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        inVolume: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevReal: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut prevOBV: f64 = 0.0_f64;
        prevOBV = inVolume[startIdx];
        prevReal = inReal[startIdx];
        outIdx = 0;
        for i in (startIdx as usize)..(endIdx as usize) + 1 {
            tempReal = inReal[i];
            if tempReal > prevReal {
                prevOBV += inVolume[i];
            } else if tempReal < prevReal {
                prevOBV -= inVolume[i];
            }
            outReal[outIdx] = prevOBV;
            outIdx += 1;
            prevReal = tempReal;
        }
        i = (endIdx as usize) + 1;
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn obv_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        inVolume: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut prevReal: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        let mut prevOBV: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx < inVolume.len());
        assert!(endIdx - startIdx < outReal.len());
        prevOBV = *inVolume.as_ptr().add(startIdx);
        prevReal = *inReal.as_ptr().add(startIdx);
        outIdx = 0;
        for i in (startIdx as usize)..(endIdx as usize) + 1 {
            tempReal = *inReal.as_ptr().add(i);
            if tempReal > prevReal {
                prevOBV += *inVolume.as_ptr().add(i);
            } else if tempReal < prevReal {
                prevOBV -= *inVolume.as_ptr().add(i);
            }
            *outReal.as_mut_ptr().add(outIdx) = prevOBV;
            outIdx += 1;
            prevReal = tempReal;
        }
        i = (endIdx as usize) + 1;
        (*outBegIdx) = startIdx;
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
