/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::sar`].
    ///
    /// # Arguments
    ///
    /// * `optInAcceleration` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInMaximum` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    #[inline]
    pub fn sar_lookback(&self, mut optInAcceleration: f64, mut optInMaximum: f64) -> usize {
        return (1) as usize;
    }
    /// Parabolic SAR
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `optInAcceleration` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `optInMaximum` - Number of period (default: 0, range: 0..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn sar(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInAcceleration: f64,
        mut optInMaximum: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut retCode: RetCode = RetCode::Success;
        let mut isLong: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut newHigh: f64 = 0.0_f64;
        let mut newLow: f64 = 0.0_f64;
        let mut prevHigh: f64 = 0.0_f64;
        let mut prevLow: f64 = 0.0_f64;
        let mut af: f64 = 0.0_f64;
        let mut ep: f64 = 0.0_f64;
        let mut sar: f64 = 0.0_f64;
        let mut ep_temp: [f64; 1 as usize] = [0.0_f64; 1 as usize];
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        af = optInAcceleration;
        if af > optInMaximum {
            optInAcceleration = optInMaximum;
            af = optInAcceleration;
        }
        let mut _dup_out: usize = 0_usize;
        retCode = self.minus_dm_unguarded(startIdx, startIdx, inHigh, inLow, 1, &mut tempInt, &mut _dup_out, &mut ep_temp);
        if ep_temp[0] > 0_f64 {
            isLong = 0;
        } else {
            isLong = 1;
        }
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        outIdx = 0;
        todayIdx = startIdx;
        newHigh = inHigh[todayIdx - 1];
        newLow = inLow[todayIdx - 1];
        if isLong == 1 {
            ep = inHigh[todayIdx];
            sar = newLow;
        } else {
            ep = inLow[todayIdx];
            sar = newHigh;
        }
        newLow = inLow[todayIdx];
        newHigh = inHigh[todayIdx];
        while todayIdx <= endIdx {
            prevLow = newLow;
            prevHigh = newHigh;
            newLow = inLow[todayIdx];
            newHigh = inHigh[todayIdx];
            todayIdx += 1;
            if isLong == 1 {
                if newLow <= sar {
                    isLong = 0;
                    sar = ep;
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                    outReal[outIdx] = sar;
                    outIdx += 1;
                    af = optInAcceleration;
                    ep = newLow;
                    sar = (af as f64).mul_add(ep - sar, sar);
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                } else {
                    outReal[outIdx] = sar;
                    outIdx += 1;
                    if newHigh > ep {
                        ep = newHigh;
                        af += optInAcceleration;
                        if af > optInMaximum {
                            af = optInMaximum;
                        }
                    }
                    sar = (af as f64).mul_add(ep - sar, sar);
                    if sar > prevLow {
                        sar = prevLow;
                    }
                    if sar > newLow {
                        sar = newLow;
                    }
                }
            } else if newHigh >= sar {
                isLong = 1;
                sar = ep;
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
                outReal[outIdx] = sar;
                outIdx += 1;
                af = optInAcceleration;
                ep = newHigh;
                sar = (af as f64).mul_add(ep - sar, sar);
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
            } else {
                outReal[outIdx] = sar;
                outIdx += 1;
                if newLow < ep {
                    ep = newLow;
                    af += optInAcceleration;
                    if af > optInMaximum {
                        af = optInMaximum;
                    }
                }
                sar = (af as f64).mul_add(ep - sar, sar);
                if sar < prevHigh {
                    sar = prevHigh;
                }
                if sar < newHigh {
                    sar = newHigh;
                }
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn sar_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        mut optInAcceleration: f64,
        mut optInMaximum: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut isLong: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut tempInt: usize = 0_usize;
        let mut newHigh: f64 = 0.0_f64;
        let mut newLow: f64 = 0.0_f64;
        let mut prevHigh: f64 = 0.0_f64;
        let mut prevLow: f64 = 0.0_f64;
        let mut af: f64 = 0.0_f64;
        let mut ep: f64 = 0.0_f64;
        let mut sar: f64 = 0.0_f64;
        let mut ep_temp: [f64; 1 as usize] = [0.0_f64; 1 as usize];
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx - startIdx < outReal.len());
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        af = optInAcceleration;
        if af > optInMaximum {
            optInAcceleration = optInMaximum;
            af = optInAcceleration;
        }
        let mut _dup_out: usize = 0_usize;
        retCode = self.minus_dm_unguarded(startIdx, startIdx, inHigh, inLow, 1, &mut tempInt, &mut _dup_out, &mut ep_temp);
        if *ep_temp.as_ptr().add(0) > 0_f64 {
            isLong = 0;
        } else {
            isLong = 1;
        }
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        outIdx = 0;
        todayIdx = startIdx;
        newHigh = *inHigh.as_ptr().add(todayIdx - 1);
        newLow = *inLow.as_ptr().add(todayIdx - 1);
        if isLong == 1 {
            ep = *inHigh.as_ptr().add(todayIdx);
            sar = newLow;
        } else {
            ep = *inLow.as_ptr().add(todayIdx);
            sar = newHigh;
        }
        newLow = *inLow.as_ptr().add(todayIdx);
        newHigh = *inHigh.as_ptr().add(todayIdx);
        while todayIdx <= endIdx {
            prevLow = newLow;
            prevHigh = newHigh;
            newLow = *inLow.as_ptr().add(todayIdx);
            newHigh = *inHigh.as_ptr().add(todayIdx);
            todayIdx += 1;
            if isLong == 1 {
                if newLow <= sar {
                    isLong = 0;
                    sar = ep;
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                    *outReal.as_mut_ptr().add(outIdx) = sar;
                    outIdx += 1;
                    af = optInAcceleration;
                    ep = newLow;
                    sar = (af as f64).mul_add(ep - sar, sar);
                    if sar < prevHigh {
                        sar = prevHigh;
                    }
                    if sar < newHigh {
                        sar = newHigh;
                    }
                } else {
                    *outReal.as_mut_ptr().add(outIdx) = sar;
                    outIdx += 1;
                    if newHigh > ep {
                        ep = newHigh;
                        af += optInAcceleration;
                        if af > optInMaximum {
                            af = optInMaximum;
                        }
                    }
                    sar = (af as f64).mul_add(ep - sar, sar);
                    if sar > prevLow {
                        sar = prevLow;
                    }
                    if sar > newLow {
                        sar = newLow;
                    }
                }
            } else if newHigh >= sar {
                isLong = 1;
                sar = ep;
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
                *outReal.as_mut_ptr().add(outIdx) = sar;
                outIdx += 1;
                af = optInAcceleration;
                ep = newHigh;
                sar = (af as f64).mul_add(ep - sar, sar);
                if sar > prevLow {
                    sar = prevLow;
                }
                if sar > newLow {
                    sar = newLow;
                }
            } else {
                *outReal.as_mut_ptr().add(outIdx) = sar;
                outIdx += 1;
                if newLow < ep {
                    ep = newLow;
                    af += optInAcceleration;
                    if af > optInMaximum {
                        af = optInMaximum;
                    }
                }
                sar = (af as f64).mul_add(ep - sar, sar);
                if sar < prevHigh {
                    sar = prevHigh;
                }
                if sar < newHigh {
                    sar = newHigh;
                }
            }
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
