/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::stddev`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInNbDev` - Number of period (default: 1, range: -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    #[inline]
    pub fn stddev_lookback(&self, mut optInTimePeriod: i32, mut optInNbDev: f64) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return self.var_lookback(optInTimePeriod, optInNbDev);
    }
    /// Standard Deviation
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInNbDev` - Number of period (default: 1, range: -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000..=179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn stddev(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInNbDev: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut i: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        let mut tempReal: f64 = 0.0_f64;
        retCode = self.var_unguarded(startIdx, endIdx, inReal, optInTimePeriod, 1.0, outBegIdx, outNBElement, outReal);
        if retCode != RetCode::Success {
            return retCode;
        }
        if optInNbDev != 1.0 {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = outReal[i];
                if !((tempReal) < 1e-14) {
                    outReal[i] = (tempReal).sqrt() * optInNbDev;
                } else {
                    outReal[i] = (0.0) as f64;
                }
                i += 1;
            }
        } else {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = outReal[i];
                if !((tempReal) < 1e-14) {
                    outReal[i] = (tempReal).sqrt();
                } else {
                    outReal[i] = (0.0) as f64;
                }
                i += 1;
            }
        }
        return RetCode::Success;
    }
    #[inline]
    pub fn stddev_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInNbDev: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut i: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        let mut tempReal: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        retCode = self.var_unguarded(startIdx, endIdx, inReal, optInTimePeriod, 1.0, outBegIdx, outNBElement, outReal);
        if retCode != RetCode::Success {
            return retCode;
        }
        if optInNbDev != 1.0 {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = *outReal.as_ptr().add(i);
                if !((tempReal) < 1e-14) {
                    *outReal.as_mut_ptr().add(i) = (tempReal).sqrt() * optInNbDev;
                } else {
                    *outReal.as_mut_ptr().add(i) = (0.0) as f64;
                }
                i += 1;
            }
        } else {
            // for( i = 0; i < ((((*outNBElement)) as usize)) as usize; i += 1 )
            i = 0;
            while i < ((((*outNBElement)) as usize)) as usize {
                tempReal = *outReal.as_ptr().add(i);
                if !((tempReal) < 1e-14) {
                    *outReal.as_mut_ptr().add(i) = (tempReal).sqrt();
                } else {
                    *outReal.as_mut_ptr().add(i) = (0.0) as f64;
                }
                i += 1;
            }
        }
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
