/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::stoch`].
    ///
    /// # Arguments
    ///
    /// * `optInFastK_Period` - Number of period (default: 5, range: 1..=100000)
    /// * `optInSlowK_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `optInSlowD_Period` - Number of period (default: 3, range: 1..=100000)
    #[inline]
    pub fn stoch_lookback(&self, mut optInFastK_Period: i32, mut optInSlowK_Period: i32, mut optInSlowK_MAType: i32, mut optInSlowD_Period: i32, mut optInSlowD_MAType: i32) -> usize {
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSlowK_Period) as i32) == (i32::MIN) {
            optInSlowK_Period = 3;
        } else if (((optInSlowK_Period) as i32) < 1) || (((optInSlowK_Period) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInSlowD_Period) as i32) == (i32::MIN) {
            optInSlowD_Period = 3;
        } else if (((optInSlowD_Period) as i32) < 1) || (((optInSlowD_Period) as i32) > 100000) {
            return usize::MAX;
        }
        let mut retValue: usize = 0_usize;
        retValue = (optInFastK_Period - 1) as usize;
        retValue += self.ma_lookback(optInSlowK_Period, optInSlowK_MAType);
        retValue += self.ma_lookback(optInSlowD_Period, optInSlowD_MAType);
        return retValue;
    }
    /// Stochastic
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `optInFastK_Period` - Number of period (default: 5, range: 1..=100000)
    /// * `optInSlowK_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `optInSlowD_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outSlowK` - Output values
    /// * `outSlowD` - Output values
    pub fn stoch(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInFastK_Period: i32,
        mut optInSlowK_Period: i32,
        mut optInSlowK_MAType: i32,
        mut optInSlowD_Period: i32,
        mut optInSlowD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outSlowK: &mut [f64],
        outSlowD: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowK_Period) as i32) == (i32::MIN) {
            optInSlowK_Period = 3;
        } else if (((optInSlowK_Period) as i32) < 1) || (((optInSlowK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInSlowD_Period) as i32) == (i32::MIN) {
            optInSlowD_Period = 3;
        } else if (((optInSlowD_Period) as i32) < 1) || (((optInSlowD_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut retCode: RetCode = RetCode::Success;
        let mut lowest: f64 = 0.0_f64;
        let mut highest: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut diff: f64 = 0.0_f64;
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut outIdx: usize = 0_usize;
        let mut lowestIdx: i32 = 0_i32;
        let mut highestIdx: i32 = 0_i32;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackK: usize = 0_usize;
        let mut lookbackKSlow: usize = 0_usize;
        let mut lookbackDSlow: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut bufferIsAllocated: usize = 0_usize;
        lookbackK = (optInFastK_Period - 1) as usize;
        lookbackKSlow = self.ma_lookback(optInSlowK_Period, optInSlowK_MAType);
        lookbackDSlow = self.ma_lookback(optInSlowD_Period, optInSlowD_MAType);
        lookbackTotal = lookbackK + lookbackDSlow + lookbackKSlow;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        today = trailingIdx + lookbackK;
        highestIdx = 0 - 1;
        lowestIdx = highestIdx;
        lowest = 0.0;
        highest = lowest;
        diff = highest;
        bufferIsAllocated = 0;
        if outSlowK == inHigh || outSlowK == inLow || outSlowK == inClose {
            tempBuffer = outSlowK.to_vec();
        } else if outSlowD == inHigh || outSlowD == inLow || outSlowD == inClose {
            tempBuffer = outSlowD.to_vec();
        } else {
            bufferIsAllocated = 1;
            tempBuffer = vec![0.0_f64; ((endIdx - today + 1) * 1) as usize];
        }
        while today <= endIdx {
            tmp = inLow[today];
            if lowestIdx < (trailingIdx) as i32 {
                lowestIdx = (trailingIdx) as i32;
                lowest = inLow[(lowestIdx) as usize];
                i = (lowestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = inLow[i];
                    if tmp < lowest {
                        lowestIdx = (i) as i32;
                        lowest = tmp;
                    }
                }
                diff = (highest - lowest) / 100.0;
            } else if tmp <= lowest {
                lowestIdx = (today) as i32;
                lowest = tmp;
                diff = (highest - lowest) / 100.0;
            }
            tmp = inHigh[today];
            if highestIdx < (trailingIdx) as i32 {
                highestIdx = (trailingIdx) as i32;
                highest = inHigh[(highestIdx) as usize];
                i = (highestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = inHigh[i];
                    if tmp > highest {
                        highestIdx = (i) as i32;
                        highest = tmp;
                    }
                }
                diff = (highest - lowest) / 100.0;
            } else if tmp >= highest {
                highestIdx = (today) as i32;
                highest = tmp;
                diff = (highest - lowest) / 100.0;
            }
            if diff != 0.0 {
                tempBuffer[outIdx] = (inClose[today] - lowest) / diff;
                outIdx += 1;
            } else {
                tempBuffer[outIdx] = 0.0;
                outIdx += 1;
            }
            trailingIdx += 1;
            today += 1;
        }
        retCode = self.ma_unguarded(0, outIdx - 1, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInSlowK_Period, optInSlowK_MAType, outBegIdx, outNBElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            if bufferIsAllocated != 0 {
            }
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ma_unguarded(0, ((((*outNBElement)) as usize) - 1) as usize, &tempBuffer, optInSlowD_Period, optInSlowD_MAType, outBegIdx, outNBElement, outSlowD);
        {
            let _n = (((((*outNBElement)) as usize)) as usize * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackDSlow) as usize;
            outSlowK[_di.._di + _n].copy_from_slice(&tempBuffer[_si.._si + _n]);
        };
        if bufferIsAllocated != 0 {
        }
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn stoch_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        mut optInFastK_Period: i32,
        mut optInSlowK_Period: i32,
        mut optInSlowK_MAType: i32,
        mut optInSlowD_Period: i32,
        mut optInSlowD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outSlowK: &mut [f64],
        outSlowD: &mut [f64],
    ) -> RetCode {
        let mut retCode: RetCode = RetCode::Success;
        let mut lowest: f64 = 0.0_f64;
        let mut highest: f64 = 0.0_f64;
        let mut tmp: f64 = 0.0_f64;
        let mut diff: f64 = 0.0_f64;
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut outIdx: usize = 0_usize;
        let mut lowestIdx: i32 = 0_i32;
        let mut highestIdx: i32 = 0_i32;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackK: usize = 0_usize;
        let mut lookbackKSlow: usize = 0_usize;
        let mut lookbackDSlow: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut bufferIsAllocated: usize = 0_usize;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outSlowK.len());
        assert!(endIdx - startIdx < outSlowD.len());
        lookbackK = (optInFastK_Period - 1) as usize;
        lookbackKSlow = self.ma_lookback(optInSlowK_Period, optInSlowK_MAType);
        lookbackDSlow = self.ma_lookback(optInSlowD_Period, optInSlowD_MAType);
        lookbackTotal = lookbackK + lookbackDSlow + lookbackKSlow;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        trailingIdx = startIdx - lookbackTotal;
        today = trailingIdx + lookbackK;
        highestIdx = 0 - 1;
        lowestIdx = highestIdx;
        lowest = 0.0;
        highest = lowest;
        diff = highest;
        bufferIsAllocated = 0;
        if outSlowK == inHigh || outSlowK == inLow || outSlowK == inClose {
            tempBuffer = outSlowK.to_vec();
        } else if outSlowD == inHigh || outSlowD == inLow || outSlowD == inClose {
            tempBuffer = outSlowD.to_vec();
        } else {
            bufferIsAllocated = 1;
            tempBuffer = vec![0.0_f64; ((endIdx - today + 1) * 1) as usize];
        }
        while today <= endIdx {
            tmp = *inLow.as_ptr().add(today);
            if lowestIdx < (trailingIdx) as i32 {
                lowestIdx = (trailingIdx) as i32;
                lowest = *inLow.as_ptr().add((lowestIdx) as usize);
                i = (lowestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = *inLow.as_ptr().add(i);
                    if tmp < lowest {
                        lowestIdx = (i) as i32;
                        lowest = tmp;
                    }
                }
                diff = (highest - lowest) / 100.0;
            } else if tmp <= lowest {
                lowestIdx = (today) as i32;
                lowest = tmp;
                diff = (highest - lowest) / 100.0;
            }
            tmp = *inHigh.as_ptr().add(today);
            if highestIdx < (trailingIdx) as i32 {
                highestIdx = (trailingIdx) as i32;
                highest = *inHigh.as_ptr().add((highestIdx) as usize);
                i = (highestIdx) as usize;
                while { i += 1; i } <= today {
                    tmp = *inHigh.as_ptr().add(i);
                    if tmp > highest {
                        highestIdx = (i) as i32;
                        highest = tmp;
                    }
                }
                diff = (highest - lowest) / 100.0;
            } else if tmp >= highest {
                highestIdx = (today) as i32;
                highest = tmp;
                diff = (highest - lowest) / 100.0;
            }
            if diff != 0.0 {
                *tempBuffer.as_mut_ptr().add(outIdx) = (*inClose.as_ptr().add(today) - lowest) / diff;
                outIdx += 1;
            } else {
                *tempBuffer.as_mut_ptr().add(outIdx) = 0.0;
                outIdx += 1;
            }
            trailingIdx += 1;
            today += 1;
        }
        retCode = self.ma_unguarded(0, outIdx - 1, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInSlowK_Period, optInSlowK_MAType, outBegIdx, outNBElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            if bufferIsAllocated != 0 {
            }
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.ma_unguarded(0, ((((*outNBElement)) as usize) - 1) as usize, &tempBuffer, optInSlowD_Period, optInSlowD_MAType, outBegIdx, outNBElement, outSlowD);
        {
            let _n = (((((*outNBElement)) as usize)) as usize * 1) as usize;
            let _di = (0) as usize;
            let _si = (lookbackDSlow) as usize;
            outSlowK[_di.._di + _n].copy_from_slice(&tempBuffer[_si.._si + _n]);
        };
        if bufferIsAllocated != 0 {
        }
        if retCode != RetCode::Success {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
