/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::stochrsi`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `optInFastK_Period` - Number of period (default: 5, range: 1..=100000)
    /// * `optInFastD_Period` - Number of period (default: 3, range: 1..=100000)
    #[inline]
    pub fn stochrsi_lookback(&self, mut optInTimePeriod: i32, mut optInFastK_Period: i32, mut optInFastD_Period: i32, mut optInFastD_MAType: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return usize::MAX;
        }
        if ((optInFastD_Period) as i32) == (i32::MIN) {
            optInFastD_Period = 3;
        } else if (((optInFastD_Period) as i32) < 1) || (((optInFastD_Period) as i32) > 100000) {
            return usize::MAX;
        }
        let mut retValue: usize = 0_usize;
        retValue = self.rsi_lookback(optInTimePeriod) + self.stochf_lookback(optInFastK_Period, optInFastD_Period, optInFastD_MAType);
        return retValue;
    }
    /// Stochastic Relative Strength Index
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 14, range: 2..=100000)
    /// * `optInFastK_Period` - Number of period (default: 5, range: 1..=100000)
    /// * `optInFastD_Period` - Number of period (default: 3, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outFastK` - Output values
    /// * `outFastD` - Output values
    pub fn stochrsi(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInFastK_Period: i32,
        mut optInFastD_Period: i32,
        mut optInFastD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outFastK: &mut [f64],
        outFastD: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 14;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInFastK_Period) as i32) == (i32::MIN) {
            optInFastK_Period = 5;
        } else if (((optInFastK_Period) as i32) < 1) || (((optInFastK_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        if ((optInFastD_Period) as i32) == (i32::MIN) {
            optInFastD_Period = 3;
        } else if (((optInFastD_Period) as i32) < 1) || (((optInFastD_Period) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut tempRSIBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackSTOCHF: usize = 0_usize;
        let mut tempArraySize: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackSTOCHF = self.stochf_lookback(optInFastK_Period, optInFastD_Period, optInFastD_MAType);
        lookbackTotal = self.rsi_lookback(optInTimePeriod) + lookbackSTOCHF;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        tempArraySize = endIdx - startIdx + 1 + lookbackSTOCHF;
        tempRSIBuffer = vec![0.0_f64; (tempArraySize * 1) as usize];
        retCode = self.rsi_unguarded(startIdx - lookbackSTOCHF, endIdx, inReal, optInTimePeriod, &mut outBegIdx1, &mut outNbElement1, &mut tempRSIBuffer[..]);
        if retCode != RetCode::Success || outNbElement1 == 0 {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.stochf_unguarded(0, tempArraySize - 1, &tempRSIBuffer, &tempRSIBuffer, &tempRSIBuffer, optInFastK_Period, optInFastD_Period, optInFastD_MAType, &mut outBegIdx2, outNBElement, outFastK, outFastD);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        return RetCode::Success;
    }
    #[inline]
    pub fn stochrsi_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInFastK_Period: i32,
        mut optInFastD_Period: i32,
        mut optInFastD_MAType: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outFastK: &mut [f64],
        outFastD: &mut [f64],
    ) -> RetCode {
        let mut tempRSIBuffer: Vec<f64> = Vec::new();
        let mut retCode: RetCode = RetCode::Success;
        let mut lookbackTotal: usize = 0_usize;
        let mut lookbackSTOCHF: usize = 0_usize;
        let mut tempArraySize: usize = 0_usize;
        let mut outBegIdx1: usize = 0_usize;
        let mut outBegIdx2: usize = 0_usize;
        let mut outNbElement1: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outFastK.len());
        assert!(endIdx - startIdx < outFastD.len());
        (*outBegIdx) = 0;
        (*outNBElement) = 0;
        lookbackSTOCHF = self.stochf_lookback(optInFastK_Period, optInFastD_Period, optInFastD_MAType);
        lookbackTotal = self.rsi_lookback(optInTimePeriod) + lookbackSTOCHF;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        tempArraySize = endIdx - startIdx + 1 + lookbackSTOCHF;
        tempRSIBuffer = vec![0.0_f64; (tempArraySize * 1) as usize];
        retCode = self.rsi_unguarded(startIdx - lookbackSTOCHF, endIdx, inReal, optInTimePeriod, &mut outBegIdx1, &mut outNbElement1, &mut tempRSIBuffer[..]);
        if retCode != RetCode::Success || outNbElement1 == 0 {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        retCode = self.stochf_unguarded(0, tempArraySize - 1, &tempRSIBuffer, &tempRSIBuffer, &tempRSIBuffer, optInFastK_Period, optInFastD_Period, optInFastD_MAType, &mut outBegIdx2, outNBElement, outFastK, outFastD);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return retCode;
        }
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
