/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::t3`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInVFactor` - Number of period (default: 0, range: 0..=1)
    #[inline]
    pub fn t3_lookback(&self, mut optInTimePeriod: i32, mut optInVFactor: f64) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (6 * (optInTimePeriod - 1) + self.unstable_period[FuncUnstId::T3 as usize]) as usize;
    }
    /// Triple Exponential Moving Average (T3)
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 5, range: 2..=100000)
    /// * `optInVFactor` - Number of period (default: 0, range: 0..=1)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn t3(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInVFactor: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 5;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut k: f64 = 0.0_f64;
        let mut one_minus_k: f64 = 0.0_f64;
        let mut e1: f64 = 0.0_f64;
        let mut e2: f64 = 0.0_f64;
        let mut e3: f64 = 0.0_f64;
        let mut e4: f64 = 0.0_f64;
        let mut e5: f64 = 0.0_f64;
        let mut e6: f64 = 0.0_f64;
        let mut c1: f64 = 0.0_f64;
        let mut c2: f64 = 0.0_f64;
        let mut c3: f64 = 0.0_f64;
        let mut c4: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        lookbackTotal = (6 * (optInTimePeriod - 1) + self.unstable_period[FuncUnstId::T3 as usize]) as usize;
        if startIdx <= lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        today = startIdx - lookbackTotal;
        k = 2.0 / (((optInTimePeriod) as f64) + 1.0);
        one_minus_k = 1.0 - k;
        tempReal = inReal[{ let _v = today; today += 1; _v }];
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            tempReal += inReal[{ let _v = today; today += 1; _v }];
            i -= 1;
        }
        e1 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e1;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            tempReal += e1;
            i -= 1;
        }
        e2 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e2;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            tempReal += e2;
            i -= 1;
        }
        e3 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e3;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            tempReal += e3;
            i -= 1;
        }
        e4 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e4;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            tempReal += e4;
            i -= 1;
        }
        e5 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e5;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            e5 = (k as f64).mul_add(e4, one_minus_k * e5);
            tempReal += e5;
            i -= 1;
        }
        e6 = tempReal / ((optInTimePeriod) as f64);
        while today <= startIdx {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            e5 = (k as f64).mul_add(e4, one_minus_k * e5);
            e6 = (k as f64).mul_add(e5, one_minus_k * e6);
        }
        tempReal = optInVFactor * optInVFactor;
        c1 = 0_f64 - tempReal * optInVFactor;
        c2 = 3.0 * (tempReal - c1);
        c3 = (0_f64 - 6.0) * tempReal - 3.0 * (optInVFactor - c1);
        c4 = (3.0 as f64).mul_add(tempReal, (3.0 as f64).mul_add(optInVFactor, 1.0) - c1);
        outIdx = 0;
        outReal[outIdx] = (c4 as f64).mul_add(e3, (c3 as f64).mul_add(e4, (c1 as f64).mul_add(e6, c2 * e5)));
        outIdx += 1;
        while today <= endIdx {
            e1 = (k as f64).mul_add(inReal[{ let _v = today; today += 1; _v }], one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            e5 = (k as f64).mul_add(e4, one_minus_k * e5);
            e6 = (k as f64).mul_add(e5, one_minus_k * e6);
            outReal[outIdx] = (c4 as f64).mul_add(e3, (c3 as f64).mul_add(e4, (c1 as f64).mul_add(e6, c2 * e5)));
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn t3_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        mut optInVFactor: f64,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut outIdx: usize = 0_usize;
        let mut lookbackTotal: usize = 0_usize;
        let mut today: usize = 0_usize;
        let mut i: usize = 0_usize;
        let mut k: f64 = 0.0_f64;
        let mut one_minus_k: f64 = 0.0_f64;
        let mut e1: f64 = 0.0_f64;
        let mut e2: f64 = 0.0_f64;
        let mut e3: f64 = 0.0_f64;
        let mut e4: f64 = 0.0_f64;
        let mut e5: f64 = 0.0_f64;
        let mut e6: f64 = 0.0_f64;
        let mut c1: f64 = 0.0_f64;
        let mut c2: f64 = 0.0_f64;
        let mut c3: f64 = 0.0_f64;
        let mut c4: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        lookbackTotal = (6 * (optInTimePeriod - 1) + self.unstable_period[FuncUnstId::T3 as usize]) as usize;
        if startIdx <= lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        today = startIdx - lookbackTotal;
        k = 2.0 / (((optInTimePeriod) as f64) + 1.0);
        one_minus_k = 1.0 - k;
        tempReal = *inReal.as_ptr().add({ let _v = today; today += 1; _v });
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            tempReal += *inReal.as_ptr().add({ let _v = today; today += 1; _v });
            i -= 1;
        }
        e1 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e1;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            tempReal += e1;
            i -= 1;
        }
        e2 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e2;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            tempReal += e2;
            i -= 1;
        }
        e3 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e3;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            tempReal += e3;
            i -= 1;
        }
        e4 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e4;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            tempReal += e4;
            i -= 1;
        }
        e5 = tempReal / ((optInTimePeriod) as f64);
        tempReal = e5;
        // for( i = (optInTimePeriod - 1) as usize; i > 0; i -= 1 )
        i = (optInTimePeriod - 1) as usize;
        while i > 0 {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            e5 = (k as f64).mul_add(e4, one_minus_k * e5);
            tempReal += e5;
            i -= 1;
        }
        e6 = tempReal / ((optInTimePeriod) as f64);
        while today <= startIdx {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            e5 = (k as f64).mul_add(e4, one_minus_k * e5);
            e6 = (k as f64).mul_add(e5, one_minus_k * e6);
        }
        tempReal = optInVFactor * optInVFactor;
        c1 = 0_f64 - tempReal * optInVFactor;
        c2 = 3.0 * (tempReal - c1);
        c3 = (0_f64 - 6.0) * tempReal - 3.0 * (optInVFactor - c1);
        c4 = (3.0 as f64).mul_add(tempReal, (3.0 as f64).mul_add(optInVFactor, 1.0) - c1);
        outIdx = 0;
        *outReal.as_mut_ptr().add(outIdx) = (c4 as f64).mul_add(e3, (c3 as f64).mul_add(e4, (c1 as f64).mul_add(e6, c2 * e5)));
        outIdx += 1;
        while today <= endIdx {
            e1 = (k as f64).mul_add(*inReal.as_ptr().add({ let _v = today; today += 1; _v }), one_minus_k * e1);
            e2 = (k as f64).mul_add(e1, one_minus_k * e2);
            e3 = (k as f64).mul_add(e2, one_minus_k * e3);
            e4 = (k as f64).mul_add(e3, one_minus_k * e4);
            e5 = (k as f64).mul_add(e4, one_minus_k * e5);
            e6 = (k as f64).mul_add(e5, one_minus_k * e6);
            *outReal.as_mut_ptr().add(outIdx) = (c4 as f64).mul_add(e3, (c3 as f64).mul_add(e4, (c1 as f64).mul_add(e6, c2 * e5)));
            outIdx += 1;
        }
        (*outNBElement) = outIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
