/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::trange`].
    ///
    /// # Arguments
    ///
    pub fn trange_lookback(&self) -> usize {
        return (1) as usize;
    }
    /// True Range
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inHigh` - Input price series
    /// * `inLow` - Input price series
    /// * `inClose` - Input price series
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn trange(
        &self,
        startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        let mut startIdx = startIdx;
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut val2: f64 = 0.0_f64;
        let mut val3: f64 = 0.0_f64;
        let mut greatest: f64 = 0.0_f64;
        let mut tempCY: f64 = 0.0_f64;
        let mut tempLT: f64 = 0.0_f64;
        let mut tempHT: f64 = 0.0_f64;
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        while today <= endIdx {
            tempLT = inLow[today];
            tempHT = inHigh[today];
            tempCY = inClose[today - 1];
            greatest = tempHT - tempLT;
            val2 = (tempCY - tempHT).abs();
            if val2 > greatest {
                greatest = val2;
            }
            val3 = (tempCY - tempLT).abs();
            if val3 > greatest {
                greatest = val3;
            }
            outReal[outIdx] = greatest;
            outIdx += 1;
            today += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn trange_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inHigh: &[f64],
        inLow: &[f64],
        inClose: &[f64],
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut today: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut val2: f64 = 0.0_f64;
        let mut val3: f64 = 0.0_f64;
        let mut greatest: f64 = 0.0_f64;
        let mut tempCY: f64 = 0.0_f64;
        let mut tempLT: f64 = 0.0_f64;
        let mut tempHT: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inHigh.len());
        assert!(endIdx < inLow.len());
        assert!(endIdx < inClose.len());
        assert!(endIdx - startIdx < outReal.len());
        if startIdx < 1 {
            startIdx = 1;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        today = startIdx;
        while today <= endIdx {
            tempLT = *inLow.as_ptr().add(today);
            tempHT = *inHigh.as_ptr().add(today);
            tempCY = *inClose.as_ptr().add(today - 1);
            greatest = tempHT - tempLT;
            val2 = (tempCY - tempHT).abs();
            if val2 > greatest {
                greatest = val2;
            }
            val3 = (tempCY - tempLT).abs();
            if val3 > greatest {
                greatest = val3;
            }
            *outReal.as_mut_ptr().add(outIdx) = greatest;
            outIdx += 1;
            today += 1;
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
