/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::trima`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    #[inline]
    pub fn trima_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        return (optInTimePeriod - 1) as usize;
    }
    /// Triangular Moving Average
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 2..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn trima(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 2) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut lookbackTotal: usize = 0_usize;
        let mut numerator: f64 = 0.0_f64;
        let mut numeratorSub: f64 = 0.0_f64;
        let mut numeratorAdd: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut middleIdx: usize = 0_usize;
        let mut factor: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod % 2 == 1 {
            i = (optInTimePeriod >> 1) as usize;
            factor = (((i + 1) * (i + 1)) as f64);
            factor = 1.0 / factor;
            trailingIdx = startIdx - lookbackTotal;
            middleIdx = trailingIdx + i;
            todayIdx = middleIdx + i;
            numerator = 0.0;
            numeratorSub = 0.0;
            // for( i = middleIdx; i >= trailingIdx; i -= 1 )
            i = middleIdx;
            loop {
                tempReal = inReal[i];
                numeratorSub += tempReal;
                numerator += numeratorSub;
                if i == trailingIdx { break; }
                i -= 1;
            }
            numeratorAdd = 0.0;
            middleIdx += 1;
            for i in (middleIdx as usize)..(todayIdx as usize) + 1 {
                tempReal = inReal[i];
                numeratorAdd += tempReal;
                numerator += numeratorAdd;
            }
            i = (todayIdx as usize) + 1;
            outIdx = 0;
            tempReal = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            outReal[outIdx] = numerator * factor;
            outIdx += 1;
            todayIdx += 1;
            while todayIdx <= endIdx {
                numerator -= numeratorSub;
                numeratorSub -= tempReal;
                tempReal = inReal[{ let _v = middleIdx; middleIdx += 1; _v }];
                numeratorSub += tempReal;
                numerator += numeratorAdd;
                numeratorAdd -= tempReal;
                tempReal = inReal[{ let _v = todayIdx; todayIdx += 1; _v }];
                numeratorAdd += tempReal;
                numerator += tempReal;
                tempReal = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
                outReal[outIdx] = numerator * factor;
                outIdx += 1;
            }
        } else {
            i = (optInTimePeriod >> 1) as usize;
            factor = ((i * (i + 1)) as f64);
            factor = 1.0 / factor;
            trailingIdx = startIdx - lookbackTotal;
            middleIdx = trailingIdx + i - 1;
            todayIdx = middleIdx + i;
            numerator = 0.0;
            numeratorSub = 0.0;
            // for( i = middleIdx; i >= trailingIdx; i -= 1 )
            i = middleIdx;
            loop {
                tempReal = inReal[i];
                numeratorSub += tempReal;
                numerator += numeratorSub;
                if i == trailingIdx { break; }
                i -= 1;
            }
            numeratorAdd = 0.0;
            middleIdx += 1;
            for i in (middleIdx as usize)..(todayIdx as usize) + 1 {
                tempReal = inReal[i];
                numeratorAdd += tempReal;
                numerator += numeratorAdd;
            }
            i = (todayIdx as usize) + 1;
            outIdx = 0;
            tempReal = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
            outReal[outIdx] = numerator * factor;
            outIdx += 1;
            todayIdx += 1;
            while todayIdx <= endIdx {
                numerator -= numeratorSub;
                numeratorSub -= tempReal;
                tempReal = inReal[{ let _v = middleIdx; middleIdx += 1; _v }];
                numeratorSub += tempReal;
                numeratorAdd -= tempReal;
                numerator += numeratorAdd;
                tempReal = inReal[{ let _v = todayIdx; todayIdx += 1; _v }];
                numeratorAdd += tempReal;
                numerator += tempReal;
                tempReal = inReal[{ let _v = trailingIdx; trailingIdx += 1; _v }];
                outReal[outIdx] = numerator * factor;
                outIdx += 1;
            }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
    }
    #[inline]
    pub fn trima_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut lookbackTotal: usize = 0_usize;
        let mut numerator: f64 = 0.0_f64;
        let mut numeratorSub: f64 = 0.0_f64;
        let mut numeratorAdd: f64 = 0.0_f64;
        let mut i: usize = 0_usize;
        let mut outIdx: usize = 0_usize;
        let mut todayIdx: usize = 0_usize;
        let mut trailingIdx: usize = 0_usize;
        let mut middleIdx: usize = 0_usize;
        let mut factor: f64 = 0.0_f64;
        let mut tempReal: f64 = 0.0_f64;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        lookbackTotal = (optInTimePeriod - 1) as usize;
        if startIdx < lookbackTotal {
            startIdx = lookbackTotal;
        }
        if startIdx > endIdx {
            (*outBegIdx) = 0;
            (*outNBElement) = 0;
            return RetCode::Success;
        }
        outIdx = 0;
        if optInTimePeriod % 2 == 1 {
            i = (optInTimePeriod >> 1) as usize;
            factor = (((i + 1) * (i + 1)) as f64);
            factor = 1.0 / factor;
            trailingIdx = startIdx - lookbackTotal;
            middleIdx = trailingIdx + i;
            todayIdx = middleIdx + i;
            numerator = 0.0;
            numeratorSub = 0.0;
            // for( i = middleIdx; i >= trailingIdx; i -= 1 )
            i = middleIdx;
            loop {
                tempReal = *inReal.as_ptr().add(i);
                numeratorSub += tempReal;
                numerator += numeratorSub;
                if i == trailingIdx { break; }
                i -= 1;
            }
            numeratorAdd = 0.0;
            middleIdx += 1;
            for i in (middleIdx as usize)..(todayIdx as usize) + 1 {
                tempReal = *inReal.as_ptr().add(i);
                numeratorAdd += tempReal;
                numerator += numeratorAdd;
            }
            i = (todayIdx as usize) + 1;
            outIdx = 0;
            tempReal = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            *outReal.as_mut_ptr().add(outIdx) = numerator * factor;
            outIdx += 1;
            todayIdx += 1;
            while todayIdx <= endIdx {
                numerator -= numeratorSub;
                numeratorSub -= tempReal;
                tempReal = *inReal.as_ptr().add({ let _v = middleIdx; middleIdx += 1; _v });
                numeratorSub += tempReal;
                numerator += numeratorAdd;
                numeratorAdd -= tempReal;
                tempReal = *inReal.as_ptr().add({ let _v = todayIdx; todayIdx += 1; _v });
                numeratorAdd += tempReal;
                numerator += tempReal;
                tempReal = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
                *outReal.as_mut_ptr().add(outIdx) = numerator * factor;
                outIdx += 1;
            }
        } else {
            i = (optInTimePeriod >> 1) as usize;
            factor = ((i * (i + 1)) as f64);
            factor = 1.0 / factor;
            trailingIdx = startIdx - lookbackTotal;
            middleIdx = trailingIdx + i - 1;
            todayIdx = middleIdx + i;
            numerator = 0.0;
            numeratorSub = 0.0;
            // for( i = middleIdx; i >= trailingIdx; i -= 1 )
            i = middleIdx;
            loop {
                tempReal = *inReal.as_ptr().add(i);
                numeratorSub += tempReal;
                numerator += numeratorSub;
                if i == trailingIdx { break; }
                i -= 1;
            }
            numeratorAdd = 0.0;
            middleIdx += 1;
            for i in (middleIdx as usize)..(todayIdx as usize) + 1 {
                tempReal = *inReal.as_ptr().add(i);
                numeratorAdd += tempReal;
                numerator += numeratorAdd;
            }
            i = (todayIdx as usize) + 1;
            outIdx = 0;
            tempReal = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
            *outReal.as_mut_ptr().add(outIdx) = numerator * factor;
            outIdx += 1;
            todayIdx += 1;
            while todayIdx <= endIdx {
                numerator -= numeratorSub;
                numeratorSub -= tempReal;
                tempReal = *inReal.as_ptr().add({ let _v = middleIdx; middleIdx += 1; _v });
                numeratorSub += tempReal;
                numeratorAdd -= tempReal;
                numerator += numeratorAdd;
                tempReal = *inReal.as_ptr().add({ let _v = todayIdx; todayIdx += 1; _v });
                numeratorAdd += tempReal;
                numerator += tempReal;
                tempReal = *inReal.as_ptr().add({ let _v = trailingIdx; trailingIdx += 1; _v });
                *outReal.as_mut_ptr().add(outIdx) = numerator * factor;
                outIdx += 1;
            }
        }
        (*outNBElement) = outIdx;
        (*outBegIdx) = startIdx;
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
