/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility gen_code.
 *  Any modifications will be lost on next execution of gen_code.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::trix`].
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    #[inline]
    pub fn trix_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        let mut emaLookback: usize = 0_usize;
        emaLookback = self.ema_lookback(optInTimePeriod);
        return (emaLookback * 3 + self.rocr_lookback(1)) as usize;
    }
    /// 1-day Rate-Of-Change (ROC) of a Triple Smooth EMA
    ///
    /// # Arguments
    ///
    /// * `startIdx` - Start index for calculation range
    /// * `endIdx` - End index for calculation range (inclusive)
    /// * `inReal` - Input price series
    /// * `optInTimePeriod` - Number of period (default: 30, range: 1..=100000)
    /// * `outBegIdx` - First valid output index
    /// * `outNBElement` - Number of valid output elements
    /// * `outReal` - Output values
    pub fn trix(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut nbElement: usize = 0_usize;
        let mut begIdx: usize = 0_usize;
        let mut totalLookback: usize = 0_usize;
        let mut emaLookback: usize = 0_usize;
        let mut rocLookback: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        let mut nbElementToOutput: usize = 0_usize;
        emaLookback = self.ema_lookback(optInTimePeriod);
        rocLookback = self.rocr_lookback(1);
        totalLookback = emaLookback * 3 + rocLookback;
        if startIdx < totalLookback {
            startIdx = totalLookback;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        nbElementToOutput = endIdx - startIdx + 1 + totalLookback;
        tempBuffer = vec![0.0_f64; (nbElementToOutput * 1) as usize];
        retCode = self.ema_unguarded(startIdx - totalLookback, endIdx, inReal, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= 1;
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= emaLookback;
        retCode = self.roc_unguarded(0, nbElementToOutput, &tempBuffer, 1, &mut begIdx, outNBElement, outReal);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        return RetCode::Success;
    }
    #[inline]
    pub fn trix_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut nbElement: usize = 0_usize;
        let mut begIdx: usize = 0_usize;
        let mut totalLookback: usize = 0_usize;
        let mut emaLookback: usize = 0_usize;
        let mut rocLookback: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        let mut nbElementToOutput: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        assert!(endIdx - startIdx < outReal.len());
        emaLookback = self.ema_lookback(optInTimePeriod);
        rocLookback = self.rocr_lookback(1);
        totalLookback = emaLookback * 3 + rocLookback;
        if startIdx < totalLookback {
            startIdx = totalLookback;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        nbElementToOutput = endIdx - startIdx + 1 + totalLookback;
        tempBuffer = vec![0.0_f64; (nbElementToOutput * 1) as usize];
        retCode = self.ema_unguarded(startIdx - totalLookback, endIdx, inReal, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= 1;
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= emaLookback;
        retCode = self.roc_unguarded(0, nbElementToOutput, &tempBuffer, 1, &mut begIdx, outNBElement, outReal);
        if retCode != RetCode::Success || (((*outNBElement)) as usize) == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        return RetCode::Success;
        } // unsafe
    }
}
/* Generated */

/***************/
/* End of File */
/***************/
