/* TA-LIB Copyright (c) 1999-2025, Mario Fortier
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or
 * without modification, are permitted provided that the following
 * conditions are met:
 *
 * - Redistributions of source code must retain the above copyright
 *   notice, this list of conditions and the following disclaimer.
 *
 * - Redistributions in binary form must reproduce the above copyright
 *   notice, this list of conditions and the following disclaimer in
 *   the documentation and/or other materials provided with the
 *   distribution.
 *
 * - Neither name of author nor the names of its contributors
 *   may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * REGENTS OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/* Important:
 *  This file is automatically generated by the utility ta_codegen.
 *  Any modifications will be lost on next execution of ta_codegen.
 *
 *  Modifications should instead be done with the "C" source file
 *  in ta-lib\src\ta_func
 */

/* List of contributors:
 *
 *  Initial  Name/description
 *  -------------------------------------------------------------------
 *  MF       Mario Fortier
 *  AA       Andrew Atkinson
 *
 * Change history:
 *
 *  MMDDYY BY   Description
 *  -------------------------------------------------------------------
 *  112400 MF   Template creation.
 *  052603 MF   Adapt code to compile with .NET Managed C++
 *  020605 AA   Fix #1117656. NULL pointer assignement.
 */

// Import types from parent module
use super::*;

// Allow non-snake-case names to maintain TA-Lib API compatibility
#[allow(non_snake_case)]
#[allow(unused_variables)]
#[allow(dead_code)]
#[allow(unused_mut)]
#[allow(unused_assignments)]
impl Core {
    /// Lookback period for [`Core::trix`]: the number of leading input values consumed before the
    /// first output value can be produced.
    ///
    /// # Arguments
    ///
    /// * `optInTimePeriod` — EMA period used at each of the three smoothing passes (default 30,
    ///   range 1..=100000)
    ///
    /// Returns `usize::MAX` when a parameter is out of range. Integer parameters accept `i32::MIN`
    /// to select their default value.
    #[inline]
    pub fn trix_lookback(&self, mut optInTimePeriod: i32) -> usize {
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return usize::MAX;
        }
        let mut emaLookback: usize = 0_usize;
        emaLookback = self.ema_lookback(optInTimePeriod);
        return (emaLookback * 3 + self.rocr_lookback(1)) as usize;
    }
    /// 1-day Rate-Of-Change of a triple-smoothed EMA of the input. Momentum oscillator that filters
    /// out price moves shorter than the chosen period. Oscillates around zero; sign, zero-crossings
    /// and slope signal momentum direction.
    ///
    /// # Formula
    ///
    /// ```text
    /// E1 = EMA(inReal, n); E2 = EMA(E1, n); E3 = EMA(E2, n); TRIX = ROC_1(E3) = 100 * (E3_today/E3_yesterday - 1)
    /// ```
    ///
    /// # Notes
    ///
    /// * The final rate-of-change step yields 0 when the previous smoothed value is exactly zero,
    ///   rather than being undefined.
    ///
    /// # Arguments
    ///
    /// * `startIdx` — Start index of the requested calculation range.
    /// * `endIdx` — End index of the requested calculation range (inclusive).
    /// * `inReal` — Source series to smooth.
    /// * `optInTimePeriod` — EMA period used at each of the three smoothing passes (default 30,
    ///   range 1..=100000)
    /// * `outBegIdx` — Set to the input index of the first output value.
    /// * `outNBElement` — Set to the number of output values written.
    /// * `outReal` — 1-day percent ROC of the triple EMA.
    ///
    /// Integer parameters accept `i32::MIN` to select their default value.
    ///
    /// # Errors
    ///
    /// Returns [`RetCode::OutOfRangeStartIndex`] when `endIdx < startIdx`, and
    /// [`RetCode::BadParam`] when an optional parameter is outside its documented range.
    ///
    /// # Panics
    ///
    /// Input slices must cover `startIdx..=endIdx` and output slices must hold the number of values
    /// produced for that range: undersized slices panic or, for functions that forward to unchecked
    /// internals, cause undefined behavior. Sizing every output slice to the input length is always
    /// sufficient.
    ///
    /// # Examples
    ///
    /// ```
    /// use ta_lib::{Core, RetCode};
    ///
    /// let data: Vec<f64> = (0..252).map(|i| 100.0 + 10.0 * (0.1 * i as f64).sin()).collect();
    ///
    /// let core = Core::new();
    /// let mut out_beg = 0;
    /// let mut out_nb = 0;
    /// let mut out = vec![0.0; 252];
    ///
    /// let ret = core.trix(0, data.len() - 1, &data, 30, &mut out_beg, &mut out_nb, &mut out);
    /// assert_eq!(ret, RetCode::Success);
    /// assert!(out_nb > 0);
    /// ```
    ///
    /// # See also
    ///
    /// [`Core::ema`] · [`Core::roc`] · [`Core::rocr`] · [`Core::tema`]
    ///
    /// Further reading: [ta-lib.org/functions/trix](https://ta-lib.org/functions/trix/)
    #[doc(alias = "TripleExponentialAverage")]
    pub fn trix(
        &self,
        startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        if endIdx < startIdx {
            return RetCode::OutOfRangeStartIndex;
        }
        if ((optInTimePeriod) as i32) == (i32::MIN) {
            optInTimePeriod = 30;
        } else if (((optInTimePeriod) as i32) < 1) || (((optInTimePeriod) as i32) > 100000) {
            return RetCode::BadParam;
        }
        let mut startIdx = startIdx;
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut nbElement: usize = 0_usize;
        let mut begIdx: usize = 0_usize;
        let mut totalLookback: usize = 0_usize;
        let mut emaLookback: usize = 0_usize;
        let mut rocLookback: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        let mut nbElementToOutput: usize = 0_usize;
        // Adjust the startIdx to account for the lookback.
        emaLookback = self.ema_lookback(optInTimePeriod);
        rocLookback = self.rocr_lookback(1);
        totalLookback = emaLookback * 3 + rocLookback;
        if startIdx < totalLookback {
            startIdx = totalLookback;
        }
        // Make sure there is still something to evaluate.
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        nbElementToOutput = endIdx - startIdx + 1 + totalLookback;
        // Allocate a temporary buffer for performing
        // the calculation.
        tempBuffer = vec![0.0_f64; (nbElementToOutput * 1) as usize];
        // Calculate the first EMA
        retCode = self.ema_unguarded(startIdx - totalLookback, endIdx, inReal, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        // Verify for failure or if not enough data after
        // calculating the EMA.
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= 1;
        // Make this variable zero base from now on.
        // Calculate the second EMA
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        // Verify for failure or if not enough data after
        // calculating the EMA.
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        // Calculate the third EMA
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        // Verify for failure or if not enough data after
        // calculating the EMA.
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        // Calculate the 1-day Rate-Of-Change
        nbElementToOutput -= emaLookback;
        retCode = self.roc_unguarded(0, nbElementToOutput, &tempBuffer, 1, &mut begIdx, outNBElement, outReal);
        // Verify for failure or if not enough data after
        // calculating the rate-of-change.
        if retCode != RetCode::Success || ((*outNBElement) as usize) == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        return RetCode::Success;
    }
    /// Unchecked variant of [`Core::trix`], used for internal cross-indicator calls.
    ///
    /// Skips parameter validation and uses unchecked indexing internally. Every argument must
    /// satisfy the constraints documented on [`Core::trix`]; an out-of-range parameter, an input
    /// slice not covering `startIdx..=endIdx`, or an undersized output slice may panic or cause
    /// undefined behavior. Prefer [`Core::trix`].
    #[inline]
    pub fn trix_unguarded(
        &self,
        mut startIdx: usize,
        endIdx: usize,
        inReal: &[f64],
        mut optInTimePeriod: i32,
        outBegIdx: &mut usize,
        outNBElement: &mut usize,
        outReal: &mut [f64],
    ) -> RetCode {
        let mut tempBuffer: Vec<f64> = Vec::new();
        let mut nbElement: usize = 0_usize;
        let mut begIdx: usize = 0_usize;
        let mut totalLookback: usize = 0_usize;
        let mut emaLookback: usize = 0_usize;
        let mut rocLookback: usize = 0_usize;
        let mut retCode: RetCode = RetCode::Success;
        let mut nbElementToOutput: usize = 0_usize;
        unsafe {
        assert!(endIdx < inReal.len());
        let _assertLb = self.trix_lookback(optInTimePeriod);
        let _assertStart = if startIdx > _assertLb { startIdx } else { _assertLb };
        assert!(_assertStart > endIdx || endIdx - _assertStart < outReal.len());
        emaLookback = self.ema_lookback(optInTimePeriod);
        rocLookback = self.rocr_lookback(1);
        totalLookback = emaLookback * 3 + rocLookback;
        if startIdx < totalLookback {
            startIdx = totalLookback;
        }
        if startIdx > endIdx {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return RetCode::Success;
        }
        (*outBegIdx) = startIdx;
        nbElementToOutput = endIdx - startIdx + 1 + totalLookback;
        tempBuffer = vec![0.0_f64; (nbElementToOutput * 1) as usize];
        retCode = self.ema_unguarded(startIdx - totalLookback, endIdx, inReal, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= 1;
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= emaLookback;
        retCode = self.ema_unguarded(0, nbElementToOutput, unsafe { std::slice::from_raw_parts(tempBuffer.as_ptr(), tempBuffer.len()) }, optInTimePeriod, &mut begIdx, &mut nbElement, &mut tempBuffer[..]);
        if retCode != RetCode::Success || nbElement == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        nbElementToOutput -= emaLookback;
        retCode = self.roc_unguarded(0, nbElementToOutput, &tempBuffer, 1, &mut begIdx, outNBElement, outReal);
        if retCode != RetCode::Success || ((*outNBElement) as usize) == 0 {
            (*outNBElement) = 0;
            (*outBegIdx) = 0;
            return retCode;
        }
        return RetCode::Success;
        } // unsafe
    }
}
/***************/
/* End of File */
/***************/
