name: Generate Stock Data

on:
  schedule:
    - cron: '30 6 * * *'  # 每天 UTC 6:30 執行一次, UTC+8 14:30
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc
          sudo apt-get install -y python3-dev
          sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev
          sudo apt-get install -y wget tar

      - name: Download and build ta-lib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install

      - name: Verify TA-Lib installation
        run: |
          ls /usr/lib | grep ta_lib
          
      - name: Configure shared libraries
        run: |
          echo "/usr/lib" | sudo tee -a /etc/ld.so.conf.d/ta-lib.conf
          sudo ldconfig  # 更新動態鏈接器的緩存
          export LD_LIBRARY_PATH=/usr/lib:$LD_LIBRARY_PATH
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas jinja2
          pip install ta-lib
      
      - name: Print working directory
        run: pwd

      - name: List files in the repository
        run: ls -la
      
      - name: Run Python script
        run: |
          python generate_stock_data.py
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.STOCKS_GITHUB_TOKEN }}
          publish_dir: ./
