name: Generate Stock Data

on:
  schedule:
    - cron: '0 9 * * *'  # 每天 UTC 9:00 执行一次
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          sudo apt-get install -y python3-dev
          sudo apt-get install -y libxml2-dev libxslt1-dev zlib1g-dev
          sudo apt-get install -y libta-lib0 libta-lib0-dev
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas jinja2
          pip install ta-lib
      
      - name: Print working directory
        run: pwd

      - name: List files in the repository
        run: ls -la
      
      - name: Run Python script
        run: |
          python generate_stock_data.py
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
